### ISSUE TITLE
Add Python 3.11 to Test Matrix

### ISSUE THREAD

**Issue by yzguy** [octodns/octodns#1006]
Python is up to 3.11.3 (as of 5/19/23) version-wise, so we should add it to our test matrix

**Comment by ross** [comment]
Looks like 3.11 is active now, 3.7 is still alive a little bit longer:

https://devguide.python.org/versions/#versions

Unfortunately we have to make this change across all the repos so it's a bit of a slog. I have some dependabot alerts i want to work though as well so I'll group that and probably aim to go through and do it all sometime next week.

**Comment by ross** [comment]
Oh, just noticed you assigned yourself. Feel free to do it for octoDNS, but guessing you probably weren't thinking of doing it for all ~30 repos :grin: I'll get whatever you haven't done next week

**Comment by yzguy** [comment]
Just notes before I come and close this issue

octodns-dyn doesn't have 3.10 either, but that's expected as  the `dyn` library doesn't support it, so will be skipping 3.11 as well

**Comment by yzguy** [comment]
All repos done except `octodns-edgecenter`, it has some failures from `./script/cibuild-setup-y`. Will need to investigate.

**Comment by yzguy** [comment]
Rebased octodns-edgecenter onto main and that seemed to clear up the tests, merged it. 3.11 has been added everywhere that it needs to be.

**Comment by ross** [comment]
> Rebased octodns-edgecenter onto main and that seemed to clear up the tests

Yeah. I got things working as part of the requirements update this morning, https://github.com/octodns/octodns-edgecenter/pull/10/commits/1b6f97a6f2543d5f3c88defe686fe7cba2a97e88
