### ISSUE TITLE
script/release should use PyPi API Token

### ISSUE THREAD

**Issue by yzguy** [octodns/octodns#1016]
The current `script/release` ends with `twine upload` which then asks for username/password, but as we enforce 2FA we need to use API token.

```
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 401 Unauthorized from https://upload.pypi.org/legacy/
         User <user> has two factor auth enabled, an API Token or Trusted Publisher must be used to upload in place of password.
```

It's likely worth it to just update the `script/release` to specify the username for the token per the [docs](https://pypi.org/help/#invalid-auth) to be `__token__`, and the password is the API Token (leaving off -p) will request it from the user.

This would be the `-u` option on twine.

```
  -u USERNAME, --username USERNAME
                        The username to authenticate to the repository (package index) as. (Can also be
                        set via TWINE_USERNAME environment variable.)
  -p PASSWORD, --password PASSWORD
                        The password to authenticate to the repository (package index) with. (Can also
                        be set via TWINE_PASSWORD environment variable.)
```

**Comment by ross** [comment]
Looks like I have them set in `~/.pypirc`, 

```console
coho:octodns ross$ sed 's/password = .*/password = [secret-token]/' ~/.pypirc
[pypi]
  username = __token__
  password = [secret-token]
```

Perhaps we add a `test -e ~/.pypirc` into `script/release` and suggest creating one with the snippet above as an example?

**Comment by yzguy** [comment]
That works!
