### ISSUE TITLE
Allow usage of ALIAS record on non-apex names

### ISSUE THREAD

**Issue by nogweii** [octodns/octodns#1021]
At least for PowerDNS, it's implementation of ALIAS is not limited to being just at the apex.

For example:

```bash
$ sudo pdnsutil add-record 'example.org.' 'this.is.an.alias' ALIAS 600 'google.com'
New rrset:
this.is.an.alias.example.org. 600 IN ALIAS google.com
$ dig @powerdns.localhost this.is.an.alias.example.org
```

**Comment by ross** [comment]
> At least for PowerDNS, it's implementation of ALIAS is not limited to being just at the apex.

octoDNS's `ALIAS` is essentially `CNAME` for the apex. The goal of things is to be as spec compliant as possible and to be as consistent behavior-wise across providers when that isn't doable. This is a case where `ALIAS`'s definition is chosen to be as consistent across providers as possible. If you were to define a non-apex `ALIAS` in PowerDNS you wouldn't be able to push that record to other providers. If you instead use a CNAME all providers would be able to get the same end behavior.

**Comment by nogweii** [comment]
I'm currently only using OctoDNS against PowerDNS.

Would it make sense to include an option somewhere to relax that constraint as an opt-in behavior?

**Comment by ross** [comment]
Without specifics of the sitaution I'm not sure, but does [`lenient`](https://github.com/octodns/octodns/blob/main/docs/records.md#lenience) allow you to create them elsewhere? It should turn the exception into a warning. From a quick glance I think `PowerDNSProvider` would probably just chug along and management then
