### ISSUE TITLE
Installing with OpenBSD 7.3 problems

### ISSUE THREAD

**Issue by quistian** [octodns/octodns#1041]
The crypto part of the build fails. I've seen this with other OpenBSD python installs.
Not sure what the  fix is:

Python: 3.10.11
          platform: OpenBSD-7.3-amd64-64bit-ELF
          pip: n/a
          setuptools: 68.0.0
          setuptools_rust: 1.6.0
          rustc: 1.68.0 (2c8cc3432 2023-03-06) (built from a source tarball)
          =============================DEBUG ASSISTANCE=============================

      error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path src/rust/Cargo.toml --release -v --features pyo3/extension-module --crate-type cdylib --` failed with code 101
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Successfully built PyYaml
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

**Comment by ross** [comment]
This is likely an issue with the `cryptography` module and not octoDNS. octoDNS is all pure python, nothing is compiled, so will run anywhere python will run. Guessing whatever is happening is specific to `cryptography` on OpenBSD as I haven't seen that on linux system. You might check with that project https://github.com/pyca/cryptography

**Comment by quistian** [comment]
This is now resolved, with OpenBSD 7.4. I can also be resolved  I discovered by using the:

--system-site-package option when setting up the python virtual environment.

**Comment by istr** [comment]
@quistian closing this, as you pointed out that it is fixed for 7.4 and there is a workaround using `--system-site-package` for 7.3.
