### ISSUE TITLE
does failing tests affect the build?

### ISSUE THREAD

**Issue by soheilade** [octodns/octodns#1042]
hi all, i am new here, i tried to modify some tests to fail but i still can build the project succeefully. I wonder if my changes leads to some tests being failed, I may not notice it if i donot run the tests explicitly?

**Comment by ross** [comment]
octoDNS uses the [Scripts to rule them all](https://github.com/github/scripts-to-rule-them-all) pattern and generally everything required for the development process lives under the `./scripts/` directory. `./script/coverage` will run the tests and check for code coverage. There's also a pre-commit hook [.git_hooks_pre-commit](https://github.com/octodns/octodns/blob/main/.git_hooks_pre-commit) that is installed by `./script/bootstrap` that's essentially the same as what's run as an action when code is pushed up to GitHub branches.

**Comment by soheilade** [comment]
thanks @ross , so after changes, to make sure tests pass, i should run the coverage script manually, right?

**Comment by soheilade** [comment]
perfect, thanks
