### ISSUE TITLE
Bluecat provider

### ISSUE THREAD

**Issue by quistian** [octodns/octodns#1055]
I can't see any module for BlueCat as a provider. I've asked on one of their forums and no one spoke up.
Do you know if anyone is working or has worked on this before?

**Comment by ross** [comment]
I'm not aware of a BlueCat provider or anyone who's worked towards building one. the base level, non-dynamic, providers are fairly simple to write. [PowerDnsProvider](https://github.com/octodns/octodns-powerdns) is a fairly clean example, but one of the others may be more suitable if it happens to have an API closer to BlueCat's.

**Comment by quistian** [comment]
Great thanks. I'll have a look at PowerDNS.

**Comment by quistian** [comment]
I've got a BlueCat Provider module written, testing out a few more RR types.
One feature or bug, is that when I sync from BlueCat to the local Yaml Provider, the sync always occurs, even though there's an up to date YAML file locally for the test zone in question. Is this normal? Or is there something I am missing?

**Comment by ross** [comment]
> One feature or bug, is that when I sync from BlueCat to the local Yaml Provider, the sync always occurs, even though there's an up to date YAML file locally for the test zone in question. Is this normal? Or is there something I am missing?

That's a known/documented behavior of the `YamlProvider`.  I've looked at making it a full-fledged provider in the past, but the issue is that there's no clean way to add things to an existing file and preserve the comments/formatting/details with any of the yaml libs I've found. So it'd essentially be re-writing the file every time anyway and at most would just tell you what's missing. It'd also have to rely on the "desired" zone in the plan which would make the whole plan/apply (processors) stuff moot. Anyway, it's likely to always be that way for "reasons."

**Comment by quistian** [comment]
So.... Say I am syncing 100s of zones from BC to YAML... There's no real way to determine say that:

There are three changes:
bozo.the.clown.net A record is updated
frodo.hobbit.org MX record is created
faster.openai.azure.com CNAME record was deleted.

**Comment by quistian** [comment]
And what's the proper way to add my octodns-bluecat module? Vetting etc.

**Comment by ross** [comment]
Sorry missed this coming through the other day. 


> So.... Say I am syncing 100s of zones from BC to YAML... There's no real way to determine say that:
> There are three changes:

Not currently. It would be theoretically possible to create a plan saying what's missing from a local Yaml, but it wouldn't be possible to actually do the sync and add in the missing records. It would have to replace the whole file and be a completely new write. To my knowledge there's no YAML libraries that support updates without blowing away everything else.
