### ISSUE TITLE
Can not get dynamic conifguration to work at all.

### ISSUE THREAD

**Issue by quistian** [octodns/octodns#1056]
When I copy and paste the example dynamic configuration file, and have a directory ( ./zones ) in the YamlProvider portion, full of
yaml files with RRs, e.g.

bozo.com.yaml
rufus.net.yaml

And run the octodns-sync command, I end up with the error message:

```
venv-octodns/lib/python3.11/site-packages/octodns/manager.py", line 394, in _populate_and_plan
    zone = self.get_zone(zone_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File .... /venv-octodns/lib/python3.11/site-packages/octodns/manager.py", line 869, in get_zone
    raise ManagerException(
octodns.manager.ManagerException: Invalid zone name *, missing ending dot
```

I thought the list of zones configurations would be dynamically created by the equivalent of a 'ls' on the directory.

**Comment by ross** [comment]
> I thought the list of zones configurations would be dynamically created by the equivalent of a 'ls' on the directory.

This is now supported in HEAD, but no releases with the functionality have been cut yet. If you're trying to use `*:` as a dynamic zone config with 1.0.0 that'd be the problem. 

You can pip install a new enough version with

```
$ pip install -e git+https://git@github.com/octodns/octodns.git@8237aa955d0f489180daf131b744dbc3d22ba986#egg=octodns
```

As should be obvious that's not released code so caveat emptor

**Comment by quistian** [comment]
Thanks. Helpful. I can generate a static config, given I've got about 100 zones to worry about.

**Comment by quistian** [comment]
Can be marked as closed.
