### ISSUE TITLE
Multiple dynamic zones fail to load their respective zones

### ISSUE THREAD

**Issue by viranch** [octodns/octodns#1068]
[This](https://github.com/octodns/octodns/blob/v1.1.1/octodns/manager.py#L519C52-L519C52) is causing a wrong re-use of `sources` for subsequent dynamic zones.

Should be an easy fix with a separate variable, I'll see if I can put some time in it.

**Comment by ross** [comment]
Doh. That's a pretty big oversight. Inner sources should just use another name to avoid clobbering the passed in one for subsequent trips through the loop. I should be somewhere that I can sit down and dig into this tomorrow afternoon.

**Comment by viranch** [comment]
Its always the tests that take up more time 😄
