### ISSUE TITLE
Processor to filter out records based on value

### ISSUE THREAD

**Issue by Solvik** [octodns/octodns#1093]
Hi there!

I'm opening this issue to discuss the ability to add a processor based on record's value

We use octodns to synchronize an internal PowerDNS instance to route53. We have the case where internal records are then synchronized to a public DNS zone and we want to avoid that.

I've seen that in the latest versions of octodns, you've introduced an amazing feature such as processors.

Would you be open to a contribution ? 

I see two ways:
- create a dedicated ExcludePrivateIpFilter
- create a generic ValueRejectlistFilter that would use a regex list `/ ^127\./` etc.

What do you think is the best ? I can do the contribution

**Comment by ross** [comment]
> I see two ways:
> ...

For IP addresses i think filtering by a list of CIDRs would be the appropriate tool for the job. It could potentially have a boolean flag parameter that auto added the private ranges: `127.0.0.0/8`, `172.16.0.0/12`, `192.168.0.0/16`. Potentially some other stuff off the full reserved IP address list, https://en.wikipedia.org/wiki/Reserved_IP_addresses. Obviously should support IPv6 as well.

It'd be possible to filter on the value of other record types like TXT too, but without a specific use case I'd be hesitant to implement it. Value based filtering would get really complicated messy if it tried to extend to non-trivial types.

**Comment by Solvik** [comment]
Ok thanks for your feedback, I'll propose a MR :)

**Comment by thystips** [comment]
Hello!

I suggest implementing Allow and Reject filters options for specific PTR records too.

**Comment by ross** [comment]
> I suggest implementing Allow and Reject filters options for specific PTR records too.

Not sure I follow. What PTRs are included would be driven off the zones configured since the zone is the subnet. To avoid pushing private PTR zones up they would just be left out of the (public) targets.

If you're talking about filtering on the value side of the PTR that'd be a totally different tool, and would apply equally to other record types. That'd be doable, but definitely not part of this PTR.

**Comment by thystips** [comment]
I read issue to fast and only keep in mind filtering and record's value. I will open another issue !

**Comment by ross** [comment]
Closed by https://github.com/octodns/octodns/pull/1094 and https://github.com/octodns/octodns/pull/1098 adds some extra functionality.
