### ISSUE TITLE
auto-arpa and dynamic zone config

### ISSUE THREAD

**Issue by baest** [octodns/octodns#1095]
Hi

auto-arpa doesn't currently support dynamic zone config as it doesn't implement the list-zones method. I would to use the combination. Basically I see a directory with arpa zones (with auto-arpa enabled) consisting of only NS records. I would like to have that list of zones populated automatically. I've tried and everything works for me if I add:

```
    def list_zones(self):
        return set()
```
To octodns/processor/arpa.py. I can provide a patch if needed. Would I need to try to make a test of this as well?

**Comment by istr** [comment]
A PR would be highly welcome. I think that adding a test would be simple.
You can set up and test locally using `script/bootstrap` and `script/cibuild`. This includes running the test and coverage.

**Comment by ross** [comment]
Returning empty, meaning it doesn't create any zones would allow using it in dynamic config situations, but people would have to know to cause those zones to exist some other way, i.e. with config files as you mention.  Not ideal, but I'm not seeing a better option.

In general I think that the phase at which `list_zones` is called is too early, before auto-arpa would know what zones it'll be creating so there's no way to do something better.

If we go forward with the empty set path we'd definitely need to document it clearly in a prominent place.

**Comment by baest** [comment]
Thanks for the quick reply and sorry being slow on my end. I will get back to you with a tested patch along with an extra "Notes" in the docs/auto_arpa.md document. IMO this will not make anything worse than it is today, but I very much agree that it could be a big gotcha if it isn't documented.

**Comment by baest** [comment]
Sorry for the very progress on the PR, but I've been distracted by other things. I have added it now:

https://github.com/octodns/octodns/pull/1128

**Comment by ross** [comment]
Closed by https://github.com/octodns/octodns/pull/1128
