### ISSUE TITLE
"pip install --no-binary" fails

### ISSUE THREAD

**Issue by viranch** [octodns/octodns#1096]
I have a use-case to not use binary wheel for installing octodns, but the pip install command fails:

```
(env) → /tmp/testenv » python -m pip install --no-binary octodns octodns==1.0.0
Collecting octodns==1.0.0
  Downloading octodns-1.0.0.tar.gz (532 kB)
     |████████████████████████████████| 532 kB 5.2 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
WARNING: Discarding https://files.pythonhosted.org/packages/6a/a9/fccc8c6120d51ea98d67a455980094a18eacf8e581c68a1e78ca0044c8cf/octodns-1.0.0.tar.gz#sha256=ccfc9c17789f71879bb10d13cba6bfe85e8eb2ba4b7a04bd3d13f10760afd502 (from https://pypi.org/simple/octodns/) (requires-python:>=3.8). Requested octodns==1.0.0 from https://files.pythonhosted.org/packages/6a/a9/fccc8c6120d51ea98d67a455980094a18eacf8e581c68a1e78ca0044c8cf/octodns-1.0.0.tar.gz#sha256=ccfc9c17789f71879bb10d13cba6bfe85e8eb2ba4b7a04bd3d13f10760afd502 has inconsistent version: filename has '1.0.0', but metadata has '1.0.0+unknown'
ERROR: Could not find a version that satisfies the requirement octodns==1.0.0 (from versions: 0.8.0, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.16, 0.9.17, 0.9.18, 0.9.19, 0.9.20, 0.9.21, 1.0.0rc0, 1.0.0rc1, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.2.1)
ERROR: No matching distribution found for octodns==1.0.0
(env) → /tmp/testenv »
```

This seems to be the culprit, but can't figure out why the metadata has this weird version:
```
inconsistent version: filename has '1.0.0', but metadata has '1.0.0+unknown'
```

This is happening for all versions of octodns as well as octodns-* packages.

**Comment by ross** [comment]
I assume it's not getting into the OCTODNS_RELEASE branch of 

https://github.com/octodns/octodns/blob/f5fcb1ae8a4c7f4ee01511521b0e592507bbc94a/setup.py#L52-L62

for some reason. No clue why that'd happen for source and not wheel though.

**Comment by ross** [comment]
Test build locally using script release w/o the tagging and uploading:

```console
coho:octodns ross$ ll dist/
total 1272
-rw-r--r--@ 1 ross  staff   92847 Nov  9 16:32 octodns-1.2.1-py3-none-any.whl
-rw-r--r--@ 1 ross  staff  555691 Nov  9 16:32 octodns-1.2.1.tar.gz
```

It installs fine:

```console
(env) coho:tmp ross$ pip install ~/octodns/octodns/dist/octodns-1.2.1.tar.gz
Processing /Users/ross/octodns/octodns/dist/octodns-1.2.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyYaml>=4.2b1 (from octodns==1.2.1+unknown)
  Obtaining dependency information for PyYaml>=4.2b1 from https://files.pythonhosted.org/packages/bc/06/1b305bf6aa704343be85444c9d011f626c763abb40c0edc1cad13bfd7f86/PyYAML-6.0.1-cp312-cp312-macosx_10_9_x86_64.whl.metadata
  Using cached PyYAML-6.0.1-cp312-cp312-macosx_10_9_x86_64.whl.metadata (2.1 kB)
Collecting dnspython>=2.2.1 (from octodns==1.2.1+unknown)
  Obtaining dependency information for dnspython>=2.2.1 from https://files.pythonhosted.org/packages/f6/b4/0a9bee52c50f226a3cbfb54263d02bb421c7f2adc136520729c2c689c1e5/dnspython-2.4.2-py3-none-any.whl.metadata
  Using cached dnspython-2.4.2-py3-none-any.whl.metadata (4.9 kB)
Collecting fqdn>=1.5.0 (from octodns==1.2.1+unknown)
  Using cached fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Collecting idna>=3.3 (from octodns==1.2.1+unknown)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting natsort>=5.5.0 (from octodns==1.2.1+unknown)
  Obtaining dependency information for natsort>=5.5.0 from https://files.pythonhosted.org/packages/ef/82/7a9d0550484a62c6da82858ee9419f3dd1ccc9aa1c26a1e43da3ecd20b0d/natsort-8.4.0-py3-none-any.whl.metadata
  Using cached natsort-8.4.0-py3-none-any.whl.metadata (21 kB)
Collecting python-dateutil>=2.8.1 (from octodns==1.2.1+unknown)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.1->octodns==1.2.1+unknown)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached dnspython-2.4.2-py3-none-any.whl (300 kB)
Using cached natsort-8.4.0-py3-none-any.whl (38 kB)
Using cached PyYAML-6.0.1-cp312-cp312-macosx_10_9_x86_64.whl (178 kB)
Building wheels for collected packages: octodns
  Building wheel for octodns (pyproject.toml) ... done
  Created wheel for octodns: filename=octodns-1.2.1+unknown-py3-none-any.whl size=92964 sha256=9a6ee097d5a869382c7f3f50af2778e4df95c01064aadb8878e813d14ad6b396
  Stored in directory: /Users/ross/Library/Caches/pip/wheels/a8/a4/a7/ae01735c5d2bb2c840e951beb447b0376e345feb37fc61230c
Successfully built octodns
Installing collected packages: six, PyYaml, natsort, idna, fqdn, dnspython, python-dateutil, octodns
Successfully installed PyYaml-6.0.1 dnspython-2.4.2 fqdn-1.5.1 idna-3.4 natsort-8.4.0 octodns-1.2.1+unknown python-dateutil-2.8.2 six-1.16.0
```

**Comment by viranch** [comment]
The `unknown` bit is still showing up: ```Collecting PyYaml>=4.2b1 (from octodns==1.2.1+unknown)```

**Comment by viranch** [comment]
This subshell is probably not picking up the exported envvar? https://github.com/octodns/octodns/blob/main/script/release#L45

**Comment by ross** [comment]
"unknown" doesn't appear anywhere in the output of `./script./release`


> This subshell is probably not picking up the exported envvar? https://github.com/octodns/octodns/blob/main/script/release#L45

quick `echo $OCTODNS_RELEASE` inside the `()` printed `1` as expected. Maybe it's something `python -m build --sdist --wheel` does. Will have to dig into that.

**Comment by ross** [comment]
Added some debugging prints to the version function in setup.py and it always comes out as:

```
OCTODNS_RELEASE=1
rel branch
```

So setup.py seems to be doing the correct thing. Whatever is happening it's further down.

**Comment by ross** [comment]
AH! So the releases are created correctly, but when doing a source install `setup.py` is run by `pip` and at that point the release env var isn't set and things go into the dev/sha branch and land on unknown.

So I guess that mechanism for managing version isn't sufficient. Will have to explore other options for differentiating real releases from random sha (dev) releases

**Comment by viranch** [comment]
Perhaps flip that `OCTODNS_RELEASE` var into something like `OCTODNS_DEV`? When it's set its a dev build, otherwise it's an intentional release.

**Comment by ross** [comment]
The intent was to have an add-on to the version number when people installed by SHA and thus didn't have a released version. Afaict all the env/state of things is identical to your `--no-binary` case so it may be a lost cause. Best path forward is probably just to drop back to using the version in the module and call it a day...

**Comment by ross** [comment]
Interesting, the part after the + is supposed to be ignored for the purpose of version comparisons https://stackoverflow.com/questions/61808433/python-package-version-vs-version-with-local-version-label.

That also sparked a memory of where this all came from, pep404 https://peps.python.org/pep-0440/#local-version-identifiers.

**Comment by viranch** [comment]
OK to cut a new release to fix sdist installs?

**Comment by ross** [comment]
> OK to cut a new release to fix sdist installs?

Yeah it's probably clear to go ahead. https://github.com/octodns/octodns/pull/1102 is the only thing I have oustanding and it can go in a patch or follow on release as it's not critical.
