### ISSUE TITLE
Odd processor query

### ISSUE THREAD

**Issue by quistian** [octodns/octodns#1119]
I have a need to compress or strip off the outermost subdomain...  It does sound odd. 
Given the name of the fqdn is unique, I was wanting a processor that would in effect translate:

q123.123.bozo.net -> q123.bozo.net
n456.456.bozo.net -> n456.bozo.net
y222_test.NNN.bozo.net -> y222_test.bozo.net
etc.. 

Looking at the current filter.py processor code, is this something a customization one could do?
At the present time I am filtering the local yaml data. 

Thanks.

**Comment by ross** [comment]
Not something that would currently be possible with octoDNS code as is. Processors are focused on record data & plans. There's no plug-in arch for modifying the zone data atm. 

You could create a custom provider that inherits from `YamlProvider` and does whatever mucking you want/need to do with the zone data. Should be fairly simple & straightforward to do that. 

Otherwise I'll have to look around in the code and see if there's a clean/clear pattern for how processing zones would fit into things.

**Comment by quistian** [comment]
Many thanks. That's a start. And by "inherits" from YamlProvider, do you mean start with the current YamlProvider code as a template, and manage the file step of writing the data to the local YAML files?

**Comment by ross** [comment]
So I was assuming you had sub zones configured and needed to muck with their names to push the data to the parent zone. E.g. you have `config/123.bozo.net.yaml` on disk and configured in the octodns yaml file and want `bozo.net.` to actually have the data pushed to it.

If instead you have `config/bozo.net.yaml` and have `q123.123:` defined as a record in the zone you should be able to do that modification in a custom processor (it would probably be too unique of a use case to be included in octoDNS core.)

**Comment by quistian** [comment]
Yes.. What I want is to have the data at the leaf subdomain to be pushed up one level.  In effect take off the outermost subdomain combining and pushing all the RRs up one level. I have a case where by design none of the names will collide. I shall look at #1120. Thanks.

**Comment by ross** [comment]
If you're merging records between two zones (pushing trimming a childs records to fit in its parents) #1120 probably won't be of use. If all of the records are already in a single octoDNS/provider zone and some just have the extra subdomain that you want to remove a custom processor should be able to do that.

Feel like we're to the point where it'll probably require knowing the full setup for me to be able to make suggestions which may or may not make sense/be needed :grin:

**Comment by quistian** [comment]
I am in the case as you described above.  In short, I am using a subdomain, in my case a 3 digit number, to allow authorization at the RR level.  E.g. Azure private DNS names e.g. privatelink.openai.azure.com, are managed as resources, on per name/service.  There's no way to delegate authority on a RR basis.  Given one has 100s of users using the same service, the Azure dashboard e.g. allows everyone to view, add, modify, delete all A records.  So I am using  the BlueCat address manager, making sure by naming convention, that all host names are unique. People have authority now only in their own zone. E.g. 278.privatelink.openai.azure.com, others in theirs e.g. 321.privatelink.openai.azure.com.  The goal is to merge all the records, stripping off now the artificial departmental subdomain e.g. 278 and 321, and eventually use octodns-azure to push them into the Azure cloud.  I've built an octodns-bluecat module to move to and from the YamlProvider.  At present I am then using some Python Yaml libraries to read, strip and then write the data back into another Yaml directory, which will be the source when syncing with Azure.  That's a more detailed view of what I am trying to do.

**Comment by quistian** [comment]
And on the processing front. I know I can turn off the:
WARNING root NS record supported, but no record is configured
message by editing the appropriate code in __init__.py
But is there a mechanism in processor or config or octodns-sync levels?

**Comment by ross** [comment]
> ... That's a more detailed view of what I am trying to do.

OK. You could probably work up a custom Provider, likely inheriting from `YamlProvider` that when asked for `privatelink.openai.azure.com.` loaded up `*.privatelink.openai.azure.com.yaml` for its records. That is assuming you've already gone from bluecat to yaml files.

It should be possible for the bluecat provider do the same sort of logic, i.e. ask it for `privatelink.openai.azure.com.` and it looks for any data in bluecat zones that `endswith('privatelink.openai.azure.com.')` and strips off the extra sub for the names.

> And on the processing front. I know I can turn off the:
> WARNING root NS record supported, but no record is configured
> message by editing the appropriate code in **init**.py
> But is there a mechanism in processor or config or octodns-sync levels?

There's not a way to get rid of the warning short of adding the records to the config. It's an error by default and `strict_supports: false` on the provider will make it __just__ a warning.
