### ISSUE TITLE
OctoDNS dry-run not failing on em dash in txt record

### ISSUE THREAD

**Issue by freekdegreef** [octodns/octodns#1126]
When trying to set this text record `v=spf1 –all` using OctoDNS without `--do-it` (which we use as a validate step in our CI pipeline) OctoDNS fails to pick up the em dash posing as a hyphen. When actually making the changes this results in an error:
```
Invalid value for 'entity.change.additions[example.com.][TXT].rrdata[0]': '"v=spf1 –all"'
```
In our case this is with the Google DNS provider but this might also apply to other providers.

**Comment by ross** [comment]
It looks like utf-8 chars aren't legal in TXT values, but atm i'm having a hard time finding something that definitively says that's the case. 

https://datatracker.ietf.org/doc/html/rfc1035#section-3.3.14 doesn't seem to specify what's legal in a `character-string`, though it's age would lead me to believe it's assuming ASCII.

**Comment by freekdegreef** [comment]
Thanks @ross ✌🏻
