### ISSUE TITLE
CloudFlare Specific Proxied Type / Value

### ISSUE THREAD

**Issue by mhosker** [octodns/octodns#1130]
Hi,

I am currently looking to implement OctoDNS using Cloudflare & NS1, however a number of my records are required to be proxied via CloudFlare even when the DNS query is served by NS1.

I can make this work using a CloudFlare partial CNAME zone, where proxied records that exist in NS1 can be created as CNAMEs pointing back to Cloudflare e.g `www.example.com.cdn.cloudflare.net.`.

However, herein lies my problem... without using two zone files (one for NS1 & one for Cloudflare) is it possible to either specify a per provider value or add an override for CloudFlare specifically. Something like...

```
www:
  octodns:
    cloudflare:
      proxied: true
      type: A
      value: 8.8.8.8
  ttl: 300
  type: CNAME
  value: www.example.com.cdn.cloudflare.net.
```
Where `8.8.8.8` is the value of your secret origin server sitting behind Cloudflare.

I think this feature would be really beneficial (if it doesn't already exist and I have missed it!) as in a lot of cases the reason for proxying behind Cloudflare is to mask the origin IP, so I can see few use cases where you would have split DNS setup with Cloudflare returning a proxied record some of the time and the other provider returning the origin IP the rest of the time.

Additionally, if I were to use two non Cloudflare DNS providers and use Cloudflare as a CDN only, I would run into the same issue whereby the DNS providers would need to return the `.cdn.cloudflare.net.` CNAME record, however Cloudflare would need the true origin A / AAAA / CNAME configured.

Hopefully this makes sense, at the moment its making my deployment a bit tricky as I both don't want duplicate zone files to maintain and additional config OR my origin server IP exposed for non Cloudflare queries (plus it wouldn't work as my origins are all locked down to Cloudflare IPs only)!

As an aside, I love the OctoDNS project and have it successfully working with another zone that is solely Cloudflare. I plan to write some blog posts / produce a video on my rather unorthodox method of running OctoDNS using an Azure DevOps pipeline!

Thanks in advance! :)

**Comment by ross** [comment]
> However, herein lies my problem... without using two zone files (one for NS1 & one for Cloudflare) is it possible to either specify a per provider value or add an override for CloudFlare specifically. Something like...

There's no built in way to accomplish this out of the box as it's a fairly unique setup, at least I haven't run across anyone doing it over the past ~6 years.

I can think of two main routes to manage it w/o having to completely duplicate record data:

The first would be to have 2 config providers, the base one with all the data as you want it in CloudFlare and then the 2nd would have just the overrides for NS1 (or other non-CF providers.) It would set `populate_should_replace: true` and overwrite the values in the base config.

The second would be to define a single config file with either the base config for the Cloudflare config, not sure which would be easier, and a custom processor that implements `Processor.process_target_zone` and modifies the records based on the `target`.

e.g. if the base config had the Cloudflare versions of things the processor could convert records w/proxied enabled to CNAMEs pointing to `f'{record.fqdn}.cdn.cloudflare.net` when the `target` isn't a `CloudflareProvider`

All of this may run into a road block if you have proxied records that live alongside other records at the same node since CNAMEs cannot coexist alongside records of other types. 


> As an aside, I love the OctoDNS project and have it successfully working with another zone that is solely Cloudflare. I plan to write some blog posts / produce a video on my rather unorthodox method of running OctoDNS using an Azure DevOps pipeline!

Nice!

**Comment by mhosker** [comment]
Thanks @ross !

I suspect the reason you may not have run across this before is due to the fact CNAME setup for Cloudflare is only offered in business or enterprise plans, therefore its not very widespread.

Thanks for your suggestions on workarounds, I really like the idea of that processor and it sounds like it would do exactly what I want...

I may have a stab at a Cloudflare processor and submit a pull request.

In my case I am lucky as all the CNAME records (bar the apex) don't coexist with any other records and I deliberately selected NS1 as it has support for ALIAS records (CNAME flattening) at the apex.

So in the processor I would have to check if it was an apex and if so change the non Cloudflare to an ALIAS rather than CNAME.

If you dont see any pull requests from me then assume I used method 1! :)

**Comment by mhosker** [comment]
A quick question as a follow up to this... when using `Processor.process_target_zone` should I expect to see the modified results in the sync noop output?

Also, is there any documentation on writing processors? I have got so far looking at the existing ones, but wondering... is there something special I need to do in regards to registering my processor locally? Or is it just a case of adding the `.py` file under the `processor` directory and then adding it to my config?

Thanks :)

**Comment by ross** [comment]
> A quick question as a follow up to this... when using `Processor.process_target_zone` should I expect to see the modified results in the sync noop output?

Yup. 

> Also, is there any documentation on writing processors?

` BaseProcessor` is faily well documented, at least by OSS standards, and tries to talk about what's called when and all the expectations are. 

https://github.com/octodns/octodns/blob/30f8b4f5f5e9b613c1282615d645e0e2b3f71015/octodns/processor/base.py#L34-L49

>  I have got so far looking at the existing ones, but wondering... is there something special I need to do in regards to registering my processor locally? Or is it just a case of adding the `.py` file under the `processor` directory and then adding it to my config?

So long as it's in the python path it will be auto-magically discovered and loaded via python's normal mechanisms based on the path/module you specify in the yaml config.

**Comment by mhosker** [comment]
Interesting, I must be doing something wrong!

This is the content of my cloudflare.py file which lives under the `processor` directory -
```
from .base import BaseProcessor, ProcessorException

class CloudflareException(ProcessorException):
    pass

class CloudflareProcessor(BaseProcessor):
    def __init__(self, name):
        # TODO: name is DEPRECATED, remove in 2.0
        self.id = self.name = name
    
    def process_target_zone(self, existing, target):
        for record in existing.records:
          record = record.copy()
          record._type = "CNAME"
          record.values = ["www.example.com.cdn.cloudflare.net."]
          self._owned.add(record)
          existing.add_record(record, replace=True)
        return existing
```
I am then calling it using the following in my prod.yaml file -
```
processors:
  cloudflare:
    class: octodns.processor.cloudflare.CloudflareProcessor
```

Sadly, no dice! The noop is showing no difference... oh and I am using the following on the zones config -
```
    processors:
      - cloudflare
```
Any ideas? I assume as I am not seeing an error that the linking of the processor itself is OK and its likely something I am missing in my for loop!

**Comment by ross** [comment]
> record._type = "CNAME"

It's not possible to change the record type like this. I should probably look at making that attribute real-only or something. You'll want to remove the existing record and add a newly created CNAME.

> self._owned.add(record)

Not sure what `._owned` is, it doesn't seem to be defined anywhere. If you're not getting an error from this line then your processor must not be getting called.

**Comment by mhosker** [comment]
Interesting... I note the following from my OctoDNS output - 

![image](https://github.com/octodns/octodns/assets/37193543/ad68fc95-2abb-4d8c-b7d2-220761984719)

It registers the provider seemingly, however it doesnt show it alongside the `sources` & `targets` - not sure if that is desired or should I be seeing the provider there?

**Comment by ross** [comment]
> It's not possible to change the record type like this. I should probably look at making that attribute real-only or something. You'll want to remove the existing record and add a newly created CNAME.

PR https://github.com/octodns/octodns/pull/1133

> It registers the processor seemingly, however it doesnt show it alongside the `sources` & `targets` - not sure if that is desired or should I be seeing the processor there?

Doesn't look like the lisst of processors is currently logged out there, will look into that, but I still suspect that it isn't running assuming that `_owned` bit is in there.

The yaml should look something like:

```yaml
providers:
  config: ...
  ns1: ...

processors:
  cloudflare:
    class: octodns.processor.cloudflare.CloudflareProcessor

zones:
  exxampled.com.:
    sources:
      - config
    processors:
      - cloudflare
    targets:
      - ns
```

**Comment by mhosker** [comment]
Indeed, I would concur that the processor is somehow not running... I have checked my prod.yaml config and it aligns with exactly what you have exampled.

Changed my `process_target_zone` def contents to -

```
for record in existing.records:                
    new = record.new(
        existing,
        record.name,
        {'type': 'CNAME', 'ttl': 60, 'value': "www.example.com.cdn.cloudflare.net."},
    )
    existing.add_record(new, replace=True)
```

With that hope that at least initially this will effectively convert *every* record to a CNAME pointing to `www.example.com.cdn.cloudflare.net.`. No dice sadly.

Is there any way from within the processor I can write to a debug log or output stuff in response to the octodns-sync command? Just so I can try and see something happening...

Mike :)

**Comment by ross** [comment]
Not sure what's going on. To start I'd just stick the following in your processors' `process_target_zone` so that it should 100% blow up if it's called:

```python
raise Exception('boom')
```

I just tested out your original code in my NS1 setup. In the checkout I created `tmp/__init__.py` that was empty and `tmp/cloudflare.py` that had the following in it:

```python
from octodns.processor.base import BaseProcessor, ProcessorException

class CloudflareException(ProcessorException):
    pass

class CloudflareProcessor(BaseProcessor):
    def __init__(self, name):
        # TODO: name is DEPRECATED, remove in 2.0
        self.id = self.name = name

    def process_target_zone(self, existing, target):
        for record in existing.records:
          record = record.copy()
          record._type = "CNAME"
          record.values = ["www.example.com.cdn.cloudflare.net."]
          self._owned.add(record)
          existing.add_record(record, replace=True)
        return existing
```

I think added the following to my ns1 dev.yaml:

```yaml
processors:
  cloudflare:
    class: tmp.cloudflare.CloudflareProcessor

...

zones:
  '*':
    sources:
      - config
    processors:
      - cloudflare
    targets:
      - ns1
```

And when run, I get the expected error message about `_owned`:

```console
(env) coho:octodns-ns1 ross$ PYTHONPATH=. octodns-sync --config-file=config/dev.yaml exxampled.com.
...
2024-01-16T13:58:18  [140704644451968] INFO  Ns1Provider[ns1] root NS record in existing, but not supported or not configured; ignoring it
Traceback (most recent call last):
  File "/Users/ross/octodns/octodns-ns1/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/ross/octodns/octodns/octodns/cmds/sync.py", line 62, in main
    manager.sync(
  File "/Users/ross/octodns/octodns/octodns/manager.py", line 730, in sync
    ps, d = future.result()
            ^^^^^^^^^^^^^^^
  File "/Users/ross/octodns/octodns/octodns/manager.py", line 62, in result
    return self.func(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ross/octodns/octodns/octodns/manager.py", line 487, in _populate_and_plan
    plan = target.plan(zone, processors=processors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ross/octodns/octodns/octodns/provider/base.py", line 244, in plan
    existing = processor.process_target_zone(existing, target=self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ross/octodns/octodns-ns1/tmp/cloudflare.py", line 16, in process_target_zone
    self._owned.add(record)
    ^^^^^^^^^^^
AttributeError: 'CloudflareProcessor' object has no attribute '_owned'
```

So everything seems to be working as i would expect it to. There must be something askew with the details of your setup/config.  You could try changing the class name of the processor to something you know doesn't exist to see if it blows up when trying to configure things.

**Comment by mhosker** [comment]
OK! Good news - Boom works!!!!

So... the processor seems to be linked correctly... but... I now suspect the for loop is at fault and potentially `existing.records` has nothing in it.

Which actually, would make sense... as my NS1 is currently empty awaiting the correct Cloudflare proxied data set...

So... could it be that the `process_target_zone` wont be suitable in my current case due to the fact my provider is currently blank?

Maybe I am better off using `process_source_and_target_zones` so I can still use `target` but use `desired` for the actual records.

**Comment by ross** [comment]
Ah. You may want to look at the other processor methods as it sounds like you're situation isn't exactly what i expected. 

Take a look at the other processor methods. It may be that the way things are laid out you want to modify the `desired` stated for non-CF providers in `process_source_and_target_zones`. Without sitting down to code it up hard to say.

**Comment by mhosker** [comment]
Sorry for the delay here.

Yes I am hopeful `process_source_and_target_zones` will do it. I'm getting a lot further anyway...!

One question - what would be the value of `record.name` if it were the zone apex?

In the code I need to check for the apex record so I can set it as an `ALIAS` rather than `CNAME`.

If I can get this processor working then it should actually be really very useful as I discovered that even my free Cloudflare accounts can resolve records using the `.cdn.cloudflare.net.` subdomain.

So although it may not be officially supported by Cloudflare it looks like it may technically work for all accounts...

**Comment by ross** [comment]
> One question - what would be the value of `record.name` if it were the zone apex?

`record.name = ''`

**Comment by mhosker** [comment]
A follow up to this... 

What is the correct way to delete a record when using `process_source_and_target_zones`.

At the moment I keep running into errors as I have things like the below in my zone -
```
record:
- octodns:
    cloudflare:
      proxied: true
  ttl: 300
  type: AAAA
  value: '100::'
- ttl: 300
  type: URLFWD
  value:
    code: 301
    masking: 2
    path: /
    query: 0
    target: https://example.com
```

And my code is converting the `AAAA` to a CNAME (pointing at Cloudflare), then complaining CNAME cant coexist with other records as it sees the `URLFWD`...

So my provider code which I thought should solve this -
```
# Check if root record (as CNAME cannot exist at root)
if record.name == "":
    # Use ALIAS instead as that can be used at the root (on some providers!)
    type = "ALIAS"
elif record._type not in ['A', 'AAAA', 'CNAME']:
    # If its not a CloudFlare proxyable record then we skip adding it back in
    # Remove the existing record completely
    desired.remove_record(record)
    # And skip to the next
    continue
else:
    # Else if it is proxyable then we use a CNAME back to CloudFlare
    type = "CNAME"

record = record.copy()
record._type = type
record._value = "www.example.com.cdn.cloudflare.net."

# Replace the record
desired.add_record(record, replace=True)
```
(Note this is still early days and I need to do a bit more handling of the root records ;))

In the above code I thought that through my use of `desired.remove_record(record)` for non `'A', 'AAAA', 'CNAME'` record types would have had OctoDNS remove the `URLFWD` and therefore only the `CNAME` would exist and no error...

Effectively at the moment I am just trying to get to a stage whereby ALL records of either `'A', 'AAAA', 'CNAME'` will be replaced by a static `CNAME` and any other records existing alongside will be ignored. Except for the root record which will become an ALIAS.

Any ideas?

**Comment by ross** [comment]
> What is the correct way to delete a record when using `process_source_and_target_zones`.

https://github.com/octodns/octodns/blob/ec6f1d1970e80c5273f628d17258a3b0f8415e01/octodns/zone.py#L190

> And my processor code is converting the `AAAA` to a CNAME (pointing at Cloudflare), then complaining CNAME cant coexist with other records as it sees the `URLFWD`...

That's a limitation of DNS, as I think i mentioned up above `CNAME`s cannot coexist with any other records. There really isn't a work-around for it. 

You can try calling `add_record` with both `lenient=True` and `replace=True` and see what happens. That should get octoDNS to allow the CNAME to coexist, but it's up to the provider (the company not the octodns implementation) as to whether the cname will be allowed. IIRC Cloudflare may be the only provider that allows it (by converting the `CNAME` to a proxy behind the scenes.

**Comment by mhosker** [comment]
Thanks for the quick reply!

OK, pleased to know at least my use of `.remove_record` is correct...

Regarding the CNAME coexist, indeed I am aware of the inability and I am trying to work around it in my code by deleting all other records with the same name where a CNAME exists.

A simpler example I am just testing is -
```
        for record in desired.records:
            
            if record._type not in ['A', 'AAAA', 'CNAME']:
                desired.remove_record(record)
```
The above code is deleting ALL records, not just the ones that are not `'A', 'AAAA', 'CNAME'` - is there something I am missing?

**Comment by mhosker** [comment]
Equally the following as far as I am aware should delete only the root records -

```
        for record in desired.records:
            if record.name == "":
                desired.remove_record(record)
        return desired
```

But is actually deleting everything...!

Confused!

**Comment by ross** [comment]
Try this and see what prints, I'd assume something else is going on as it seems unlikely that comparing name and/or type would be broken:

```python
for record in desired.records:
    if record.name == "":
        print(f'name={record.name}, _type={record._type}')
        desired.remove_record(record)
    return desired
```

I would expect that'll only happen once and things are either being removed elsewhere or aren't there in the first place as you're expecting.

You can always do:

```python
    from pprint import pprint
    pprint(desired.records)
```

To see what all is in `desired`

**Comment by mhosker** [comment]
Thanks for that, very useful in troubleshooting.

So it would appear that the correct records are being deleted however I am still getting the following error - 

`TypeError: cannot unpack non-iterable Zone object`

Which to me is suggesting no records exist? However... they do! So I am still a little bit confused...

**Comment by mhosker** [comment]
Its odd, its almost like `.remove_record` is being called after its worked out the changes... so it sees me add in a new CNAME but doesn't see the bit before when I deleted the existing record.

I have tried both deleting using EVERY record by setting the first line in the for loop as `desired.remove_record(record)` then readding the relevant ones back later and doing an `.add_record` using `replace=True`.

All of my text outputs seem to be correct in terms of what they are adding, e.g not seeing two CNAMEs with the same name even though Octo is complaining about it...

**Comment by mhosker** [comment]
After a little more troubleshooting...

I added `lenient=True` into `.add_record` which "solves" the problem of the coexisting CNAMEs error, although I don't like it as CNAMEs shouldn't be coexisting anyway according to my earlier calls to `.remove_record`... I will leave it for now as I just want to see some valid output!

The problem is... I am now consistently getting `TypeError: cannot unpack non-iterable Zone object` - I can now only assume this is due to the way `.remove_record` is handling the removing of records... potentially its not actually removing from the `desired` variable but rather setting it as blank so when I later `return desired` it actually has a load of blank "records" in it.

I guess my ultimate question is - is there something further I need to do after using `desired.remove_record(record)` but before `return desired` in order to reorder / remove the blank objects?

Apologies :)

**Comment by mhosker** [comment]
Update: I worked it out - I was only doing `return desired` not `return desired, existing` as I should have been... hence the odd errors! Well... I feel stupid and that was a time sink! Useful though for debugging! :)

**Comment by mhosker** [comment]
Looking to begin the route of a pull request for this processor and checking out the tests, is there any documentation regarding creating a test for a processor? Or any documentation on running the tests?

I think the test for this processor could be a little more complex as its provider specific, so I would need some way in the test to set a specific provider (Cloudflare) when creating a record then compare it to a non Cloudflare provider output... not sure I have seen that in any of the existing tests...

**Comment by mhosker** [comment]
Thanks for that info... very useful.

Indeed, it is VERY CF specific, so I agree octodns-cloudflare is a good place for it :)

One question... how can I check if not a "CloudflareProvider" in the `process_source_and_target_zones` function? So far I have tried...
```
if target == 'CloudflareProvider':
    return desired, existing
```
With no luck :(

From outputting the `target` variable it definitely contains `CloudflareProvider` however Python is not evaluating it as such... any ideas?

**Comment by ross** [comment]
```python
If is not instance(target, CloudflareProvider):
    # this is not a cf provider
```

**Comment by mhosker** [comment]
Awesome, that was a great pointer in the right direction.... :)

I ended up doing
```
# Check if zone is destined for Cloudflare
if isinstance(target, CloudflareProvider):
    # If it is then dont bother with any processing just return now
    return desired, existing
```
And had to add
```
from octodns_cloudflare import CloudflareProvider
```
As I haven't yet integrated into the CF provider code yet.

**Comment by mhosker** [comment]
To follow up on this - 

I have got the code fully integrated into the CF provider now and all is working as expected.

However, through testing I have run into one error - when using a `URLFWD` record alongside an `ALIAS` NS1 is not happy.

This is a problem as Cloudflare requires the `ALIAS` (at the root at least) to exist alongside the `URLFWD` in order for it to work!

I'm a little torn on how (if at all) I should "fix" this, there seems to be four main possible approaches -

A: This is out of scope of the Cloudflare processor as its a limitation of NS1. Therefore I do nothing processor wise and exclude either the `ALIAS` from NS1 OR include the `URLFWD` only on Cloudflare. That would mitigate the issue as NS1 wouldn't see one of the records, so cant complain about the record already existing.

B: I try and write some logic in the Cloudflare processor that would when adding a `URLFWD` record to a non Cloudflare provider check if an `ALIAS` proxied via Cloudflare coexists and if so skip the `URLFWD`. This would then mean all traffic would be sent to Cloudflare for the `URLFWD`, which may or may not be desired. Furthermore, this would only work for records where the `ALIAS` is proxied via Cloudflare.

C: An amendment to the NS1 provider with an option to specify a "URLFWD preference" of either `URLFWD` or `ALIAS`, then depending on which record type is set in the provider config the other would be discounted if both coexisted. e.g if `ALIAS` was specified then any records which also had a `URLFWD` would have the `URLFWD` removed. This would get around the immediate error, however could still cause problems as NS1 warn in their documentation - "Adding a URLFWD record to a zone that contains another resource record with the same name may result in unexpected behavior.". So if an `A` record coexisted with the `URLFWD` it would pass and apply but give potentially problematic results... 

D: A more extreme version of C - An option to specify "URLFWD override" of either `TRUE` or `FALSE`  which if `TRUE` would remove any other resource record of the same name where a `URLFWD` exists. So effectively if you have both a `URLFWD` and `A` record at `test.example.com` the `A` record will be ignored in favour of the `URLFWD`.

Interested to know your thoughts on this. At the moment I am doing option A and including the `URLFWD` only on Cloudflare so all redirects are going via that, which I am happy with.

**Comment by ross** [comment]
> when using a `URLFWD` record alongside an `ALIAS` NS1 is not happy.

Outside of provider specific considertions what would a `URLFWD` along side an `ALIAS` mean? At the root any dns query for that node should return the value of the thing the `ALIAS` points out. I don't see how they `URLFWD` would come into play. 

> This is a problem as Cloudflare requires the `ALIAS` (at the root at least) to exist alongside the `URLFWD` in order for it to work!

Not sure I understand the end goal. Is Cloudflare proxying a `URLFWD` done by someone else?

> Interested to know your thoughts on this. At the moment I am doing option A and including the `URLFWD` only on Cloudflare so all redirects are going via that, which I am happy with.

Stepping back the whole setup kind of gets away from the multi-provider redudancy goal of octoDNS in that other providers are doing the DNS but still pointing to Cloudflare services/names which will require both Cloudflare dns to be running &amp; healthy as well as all of Cloudflare's services. 

Feeling like this may be edge case-y and hairy enough that it might not belong in octodns-cloudflare and would be more of a 3rd party add on sort of thing, linked from the octodns/octodns-cloudflare repos. An added upside of that is that it would allow you to own and update it as needed and not rely on review for changes and the octodns-cloudflare releases to get things out. If it turns out that it is used by a decent number of people that could be revised.

**Comment by mhosker** [comment]
Thanks for your reply :)

> Outside of provider specific considertions what would a URLFWD along side an ALIAS mean? At the root any dns query for that node should return the value of the thing the ALIAS points out. I don't see how they URLFWD would come into play.

Well, its an interesting question. I would have thought `URLFWD` alone would have covered the redirect record completely, however in this case with Cloudflare that is not true... it requires some form of other record be that A, AAAA or CNAME (ALIAS at root) that is proxied in order for the redirect to them work.

This does spawn a further "solution" in my mind - maybe when a `URLFWD` is destined for Cloudflare then automatically add a proxied record alongside. For example `URLFWD` to `test.example.com` is declared in the zone `.yaml` and when an apply of the zone takes place OctoDNS automatically adds an `AAAA` record for `test.example.com` pointing to `100::` (the IPV6 discard prefix) set as Cloudflare proxied.

> Not sure I understand the end goal. Is Cloudflare proxying a URLFWD done by someone else?

The problem with Cloudflare is that a `URLFWD` on its own will do nothing, it *needs* a proxied record alongside in order to do anything.

> Stepping back the whole setup kind of gets away from the multi-provider redudancy goal of octoDNS in that other providers are doing the DNS but still pointing to Cloudflare services/names which will require both Cloudflare dns to be running & healthy as well as all of Cloudflare's services.

In my case, I want provider redundancy, however, Cloudflare is used as a CDN for certain records / websites which is an accepted risk for those use cases. The large majority of our zone however is not Cloudflare proxied, `MX` records for example. So we would want those record values to exist provider independently, as they do currently when using my Cloudflare processor.

> Feeling like this may be edge case-y and hairy enough that it might not belong in octodns-cloudflare and would be more of a 3rd party add on sort of thing, linked from the octodns/octodns-cloudflare repos. An added upside of that is that it would allow you to own and update it as needed and not rely on review for changes and the octodns-cloudflare releases to get things out. If it turns out that it is used by a decent number of people that could be revised.

I do feel the Cloudflare processor would be mega useful for all users of of the Cloudflare provider, as unless someone is using Cloudflare solely as a simple DNS provider without any proxied records then they are going to run into quirks when they add additional providers where records are proxied but then don't get proxied in the non Cloudflare providers (negating the security & CDN benefits proxying gives)!

I suspect at the moment anyone using OctoDNS with Cloudflare and proxied records with multiple providers (possibly more of an enterprise type setup so maybe not as many) will be either maintaining seperate zone files with one for Cloudflare and one for everything else (as I initially considered, nightmare!) OR (if its possible) creating two versions of proxied records and using the exclude / include option to set which provider each record should go to.

I am quite surprised to have not found someone discussing this setup previously, as I say it may be due to the more complex config / understanding needed. I suspect 99% of Cloudflare accounts are single provider setups and the rest are probably enterprise accounts with Cloudflare managing second provider replication for them (I know that is a feature they offer to their top tier accounts).

In my case anyway, the Cloudflare processor code is finished now (I think, just a couple of final bits of testing) and the solution is working perfectly, allowing me both provider redundancy for DNS + specific proxied records which always point back at Cloudflare.

The `URLFWD` record quirk with Cloudflare is just something I noticed when doing final testing. The more I think about it the less I think it should be integrated into the processor I have written, its more of a generic issue and would occur with the processor or not!

Happy to be lead by you regards if it should live in `octodns-cloudflare` - maybe a first step is a pull request with my code so you can see what I have done?

**Comment by ross** [comment]
> In my case, I want provider redundancy, however, Cloudflare is used as a CDN for certain records / websites which is an accepted risk for those use cases. The large majority of our zone however is not Cloudflare proxied, `MX` records for example. So we would want those record values to exist provider independently, as they do currently when using my Cloudflare processor.

Makes sense.



> I do feel the Cloudflare processor would be mega useful for all users of of the Cloudflare provider, as unless someone is using Cloudflare solely as a simple DNS provider without any proxied records then they are going to run into quirks when they add additional providers where records are proxied but then don't get proxied in the non Cloudflare providers (negating the security & CDN benefits proxying gives)!

> I suspect at the moment anyone using OctoDNS with Cloudflare and proxied records with multiple providers (possibly more of an enterprise type setup so maybe not as many) will be either maintaining seperate zone files with one for Cloudflare and one for everything else (as I initially considered, nightmare!) OR (if its possible) creating two versions of proxied records and using the exclude / include option to set which provider each record should go to.

My guess is that most people using Cloudflare do not end up doing any redundancy since they're pretty much reliant on Cloudflare's update for the proxying. If CF's dns has problems it's pretty likely that it would take out their proxying systems as collateral damage. 

> I am quite surprised to have not found someone discussing this setup previously,

I think ^^ is the reason why. 

I think a lot of people use octoDNS for migrations and/or cold standby setups. Active split authority isn't super common, maybe no one doing it w/Cloudflare. 

> In my case anyway, the Cloudflare processor code is finished now (I think, just a couple of final bits of testing) and the solution is working perfectly, allowing me both provider redundancy for DNS + specific proxied records which always point back at Cloudflare.

:cool:

> The `URLFWD` record quirk with Cloudflare is just something I noticed when doing final testing. The more I think about it the less I think it should be integrated into the processor I have written, its more of a generic issue and would occur with the processor or not!

👍 

> Happy to be lead by you regards if it should live in `octodns-cloudflare` - maybe a first step is a pull request with my code so you can see what I have done?

Sure.

**Comment by mhosker** [comment]
This has now been sorted as part of octodns/octodns-cloudflare#78 :tada:
