### ISSUE TITLE
Arguments passed to the provider

### ISSUE THREAD

**Issue by avachette** [octodns/octodns#1138]
Hi @ross,

I wanted to know if arguments passed to the provider and especially the one with environment variable can be checked at provider level, the following code portion of code seems related to my issue:
- https://github.com/octodns/octodns/blob/main/octodns/manager.py#L380

In long term I want to add Hashicorp vault support and in many case environment variable needs to be filled when secret are retrieved using hvac python implementation.

Here is my current implementation:
```
    def _build_kwargs(self, source):
        # Build up the arguments we need to pass to the provider
        kwargs = {}
        for k, v in source.items():
            kwargs[k] = v

        return kwargs
```

Everything else is done at provider level for PowerDNS as an example:
```
#
#
#

import logging
import os
import hvac
from operator import itemgetter

from requests import HTTPError, Session

from octodns import __VERSION__ as octodns_version
from octodns.provider import ProviderException
from octodns.provider.base import BaseProvider
from octodns.record import Record

from .record import PowerDnsLuaRecord

__VERSION__ = '0.0.5'


def _escape_unescaped_semicolons(value):
    pieces = value.split(';')
    if len(pieces) == 1:
        return value
    last = pieces.pop()
    joined = ';'.join([p if p and p[-1] == '\\' else f'{p}\\' for p in pieces])
    ret = f'{joined};{last}'
    return ret


class PowerDnsBaseProvider(BaseProvider):
    SUPPORTS_GEO = False
    SUPPORTS_DYNAMIC = False
    SUPPORTS_ROOT_NS = True
    SUPPORTS = set(
        (
            'A',
            'AAAA',
            'ALIAS',
            'CAA',
            'CNAME',
            'LOC',
            'MX',
            'NAPTR',
            'NS',
            'PTR',
            'SPF',
            'SSHFP',
            'SRV',
            'TLSA',
            'TXT',
            PowerDnsLuaRecord._type,
        )
    )
    TIMEOUT = 5

    POWERDNS_MODES_OF_OPERATION = {
        'native',
        'primary',
        'secondary',
        'master',
        'slave',
    }
    POWERDNS_LEGACY_MODES_OF_OPERATION = {'native', 'master', 'slave'}

    def __init__(
        self,
        id,
        host,
        api_key,
        port=8081,
        scheme="http",
        ssl_verify=True,
        timeout=TIMEOUT,
        soa_edit_api='default',
        mode_of_operation='master',
        vault_enabled=False,
        vault_address=None,
        vault_token=None,
        vault_mount_point=None,
        vault_path=None,
        vault_key=None,
        *args,
        **kwargs,
    ):
        super().__init__(id, *args, **kwargs)

        if getattr(self, '_get_nameserver_record', False):
            raise ProviderException(
                '_get_nameserver_record no longer '
                'supported; instead migrate to using a '
                'dynamic source for zones; see '
                'CHANGELOG.md'
            )

        self.host = host
        self.port = port
        self.scheme = scheme
        self.timeout = timeout

        self._powerdns_version = None

        def vault_credentials(vault_address, vault_token, vault_mount_point, vault_path, vault_key):
            vault_token = vault_token.split("/")
            vault_token = os.getenv(vault_token[1])
            vault_client = hvac.Client(
                url=vault_address,
                token=vault_token,
            )
            if not vault_client.is_authenticated():
                msg = (f'Vault: bad submitted token')
                raise RuntimeError(msg)
            else:
                read_response = vault_client.secrets.kv.read_secret_version(
                    mount_point=vault_mount_point, path=vault_path
                )
                vault_res=read_response['data']['data'][vault_key]

                return vault_res

        if vault_enabled:
            api_key = vault_credentials(vault_address, vault_token, vault_mount_point, vault_path, vault_key)
        else:
            api_key = os.getenv("POWERDNS_API_KEY")
```

I think it's not perfect as it is even if it's working, feel free to add any hints/pointers and I will write PRs to be reviewed.

Regards,

**Comment by ross** [comment]
I believe the best way to go about this is likely to use `vlt run` which will fetch the secrets from vault and place them into env variables for octodns to read. https://developer.hashicorp.com/hcp/docs/vault-secrets/commands/run

That will avoid having to bring vault logic/support into (all of the providers of) octodns.

**Comment by avachette** [comment]
I wanted to keep attack surface low:
- Short lived token
- Avoid passing security token all over the place (like CICD pipeline)

**Comment by ross** [comment]
How would the value token and other info needed to connect to vault get to the provider? Seems like that would have to come from the env which is at worse the same attack surface as `vlt run` and likely much smaller. 

I was playing around with a configurable secrets source setup over in https://github.com/octodns/octodns/pull/1140 which I'm not opposed to and would allow things like a vault source to be built w/o having to stuff detailed integration code into every provider. That said when I look at the info that the vault secret handler would need to connect to vault it seems like that'd be a larger potential attach surface than just having `vlt run` put the things you want/need into the env.

**Comment by avachette** [comment]
I think it could do the trick if the secrets source can support Vault AppRole, my first implementation was just an example using Vault token because it was simple to test on a dev environment.
When I was talking about attack surface it was more about CICD tools not OctoDNS itself.
I agree with you that vault integration on each providers seems to not be the best way to address the case but secrets are provider specific how do you see the implementation?

- Vault variable on OctoDNS
- Secret logic retrieved on OctoDNS and passed to each providers?

**Comment by ross** [comment]
I think I'm happy enough with how https://github.com/octodns/octodns/pull/1140 turned out that I'll move forward with it. 

That should allow you or anyone else to develop custom secret providers that source data however they want. If at some point in the future there are fully developed, well done, and generally useful secret handlers the option of including them as `octodns-<whatever>` modules can be explored.
