### ISSUE TITLE
Provider expectations for escaped characters

### ISSUE THREAD

**Issue by squintfox** [octodns/octodns#1145]
Sorry, this isn't an issue exactly but there's no discussion section here and I've tried for what seems like a lot of hours at this point to figure it out myself and cannot.  What is the expected input/output of a provider in regard to TXT escaped characters?  I know that octodns requires all semicolons to be escaped with a ```\```, but what about other backslashes and double quotes?

This talks about the RFC requirements, I think pretty well:
https://github.com/ajjahn/puppet-dns/issues/170

Basically every ```"``` should be stored and served as ```\"``` (unless we're talking about start/end of chunks) and every ```\``` should be stored and served as ```\\```.  So does octodns expect escaped or unescaped internally after being handed off from/to the provider?  I've been working on a provider and cannot figure out if I should be doing or not doing the escaping and what the others expect (or if it's been considered).

Also to consider, in what order the escaping applies.  Does ```\``` to ```\\``` come before or after ```;``` to ```\;```?  The answer to unescaped ```\;``` could be either ```\\\;``` or ```\\\\;```.

Or does octodns expect all records to be in their unescaped form (other than the semicolon) and the providers are expected to add/remove all the escaping and deal with their own APIs accordingly?

**Comment by ross** [comment]
From a config standpoint `;` needs to be escaped and nothing else should. 

If I had it to do over I wouldn't require `;` to be escaped in the config and would just have things do what was needed, but that :ship: sailed many years ago. 

> I've been working on a provider and cannot figure out if I should be doing or not doing the escaping and what the others expect (or if it's been considered).

`DnsimpleProvider` is probably the best/simplest real-world example. Take a look at how it deals with escaping and unescaping `;`
- https://github.com/octodns/octodns-dnsimple/blob/2bfc4d1ca25d21f315d0cb04695d82eb994a0c4c/octodns_dnsimple/__init__.py#L150-L151
- https://github.com/octodns/octodns-dnsimple/blob/2bfc4d1ca25d21f315d0cb04695d82eb994a0c4c/octodns_dnsimple/__init__.py#L364-L365

Beyond that it'll depend on the details of your provider what needs to happen escaping &amp; un-escaping wise. Some dns provider APIs want quoted strings others don't. I'd imagine anything is possible there. You can look around at other providers for more examples, but all of that is specific to the provider and nothing to do with octoDNS.

**Comment by squintfox** [comment]
@ross OK, understood from an octodns standpoint, but I guess I'd reframe the question to you as the steward of many of the providers.  I can adapt my provider to deal with it's API any way I want, but without knowing what the expectation is from the other side, how do I know what I'm sending or receiving?  Much like I need to know in advance that the other providers always escape the semicolon, I need to expect that on the inbound and make sure I'm doing the same on the outbound.  This is the same.

The DnsSimple example doesn't really get me there because I can't see what it's API is actually returning.  Do they escape or not?  If they do it all and then the provider passes it along, that's fine, but I don't have a live system I can test with.  I do have easy access to 2 of the providers (Ultra and Azure, YAML doesn't help in this regard), but it's a tiny sample set.  I just have no way to know if they are correctly representative of the whole ecosystem.

Also, I do think there's at least 1 case where octodns does inject an opinion in the matter:
https://github.com/octodns/octodns/blob/3acfd174b61ff5352294a0fbb5f9fb706d76bf14/octodns/record/chunked.py#L15

When chunking a record, it adds escapes to the double quotes.  That maybe leads me to an expectation that data should be passed around unescaped.  However, on the other end, that's not what the Ultra provider does.  Ultra adds all the escaping in the API and the provider keeps it.

**Comment by squintfox** [comment]
If it helps illustrate, these are various data points using Ultra.  In the end, when you land in YAML, you get back to what the UDNS GUI shows on the screen (albeit with the octodns semicolon escaping).  If you take this provider as the bellwether, then octodns providers expect completely unescaped records except for semicolons.

What I input into the Ultra GUI (seems bugged):
```abc"def""ghi\\\\xy;z\;```

What the GUI shows me after it saved:
```abc"def""ghi\\xy;z\;```

Dig results:
```
;QUESTION
testrecord4.example.com. IN TXT
;ANSWER
testrecord4.example.com. 60 IN TXT "abc"def""ghi\\xy;z\;"
```

Output from Ultra API:
```
{
	"ownerName": "testrecord4.example.com.",
	"rrtype": "TXT (16)",
	"ttl": 60,
	"rdata": [
		"abc\"def\"\"ghi\\\\xy;z\\;"
	]
}
```

Output of YAML provider using Ultra as a source:
```
testrecord4:
  ttl: 60
  type: TXT
  value: abc"def""ghi\\xy\;z\\;
```

**Comment by squintfox** [comment]
>"then octodns providers expect completely unescaped records except for semicolons."
> That is the case.

@ross I think that answers my question.  I can work with that and sort out the details.  Sorry about the circles and hoops, just having a sounding board for all of this really helped me get it straight.

> That's annoying. Weird that they're expecting things to be escaped on input and then showing them unescaped. Seems like that would completely break the ability to copy-n-paste a value from one record to another.

It does.  SMH.
