### ISSUE TITLE
Force a change on checksum mismatch

### ISSUE THREAD

**Issue by wjgauthier** [octodns/octodns#1153]
I just tested the new checksum functionally that was added in version 1.5, and it works great! However, it would be nice to be able to force a change with `--force`. Right now that option has no effect on a checksum mismatch.

**Comment by ross** [comment]
The thinking was that users would recompute the plan and get a new checksum as what changes would happen after the mis-match if things were applied would be unknown. 

It would be possible to grab the expected checksum, that didn't match, and pass that in to get things to move forwards. Again that would result in unknown changes, but it should go through provided nothing further changes between the mis-match and subsequent run.

**Comment by wjgauthier** [comment]
Ok, thank you. That makes sense. I will just use the checksum option to octodns-sync.
