### ISSUE TITLE
Features: Infomaniak Provider

### ISSUE THREAD

**Issue by Zerka30** [octodns/octodns#1168]
Hi :wave: 

Thanks for your hard work on `octodns`, I am very interested in using it for my own purposes. I am currently working on adding my DNS provider to octoDNS, namely [Infomaniak](https://infomaniak.com).

Work has begun, and you can follow the progress : `https://github.com/Zerka30/octodns-infomaniak`. The plugin is based, on the `octodns-digitalocean` and follow the same logic.

For the moment, the provider is able to handle type `A` and `AAAA` records, but many more are to come.

I'd like to ask you if there are any pre-requisites for contributing to `octodns` and how we could consider integrating Infomaniak as a provider in future official octoDNS releases?

**Comment by ross** [comment]
> Work has begun, and you can follow the progress : `https://github.com/Zerka30/octodns-infomaniak`. The plugin is based, on the `octodns-digitalocean` and follow the same logic.

:cool: Sounds like you're on the right track. 

I'd suggest following the steps at the top of https://github.com/octodns/octodns-template as the starting point. It'll get everything following the same patterns and scripts/tooling as all of the other modules. You should be able to do that and then drop your existing code on top of the file that is created. 

> I'd like to ask you if there are any pre-requisites for contributing to `octodns` and how we could consider integrating Infomaniak as a provider in future official octoDNS releases?

There's a couple levels. The first is just being listed in https://github.com/octodns/octodns?tab=readme-ov-file#providers. If you want to completely own and manage the provider and have full control over it that's the best route. 

The other option is that it lives under the octodns org, https://github.com/octodns/. The requires for that are first that you and/or others commit to keeping the provider up to date and working and keep on top of any issues filed. 

You would have commit permissions to the repo, but all work needs to use octodns-template as the starting point and follow the [GitHub Flow](https://docs.github.com/en/get-started/using-github/github-flow): work in a branch, push that to GitHub, create a PR, get a review before merging. Releases would be pushed/managed by the octoDNS core team.

**Comment by Zerka30** [comment]
I'll add the missing elements available via the `octodns-template, and continue to develop this provider to provide as many options as possible. 

Then we can see if the provider can be added under octodns org if that suits you. 

And I'll continue to support it as much as possible.
