### ISSUE TITLE
Question on split_extension

### ISSUE THREAD

**Issue by mrwillrobbins** [octodns/octodns#1188]
Hey Ross, 

When using split_extension and users that are on Windows.  Windows does not like having a "." in a folder name, is there any workarounds using split_extension and those that use VScode & Windows?

error: invalid path 'external/example.com./$example.com.yaml'

I tried creating folders manually in Windows and it's not possible.  My Macbook or Linux have no issues of course. 

Thank you in advance,
Will

**Comment by ross** [comment]
It's documented inline inside of `YamlProvider`, not the ideal place, but... https://github.com/octodns/octodns/blob/1562f0e80f34aa0d2b9baaa5a7d74d06dfba158b/octodns/provider/yaml.py#L42-L49

and there's a test that does a non `.` value https://github.com/octodns/octodns/blob/1562f0e80f34aa0d2b9baaa5a7d74d06dfba158b/tests/test_octodns_provider_yaml.py#L367 with the files in https://github.com/octodns/octodns/tree/1562f0e80f34aa0d2b9baaa5a7d74d06dfba158b/tests/config/split

Essentially `split_extension=.whatever` would have it use `<zone>.whatever`

**Comment by mrwillrobbins** [comment]
Much appreciated and thanks for the fast reply!  I saw that there, but wasn't following what other options could be used, but the test results made it clear.
Will

**Comment by mrwillrobbins** [comment]
closing
