### ISSUE TITLE
Add new provider

### ISSUE THREAD

**Issue by hatamiarash7** [octodns/octodns#1199]
Hi ✋ 

How can I add a new provider? I can't see any information in the Contributing guideline. As far as I know, you develop and maintain each provider as separate modules(repositories).

What should I do if I want to add a new provider?

**Comment by ross** [comment]
See https://github.com/octodns/octodns-template for the skeletal setup to get things started and https://github.com/octodns/octodns-powerdns/ is one of the cleanest/simplest example providers and https://github.com/octodns/octodns-dnsimple is pretty simple as well. You can start things out in your own repo and down the road once things hit a MVP/stable point the possibility of moving things into the octoDNS org can be explored/discussed.
