### ISSUE TITLE
Automatically creating  A records and their corresponding PTR record  

### ISSUE THREAD

**Issue by jr-RXcode** [octodns/octodns#121]
New to python and not sure how to implement automatically creating A and PTR records using octodns ? Any Advice or examples I can start with ?

**Comment by jr-RXcode** [comment]
Is it possible to get all of the A records from a zone file that was generated from an octodns dump and create anther zone file that contains a corresponding PTR record ? Basically have two file one with A record and another with PTR records.

**Comment by ross** [comment]
> Is it possible to get all of the A records from a zone file that was generated from an octodns dump and create anther zone file that contains a corresponding PTR record ?

There's nothing built-in currently that does this, but it should be possible to write a new provider to do it.

**Comment by jr-RXcode** [comment]
Do I need create a ticket with this request ?

**Comment by ross** [comment]
> Do I need create a ticket with this request ?

Yeah. It'd probably make sense to track that as a distinct request.

**Comment by ross** [comment]
See https://github.com/octodns/octodns/pull/974 for a potential solution to this
