### ISSUE TITLE
Document various configuration examples

### ISSUE THREAD

**Issue by o-be-one** [octodns/octodns#183]
I would be happy if i was able to read a complicated config file to see how powerful octodns is. I've read in docs/record.md about different patterns like multiple records (and i like this feature) but it could be better by giving a "complete" zone example, like with multiple TXT, multiple MX, etc.

I think also that the main README.md could be enhanced in this way. All informations are really powerful but we lake some zone configurations documentations.

Thank you for all you job by the way, i really like octodns!

**Comment by yzguy** [comment]
I think this makes sense. Maybe an `examples` directory with some example configs and zone files.

I can work on some initial ones. Might be a nice place to stage some stuff for people to use as initial data while creating new providers

Thoughts @ross ?

**Comment by ross** [comment]
> Thoughts @ross ?

Examples directly makes sense. `geo` is another thing that could some examples and a provider & zone config probably make sense as well.
