### ISSUE TITLE
Request for feature: route53 weighted routing, health checks

### ISSUE THREAD

**Issue by hankipanky** [octodns/octodns#252]
As far as I understand, the route53 provider employs health checks when implementing a geo-routing configuration.

I'd like to use other, simpler route53 routing policies, such as [weighted routing](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html#routing-policy-weighted) where records have health checks attached to themselves.

Is there common interest in such a feature?

**Comment by ross** [comment]
`geo` records have been retired and `dynamic` has replaced them. It's more powerful and flexible and may well cover the intended use case here. Closing this as stale. Take a look at `dynamic` to see if it does what you're looking for.
