### ISSUE TITLE
Feature Request: ZoneFileProvider

### ISSUE THREAD

**Issue by yzguy** [octodns/octodns#254]
Add a ZoneFileProvider, this will be very similar to AxfrSource, but have the ability to read a Bind Compatible zone file and be able to write one out.

dnspython package has methods to read/write zone files, it shouldn't be too difficult.

**Comment by yzguy** [comment]
Wondering if we will need to allow specifying the SOA/NS records, retry, expiry, etc. These will be necessary to create a zone file. 

Alternatively, the zone file may just be a source rather than a provider, and would be trivial to add as it’s a line change from AxfrSource.

**Comment by ross** [comment]
> Alternatively, the zone file may just be a source rather than a provider, and would be trivial to add as it’s a line change from AxfrSource.

Interesting question. I guess if people wanted to run bind off of it it might be nice to allow it to be full provider, but I'd be fine if it's just a source (to start.) If nothing else the SOA/root NS stuff could be specified as part of the provider config. 

There was a stab at managing root NS records a long time ago with https://github.com/github/octodns/pull/53, but it kind of stalled out.

**Comment by doddo** [comment]
I wrote a bind zone file provider and found that templating a bind zone file is much easier than parsing a zone file, because there are so many corner cases and such things.  But the octodns and bind server would have to share the file system (for validation),  so therefore I concluded that for octodns, in my opinion, reading the records from a zone transfer, and writing the data witn DNS Dynamic update would be best approach.  Maybe that's something to consider?

**Comment by barnumbirr** [comment]
Hello,

I've seen that the `Zonefile source` has been added in #276 but was wondering if anyone had started to work on a `Zonefile provider` as I'd be interested in managing Bind zones with octodns.

Cheers.

**Comment by kompetenzbolzen** [comment]
https://github.com/kompetenzbolzen/octodns-custom-provider/blob/master/octodns-custom-providers/provider/zonefile.py

I implemented this for me, would that be something that could be integrated here?

**Comment by yzguy** [comment]
@kompetenzbolzen yeah absolutely, I was actually playing around with your code the other night to see how feasible it would be to integrate, I was having decent success, but then some stuff came up and I haven't picked it back up.

https://github.com/yzguy/octodns/tree/zonefileprovider

**Comment by kompetenzbolzen** [comment]
@yzguy Oh cool! I fixed up some of my code this morning, hence the comment now. I added a config option for the SOA, that works for me. It's a bit of a hackjob and needs a newer version of dnspython though.

For the NS, wouldn't it be enough to just add one in eg the yaml source?

**Comment by ross** [comment]
Actually planning to do this as part of of a series of changes leading up to RFC 2136 support that would allow enabling writing files and full active management of domains served by compliant providers. (bind9 etc.)

/cc https://github.com/octodns/octodns/issues/927#issuecomment-1238834192

**Comment by polarathene** [comment]
Would still be cool to see!

Looks like it was addressed very recently too: https://github.com/octodns/octodns-bind/issues/40#issuecomment-1711765166

Available in [`octodns-bind` provider from `v0.0.05`](https://github.com/octodns/octodns-bind/pull/43) 🎉 

This issue can now be closed as resolved?
