### ISSUE TITLE
Query on wildcard sync for zones

### ISSUE THREAD

**Issue by wingZero21** [octodns/octodns#263]
Hi,

Do you know if its currently possible to sync zones based on a wildcard.

It would be great for syncing a large number of zones.

Cheers

EG:
*.co.uk
*.com

**Comment by yzguy** [comment]
Is this in reference in the configuration, eg.

```
*.co.uk.:
    sources:
        - provider1
    targets:
        - provider2
```

Or do you mean when running octodns-sync, eg `octodns-sync --config ./config *.com`

I think in the configuration it would be difficult and it makes it not very explicit about what zones are being managed. The providers would need to be reworked to get a list of zones first then do all the matching, etc.

Command-wise, I don't think it would be too bad, could definitely be useful

**Comment by wingZero21** [comment]
Hi,

Yeah, it would be really useful to have an option to sync based on the wildcard as if your managing a large number of domains this would save some time and effort.

If there is someway to achieve this it would be great!

Cheers

**Comment by ross** [comment]
> I think in the configuration it would be difficult and it makes it not very explicit about what zones are being managed

Yeah. I think I'd be opposed to wildcards in the config file. 👍 the explicit bit. It would be dangerous (octoDNS takes over things is manages) and I'd prefer/require that a human tells it exactly what to do. Might be nice to have something that can list out the zones and build a config file with all of them as an initial bootstrapping tool. That could support wildcards.

> Command-wise, I don't think it would be too bad, could definitely be useful

Agreed
