### ISSUE TITLE
Use libcloud for more providers

### ISSUE THREAD

**Issue by dol** [octodns/octodns#28]
I like the way octodns works. But instead of implementing the DNS providers yourself consider using the [libcloud library](https://libcloud.apache.org/). It's also written in Python and has already a steady number of supported [DNS providers](https://libcloud.readthedocs.io/en/latest/dns/supported_providers.html).

**Comment by ross** [comment]
Haven't looked too closely at libcloud. Something like that could be interesting, but the catch is that the majority of the code is around mapping between the common octoDNS record semantics and the details of how the provider wants/stores things. E.g. In octodns there's a single record object with one or more values, but in Dyn & Cloudflare each value is a separate (record) object. Route53 does have a single record object with multiple values, but as soon as geo location data comes into the mix that breaks up into a single record for each geo with multiple values. In Dyn those geo specific records use a completely different system of objects & api, ... Anyway that's just a tiny & incomplete example. 

Fwiw, the client libraries are generally a tiny fraction of the code involved in an octoDNS provider, most of it is mapping semantics. In fact there's a bunch of providers where I didn't even use their provided client libraries as they just got in the way/made it more difficult to do things. 

So, back to libcloud's. If its DNS support hides all of that variation/mess, it looks like it [might try to](https://libcloud.readthedocs.io/en/latest/dns/index.html), but how thoroughly isn't clear, then it would be awesome to take a look at using it and the place to start would be to create a LibcloudProvider. Part of the configuration to that provider cloud allow you to specify which driver to use and to pass any necessary config to that driver.

**Comment by ross** [comment]
There is now a template repo and process to ease this sort of work, https://github.com/octodns/octodns-template. https://github.com/octodns/octodns-powerdns is a good example for simple providers with good apis.
