### ISSUE TITLE
Thought: Update cloudflare provider to use cloudflares supported python library

### ISSUE THREAD

**Issue by Moumoutaru** [octodns/octodns#301]
Instead of interacting with the API as we currently do, would it be at all possible or useful to instead use Cloudflares python library. I noticed we are testing this provider with Cloudflares library, why not utilize it for the actual provisioning as well?

**Comment by ross** [comment]
It's been long enough that I don't remember the details, but I generally take a look at the API of a provider as well as the python client library before picking a route. For things with a clean and simple API I've found that the client libraries tend to make things more complicated more often than not and I remember starting down the path of using them a time or two and ran into problems/bugs that lead me to drop to hitting the API directly. Don't remember if that included CloudFlare or not. 

If there's a case to be made for (big) advantages to switching to the library and someone wants to take it on then I'd look a PR over.
