### ISSUE TITLE
Add support for IPv6 extensions to TinyDNS

### ISSUE THREAD

**Issue by adhawkins** [octodns/octodns#342]
There are some patches to TinyDNS that allow it to serve AAAA records.

The patch is hosted here: https://www.fefe.de/dns/

The record types in the file are '3' (AAAA only) and '6' (AAAA and associated PTR).

Some more documentation is available here:

https://docs.bytemark.co.uk/article/tinydns-format/

**Comment by ross** [comment]
I'd be happy to take a look at a PR. Won't likely be able to pick this up myself.

**Comment by adhawkins** [comment]
Addressed in MR #343.
