### ISSUE TITLE
Request for feature: GoDaddy support

### ISSUE THREAD

**Issue by nick-george** [octodns/octodns#365]
As the title suggests, I'd like to request support for GoDaddy to be added to what appears to be an awesome tool. 

Many thanks, 
Nick

**Comment by ross** [comment]
Hi @nick-george thanks for the suggestion. I won't likely have bandwidth to look into this, but others may. PRs are always welcome. If you or anyone else wants to look into adding GoDaddy support https://github.com/github/octodns/blob/c313ae38aefdfc62b688cefa4d066fb0c07f9d64/octodns/provider/dnsimple.py#L82 is pretty straightforward example to work off of.

**Comment by nick-george** [comment]
Thanks @ross. I'd love to have the time to work on this, but unfortunately I don't. Would you like me to close the ticket or leave it here open? 

Cheers,
Nick

**Comment by ross** [comment]
It can stay open in case someone wants to pick it up and so that anyone else who wonders about GoDaddy can find it.

**Comment by nick-george** [comment]
Thanks.

**Comment by ross** [comment]
There is now a template repo and process to ease this sort of work, https://github.com/octodns/octodns-template. https://github.com/octodns/octodns-powerdns is a good example for simple providers with good apis.
