### ISSUE TITLE
Unable to prevent certain types of records from being uploaded

### ISSUE THREAD

**Issue by adhawkins** [octodns/octodns#367]
Hi,

I'm using the following config file to read in a domain and subdomains, and sync them using the Mythic Beasts provider from here:

https://github.com/github/octodns/pull/360

---

providers:
  config_gentlyhosting.uk:
    class: octodns.source.tinydns.TinyDnsFileSource
    directory: /srv/gentlyhosting.uk/config/dns
    default_ttl: 3600

  config_test1.gentlyhosting.uk:
    class: octodns.source.tinydns.TinyDnsFileSource
    directory: /srv/test1.gentlyhosting.uk/config/dns
    default_ttl: 3600

  config_test2.gentlyhosting.uk:
    class: octodns.source.tinydns.TinyDnsFileSource
    directory: /srv/test2.gentlyhosting.uk/config/dns
    default_ttl: 3600

  mythicbeasts:
    class: octodns.provider.mythicbeasts.MythicBeastsProvider

    passwords:
      gentlyhosting.uk.: 'secretpasswordfordnsapigoeshere'

zones:
  gentlyhosting.uk.:
    sources:
      - config_gentlyhosting.uk
      - config_test1.gentlyhosting.uk
      - config_test2.gentlyhosting.uk

    targets:
      - mythicbeasts

What I want to do is prevent any NS records that are read from the TinyDNS zone files from being sent up to the Mythic Beasts API. I've tried a number of combinations of using 'exclude' in the config file, but none seem to do what I want.

Is this possible? Can someone tell me how to achieve this?

Thanks

Andy

**Comment by ross** [comment]
> Is this possible? Can someone tell me how to achieve this?

It's not a use-case that I've run across so there's no built in support for ignoring by type. That type of thing could potentially be added, though I'd have to sit down and think about the right way to configure it. I guess it would probably need to be a generic parameter to sources/providers or something like that.

A work-around/quick fix option would be to make a "thin" wrapper Source that inherits from TinyDnsProvider that doesn't include `NS` in its list of supports. I haven't directly tried that, but it should in theory work.

**Comment by adhawkins** [comment]
Thanks, might give that a try.

**Comment by ross** [comment]
This is now also possible with the use of processors, and the built-in [TypeRejectlistfilter](https://github.com/octodns/octodns/blob/1e0a190697609b502703c3442a2f09a2d11090ff/octodns/processor/filter.py#L28) should be able to ignore all NS records.

I believe there are options to solve the use case so closing. Feel free to reopen if not.

**Comment by adhawkins** [comment]
Are you able to provide pointers to documentation on how to achieve this? Just had a read through the main README and can't see any reference to 'processors' in there.

**Comment by adhawkins** [comment]
Perfect, will give it a try!
