### ISSUE TITLE
Cannot manage subzones that are more than one level under parent

### ISSUE THREAD

**Issue by nakato** [octodns/octodns#378]
When attempting to add NS records for a subzone that is more than one level under the parent zone OctoDNS refuses to add the record.

I would expect to be able to configure the zone in the parent zone add a zone between the parent and child.

domain.tld.yaml
```
---
zone.stg:
  ttl: 600
  type: NS
  values:
    - ns1.domain.tld
    - ns2.domain.tld
```

zone.stg.domain.tld.yaml
```
---
record:
  ttl: 60
  type: A
  values:
    - 1.2.3.4
```

`stg.domain.tld.yaml` does not exist, nor is `stg.domain.tld.` configured in OctoDNS config, nor does `stg.domain.tld.` exist in any DNS server.

Results in:
```
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns', 'console_scripts', 'octodns-sync')()
  File "/octodns/octodns/cmds/sync.py", line 39, in main
    dry_run=not args.doit, force=args.force)
  File "/octodns/octodns/manager.py", line 302, in sync
    plans = [p for f in futures for p in f.result()]
  File "/octodns/octodns/manager.py", line 56, in result
    return self.func(*self.args, **self.kwargs)
  File "/octodns/octodns/manager.py", line 224, in _populate_and_plan
    source.populate(zone)
  File "/octodns/octodns/provider/yaml.py", line 77, in populate
    self._populate_from_file(filename, zone, lenient)
  File "/octodns/octodns/provider/yaml.py", line 62, in _populate_from_file
    zone.add_record(record, lenient=lenient)
  File "/octodns/octodns/zone.py", line 68, in add_record
    .format(record.fqdn))
octodns.zone.SubzoneRecordException: Record zone.stg.domain.tld. is under a managed subzone
```

**Comment by ross** [comment]
The `NS` record in the top-level zone should be defined in the sub-zone since that zone owns that part of things. It'd have a record name of `''` there.

**Comment by nakato** [comment]
OctoDNS doesn't really support adding NS records to subzones, except in the case of PowerDNS, where it is defined in the provider configuration.  Issue #38 seems to contain the details on this, and a NS record on `''` would be silently dropped anyways in [zone.py](https://github.com/github/octodns/blob/master/octodns/zone.py#L27)

As I use PowerDNS, my Zone's get their self-referencing NS (`''`) records set via the provider plugin, however this doesn't create NS records in the parent zone pointing to the child zone.
So while `zone.stg.domain.tld` works by luck of `domain.tld` being delegated to my nameserver, `domain.tld` is not able to appropriately delegate the nameservers of `zone.stg.domain.tld`.

---

Additionally, this config also demonstrates the issue, with the same crash.

`domain.tld.yaml`
```
stg:
  ttl: 600
  type: A
  value: 1.2.3.4
```

`zone.stg.domain.tld.yaml`
```
---
record:
  ttl: 60
  type: A
  values:
    - 1.2.3.4
```

**Comment by ross** [comment]
> OctoDNS doesn't really support adding NS records to subzones, except in the case of PowerDNS, where it is defined in the provider configuration. Issue #38 seems to contain the details on this, and a NS record on `''` would be silently dropped anyways in [zone.py](https://github.com/github/octodns/blob/master/octodns/zone.py#L27)

Ah, yeah you're correct. I focused on the sub-zone part of things and wasn't thinking about the fact that they're NS records. octoDNS doesn't match the "root" NS records of a zone b/c provider support for that varies. Some will let you muck with them. Others treat them as ready only and reject changes and still others will accept the change you try to make and ignore them. I think that's documented somewhere. 

> Additionally, this config also demonstrates the issue, with the same crash.

So yeah `NS` won't work as `''` in the root, but with `A` it will if that is moved into `''` in the 2nd file.

**Comment by nakato** [comment]
The a record is for `stg.domain.tld` not `zone.stg.domain.tld`
So placing it as `''` in `zone.stg.domain.tld.yaml` would not make `stg.domain.tld` have an `A` record.

**Comment by ross** [comment]
Looking at this more closely and looking at the code it appears that having a "skip" zone like that isn't supported. If there's a sub-zone two-levels down the one in-between will need to be broken out too. In theory the code could be updated to know which zones are explicit and implicit, but that's not the case currently.

```
(env)otter:octodns ross$ tail config/*domain.tld.yaml
==> config/domain.tld.yaml <==
---

==> config/stg.domain.tld.yaml <==
---
'':
  ttl: 600
  type: A
  value: 1.2.3.4

==> config/zone.stg.domain.tld.yaml <==
---
record:
  ttl: 60
  type: A
  values:
    - 1.2.3.4
```

```
(env)otter:octodns ross$ PYTHONPATH=. ./octodns/cmds/sync.py --config-file=config/dev.yaml
...
********************************************************************************
* zone.stg.domain.tld.
********************************************************************************
* route53 (Route53Provider)
*   Create Zone<zone.stg.domain.tld.>
*   Create <ARecord A 60, record.zone.stg.domain.tld., ['1.2.3.4']> (config)
*   Create <TxtRecord TXT 60, octodns-meta.zone.stg.domain.tld., ['provider=route53']> ()
*   Summary: Creates=2, Updates=0, Deletes=0, Existing Records=0
********************************************************************************
* stg.domain.tld.
********************************************************************************
* route53 (Route53Provider)
*   Create Zone<stg.domain.tld.>
*   Create <ARecord A 600, stg.domain.tld., ['1.2.3.4']> (config)
*   Create <TxtRecord TXT 60, octodns-meta.stg.domain.tld., ['provider=route53']> ()
*   Summary: Creates=2, Updates=0, Deletes=0, Existing Records=0
********************************************************************************
* domain.tld.
********************************************************************************
* route53 (Route53Provider)
*   Create Zone<domain.tld.>
*   Create <TxtRecord TXT 60, octodns-meta.domain.tld., ['provider=route53']> ()
*   Summary: Creates=1, Updates=0, Deletes=0, Existing Records=0
********************************************************************************
```
