### ISSUE TITLE
Zone NS records

### ISSUE THREAD

**Issue by vanbroup** [octodns/octodns#38]
After dumping a zone from Cloudflare or Route53 (did not test any other providers) the YAML zone doesn't contain any zone NS records, where you would want to keep the main NS records in sync. I suppose these zone NS records are currently ignored and need to be configured manually at each provider but should this not be something that OctoDNS keeps in sync?

```
; <<>> DiG 9.10.3-P4-Ubuntu <<>> github.com NS
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44915
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;github.com.                    IN      NS

;; ANSWER SECTION:
github.com.             28      IN      NS      ns-1283.awsdns-32.org.
github.com.             28      IN      NS      ns-1707.awsdns-21.co.uk.
github.com.             28      IN      NS      ns-421.awsdns-52.com.
github.com.             28      IN      NS      ns-520.awsdns-01.net.
github.com.             28      IN      NS      ns1.p16.dynect.net.
github.com.             28      IN      NS      ns2.p16.dynect.net.
github.com.             28      IN      NS      ns3.p16.dynect.net.
github.com.             28      IN      NS      ns4.p16.dynect.net.

;; Query time: 4 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed May 24 10:26:42 UTC 2017
;; MSG SIZE  rcvd: 259
```

**Comment by ross** [comment]
> I suppose these zone NS records are currently ignored 

Correct they are ignored for all of the current providers with the exception of `PowerDnsProvider` which has the optional ability to manage them based with [provider config supplied values](https://github.com/github/octodns/blob/2ff34997a5df83ec8aba4edd7a6d4bd33e553a68/octodns/provider/powerdns.py#L351-L355).

> need to be configured manually at each provider but should this not be something that OctoDNS keeps in sync?

The reason behind the current state is they're a bit more complicated to reason about. As mentioned [in the blog post about octodns](https://githubengineering.com/enabling-split-authority-dns-with-octodns/) we use the above two providers actively, but push our data into further providers, both external and internal. 

The internal providers in our case are special, their NS records refer back to their pool. This allows us to resolve all of our "public" DNS internal to our network. More on this in an upcoming engineering blog post, but the important bit is that the zone NS records in them don't match what we push externally so a single set of values in the zone yaml file wouldn't let us set things up this way.

The external providers are generally serving as cold standbys and not part of the list of NS records we'd need to configure in our zone Yaml. We'd have to go around editing records one way or another in which case using octodns would be nice. However, providers create the zone NS records automatically when you create zones and in early experimenting I ran into problems when editing them in some cases. E.g. Dyn won't let you delete their NS records, but you can add others.

<img width="640" alt="screen shot 2017-05-24 at 7 04 16 am" src="https://cloud.githubusercontent.com/assets/12789/26407206/5248a718-404f-11e7-9b91-b48f66328f26.png">

That wasn't the only hiccup. It'd be possible to come up with ways to work within the constraints and manage around the problems for these external providers, but that coupled with our internal need for different zone NS records lead to the decision to leave them unmanaged, at least for now.

**Comment by ross** [comment]
Working on this in https://github.com/github/octodns/pull/53

**Comment by andrewkro** [comment]
Ross did I read that right, that hopefully we are getting a post outlining how we can manage internal nameservers (with internal plus external records) and split auth external nameservers (with only external records)? I was hoping to do this with Octodns!

**Comment by ross** [comment]
@andrewkro The follow up post about our internal DNS infrastructure was published about a week after that comment, https://githubengineering.com/dns-infrastructure-at-github/. 

It focuses more on the DNS infrastructure/architecture that the octoDNS details/config, but the rough sketch of how it works is there. We use the `PowerDNSProvider` to manage the internal authoritative servers.

**Comment by andrewkro** [comment]
Thanks @ross, I guess the question was more do you (or can you imagine) managing a zone, with internal (powerdns) authority for private addresses (which needs to include the external addresses as well) and external authority, say dyndns which would ONLY include the external addresses. 

im only just starting to look at octo so maybe its covered somewhere. i have see PRs for tagging which might be used. Im trying to keep my RFC1918 records out of dyndns.

**Comment by vanbroup** [comment]
@andrewkro #111 would allow you to do that

**Comment by ross** [comment]
> Thanks @ross, I guess the question was more do you (or can you imagine) managing a zone, with internal (powerdns) authority for private addresses (which needs to include the external addresses as well) and external authority, say dyndns which would ONLY include the external addresses.

> im only just starting to look at octo so maybe its covered somewhere. i have see PRs for tagging which might be used. Im trying to keep my RFC1918 records out of dyndns.

We intentionally have separate zones for internal and external records to avoid confusing situations where the answer you get depends on where you ask for it. E.g. if you query publically you don't see a record, but internally you do. 

If you're green field enough to follow that pattern I would recommend it. We use github.com for external and github.net for internal. There are a few "legacy" zones that are both public and private while we finish deprecating and removing them, but they are identical in both providers.

> @andrewkro #111 would allow you to do that

Yeah. From a complexity standpoint I'd personally avoid using that for this sort of use-case, but there definitely are situations where that'd be useful. @vanbroup I think that one is ready to merge once the last few branches are covered by tests :-) I'm hoping to spend some time on octoDNS today and try and catch up with issues & PRs.

**Comment by johnlane** [comment]
I am looking to maintain the NS record at the root of my domain that points to the name servers, the same ones that the domain registry points at (sorry if wrong terminology!).

I have DNS in two locations, route53 and Dyn (e.g. for mydomain.com). I've set the NS records on the domain for them ( 4 each for a total of 8). The mydomain.com zone on Dyn has 4 NS entries for mydomain.com, their 4. The mydomain.com zone on route53 has 4 entries, their 4. Those all set up by Dyn and AWS respectively, I did nothing.

Now I want to add the 4 route53 nameservers into the NS record on Dyn and add the 4 Dyn ones into the record on AWS. From what I can tell, OctoDNS can't do this and I will have to type them in manually on the Dyn and AWS portals.

Is that what this is about - and is it that OctoDNS cannot be used to maintain those records at the moment?

**Comment by ross** [comment]
> Is that what this is about - and is it that OctoDNS cannot be used to maintain those records at the moment?

Your understanding is correct. I've looked at supporting this a couple times now and wished it was cleaner/doable, but consistently run into problematic behavior with some providers not allowing you to fully manage the APEX NS records. E.g. one I've run into recently even manually: Dyn will not let you remove its NS records from a zone (this isn't something that'd be a problem for you, but it is something that would break octoDNS's way of operating.)

Unfortunately there just aren't good options here.

**Comment by danielgriggs** [comment]
Hi,

Just to confirm, is this still and open issue? I am trying to update NS records in a zone and OctoDNS seems to ignore any settings I put in.

**Comment by johnlane** [comment]
As far as I understand it, yes. You can't use OctoDNS to manage zone apex records as @ross explained above. I just accepted that and moved on as it's a very infrequent thing (for me) to manage. I use OctoDNS for everything else though (and very happy with it).

**Comment by ross** [comment]
> As far as I understand it, yes. You can't use OctoDNS to manage zone apex records as @ross explained above. I just accepted that and moved on as it's a very infrequent thing (for me) to manage. I use OctoDNS for everything else though (and very happy with it).

This is where we/I landed as well. We update apex NS records very infrequently and it was easier to just do it manually than to find and handle all the edge cases with providers on them, which appear to have changed over time as well.

I'm not opposed to having optional apex NS support in providers, but it will require extensive testing & vetting to make sure that it's safe & sane. Code-wise it's probably pretty easy, some sort of `SUPPORTS_APEX_NS = True` on the providers that support it and `False` on the base. It's really the sussing out of the details & edge cases that's prevented this from being done.

**Comment by danielgriggs** [comment]
Understood, thanks. I guess the APEX records don't change too often, so it's not too much of an issue.
