### ISSUE TITLE
Feature request for Aliyun(WanWang) as DNS provider

### ISSUE THREAD

**Issue by shixinyu** [octodns/octodns#386]
Aliyun(WanWang) as the biggest Domain Register Provider in China, please consider support them.

**Comment by ross** [comment]
Hi @shixinyu I'd welcome a PR that adds support for them, but it's unlikely that I'll have time to implement it myself. At this point the majority of the providers have been added by others and it's generally best for them to be built by someone who works with the provider and plans to use it going forward. https://github.com/github/octodns/blob/master/octodns/provider/dnsimple.py is one of the simpler providers and would likely serve as a good example.

**Comment by ross** [comment]
There is now a template repo and process to ease this sort of work, https://github.com/octodns/octodns-template. https://github.com/octodns/octodns-powerdns is a good example for simple providers with good apis.
