### ISSUE TITLE
Type Checking

### ISSUE THREAD

**Issue by brianeclow** [octodns/octodns#515]
Would it be possible to add a basic type checker? I have been attempting to make our DNS repo more self service, but the majority of the team does not understand the type restrictions.

At the least, adding a hostname vs URI check for CNAMEs. I have caught a number of those attempting to be merged into our zone records. In this particular case, using the complex hostname regex might cover all the bases?

**Comment by ross** [comment]
Definitely 👍 to more validations on record. They should be fairly easy to add to https://github.com/github/octodns/blob/master/octodns/record/__init__.py. Existing examples:

https://github.com/github/octodns/blob/7c9d89b82621005d6cf7d0ab87ff7b4cfc23ba7e/octodns/record/__init__.py#L814-L820

https://github.com/github/octodns/blob/7c9d89b82621005d6cf7d0ab87ff7b4cfc23ba7e/octodns/record/__init__.py#L717-L727

both around CNAMEs. PRs welcome :grin:

**Comment by brianeclow** [comment]
I have some "project time" coming up, hopefully. There are, now, two things I would like to contribute to this project. 😁 I will see if I can make it happen.

**Comment by ross** [comment]
> I am assuming only members of the organization can remove the `stale` label?

Dunno to be honest. Does it not let you do so?

**Comment by brianeclow** [comment]
I cannot edit the labels.

**Comment by ross** [comment]
@brianeclow can you give some examples of what you're trying not to allow? I just tested that urls, e.g. `https://google.com/`, and fqdns with paths, e.g. `google.com/some/path`, are rejected. 

Perhaps https://github.com/octodns/octodns/commit/cda56a3ca7ffed9b62a5f960682a9c25b9173c05 actually fixed this issue?

/cc https://github.com/octodns/octodns/pull/872 for the added tests.

**Comment by brianeclow** [comment]
I think that would cover the examples. Unless you want to add a combo: `http://google.com/random/path` as well?

**Comment by ross** [comment]
> I think that would cover the examples. Unless you want to add a combo: `http://google.com/random/path` as well?

Added in https://github.com/octodns/octodns/pull/873.
