### ISSUE TITLE
Geo for CNAME records

### ISSUE THREAD

**Issue by danhanks** [octodns/octodns#548]
Would you be willing to support Geo-enabled CNAMEs? I'm working on a provider for Ultra, and have a use case that requires Geo support for CNAME records.

**Comment by ross** [comment]
New `dynamic` style records do support CNAMEs, though it's definitely in alpha shape and not well tested (by me anyway as we don't use them) so ymmv.

**Comment by ross** [comment]
The newer `dynamic` records have support for `CNAME`s. `geo` is deprecated and will be removed in the future.
