### ISSUE TITLE
AzureDNS: Problem converting a CNAME record to an A record 

### ISSUE THREAD

**Issue by Arunothia** [octodns/octodns#586]
Similar to #507, facing trouble creating an A record in place of a CNAME record in AzureDNS.

Example Scenario: 

a:
  ttl: 3600
  type: CNAME
  value: sample.com.

change the above to - 

a:
  ttl: 3600
  type: A
  value: 1.1.1.1

This leads to the following error - 

* Create <ARecord A 3600, a.zone.com, ['1.1.1.1']> (config)
* Delete <CnameRecord CNAME 3600, a.zone.com, sample.com.>

msrestazure.azure_exceptions.CloudError: 409 Client Error: Conflict for url: <>

The error appears to be occurring because the create of A record is attempted before the delete of the CNAME record.

**Comment by ppieprzycki** [comment]
I would add that the same issue is with converting  NS record into CNAME. Probably even more cases exist for this issue.

**Comment by ross** [comment]
There is a stalled PR for this issue https://github.com/octodns/octodns/pull/587.  The Azure provider isn't currently well owned/maintained and it's not something I use/have access set up to so it'll probably have to fall to someone else to dig into this and address the problem in the near term.

**Comment by Arunothia** [comment]
> I would add that the same issue is with converting NS record into CNAME. Probably even more cases exist for this issue.
FYI: @ross 

I have updated the PR to force all deletes to happen first before other operations. 
Tested for the following scenarios -

1. Update CNAME to A
2. Update A to CNAME
3. Update NS to CNAME
4. Update CNAME to NS

**Comment by Arunothia** [comment]
PR for forcing delete operation to happen before other operations in AzureDNS has gone through.
