### ISSUE TITLE
Doing mass updates on single zone, deleting record first then re-adding instead of just updating?

### ISSUE THREAD

**Issue by banksiteservices** [octodns/octodns#615]
I have a single zone that I am managing with Constellix DNS provider.  I was trying to do a mass update of about 148 records in the zone file, just updating the IP address they point to and it took over 15 minutes to complete. Constellix told me that it appears that OctoDNS is actually deleting the record first and then re-adding it, causing a temporary outage per say.

Using OctoDNS it took a little over 12 minutes to make all the updates, I am needing to make updates in like under a minute for all these records. 

2020-10-02T18:33:02 [139982357153600] INFO ConstellixProvider[constellix] apply: making changes
2020-10-02T18:45:29 [139982357153600] INFO Manager sync: 147 total changes

Constellix support said to me:

I can confirm that bulk calls like the one you made are definitely supported on our end. They would allow you to update all of your records at once, so we do believe there may be something occurring on OctoDNS’s end. Octo DNS seems to be deleting and adding records for every single one of your records, and updates also may not be taking place, which could cause a short outage for a user as records are updated.

**Comment by banksiteservices** [comment]
yzguy, how hard would it be to add maybe an option to configure it to do updates in place? Constellix made it sound like the add/delete method is definitely not ideal, and doing the in-place would be faster. I'd like to continue to use OctoDNS but i may have to write my own thing cause it takes to long to run on 148 records, i need it in under 1 minute or less.

**Comment by ross** [comment]
Fwiw making 2 calls 1 probably isn't going to take 12m and turn it into 1m if that's your requirement. If there's some sort of batch API that might be able to do it, but that's also likely a larger change.

**Comment by yzguy** [comment]
@banksiteservices I'm not sure, It's been a while since I've worked with the provider. I'm not even sure what the API messages for those actions look like, there could be a lot of comparing with OctoDNS to decide how to do a change, or it may be declarative and you have to POST the value(s) of what you want the end result to be.

**Comment by banksiteservices** [comment]
Well if you can eventually add update in place that would be great. The problem that I face is that i have over 150 banks pointing to that zone file and those records using ALIAS. Constellix said with it deleting and adding new, it technically can cause a short outage for a few seconds if a customer happens to hit the DNS server in the middle of the record being changed out. So they said the add/remove is not ideal for my type of use case.
