### ISSUE TITLE
Correct handling of NULL SRV records in Cloudflare Provider (possibly elsewhere)

### ISSUE THREAD

**Issue by mtearle** [octodns/octodns#640]
Try into to sync the following entry from the YamlProvider to the Cloudflare provider

```
_pop3._tcp:
  octodns:
    cloudflare:
      proxied: false
  type: SRV
  value:
    port: 0
    priority: 0
    target: .
    weight: 0
```

Relevant part of trace here:

```
2020-12-05T23:01:56  [3074897664] DEBUG CloudflareProvider[cloudflare] _request: method=POST, path=/zones/f6c330b6c72b895026886d48e30ee7ec/dns_records
2020-12-05T23:01:56  [3074897664] DEBUG urllib3.connectionpool https://api.cloudflare.com:443 "POST /client/v4/zones/f6c330b6c72b895026886d48e30ee7ec/dns_records HTTP/1.1" 400 None
2020-12-05T23:01:56  [3074897664] DEBUG CloudflareProvider[cloudflare] _request:   status=400
2020-12-05T23:01:56  [3074897664] DEBUG CloudflareProvider[cloudflare] _request:   data={'data': {'service': '_pop3', 'proto': '_tcp', 'name': 'ucc.gu.uwa.edu.au.', 'priority': 0, 'weight': 0, 'port': 0, 'target': ''}, 'name': '_pop3._tcp.ucc.gu.uwa.edu.au', 'type': 'SRV', 'ttl': 3600}
Traceback (most recent call last):
  File "/home/wheel/mtearle/hack/mooneye/octodns/env/bin/octodns-sync", line 11, in <module>
    load_entry_point('octodns==0.9.11', 'console_scripts', 'octodns-sync')()
  File "/home/wheel/mtearle/hack/mooneye/octodns/env/lib/python3.9/site-packages/octodns-0.9.11-py3.9.egg/octodns/cmds/sync.py", line 38, in main
  File "/home/wheel/mtearle/hack/mooneye/octodns/env/lib/python3.9/site-packages/octodns-0.9.11-py3.9.egg/octodns/manager.py", line 418, in sync
  File "/home/wheel/mtearle/hack/mooneye/octodns/env/lib/python3.9/site-packages/octodns-0.9.11-py3.9.egg/octodns/provider/base.py", line 95, in apply
  File "/home/wheel/mtearle/hack/mooneye/octodns/env/lib/python3.9/site-packages/octodns-0.9.11-py3.9.egg/octodns/provider/cloudflare.py", line 675, in _apply
  File "/home/wheel/mtearle/hack/mooneye/octodns/env/lib/python3.9/site-packages/octodns-0.9.11-py3.9.egg/octodns/provider/cloudflare.py", line 527, in _apply_Create
  File "/home/wheel/mtearle/hack/mooneye/octodns/env/lib/python3.9/site-packages/octodns-0.9.11-py3.9.egg/octodns/provider/cloudflare.py", line 118, in _try_request
  File "/home/wheel/mtearle/hack/mooneye/octodns/env/lib/python3.9/site-packages/octodns-0.9.11-py3.9.egg/octodns/provider/cloudflare.py", line 137, in _request
octodns.provider.cloudflare.CloudflareError: DNS Validation Error
"octodns-sync --config=$OCTODIR/config/ucc-to-cloudflare.yaml $EXTRA_ARGS --doit" command failed with exit code 1.
```

On previous runs, it had failed with the error:   Invalid SRV target. Target must be a hostname

**Comment by mtearle** [comment]
Some relevant dicussion here at https://community.cloudflare.com/t/i-need-help-cloudflare-team-development-team/162279/2

RFC 2782 https://tools.ietf.org/html/rfc2782 and RFC 6186 https://tools.ietf.org/html/rfc6186 are the references

https://github.com/github/octodns/blob/b1b992c628f3e69ea8bbfe444bae95cd33ca154b/octodns/provider/cloudflare.py#L416 appears to be a possible suspect.  Will investigate further

**Comment by ross** [comment]
>  'target': value.target[:-1],

That's likely intended to remove the trailing `.`. 

octoDNS yaml requires it on the value, but I assume Cloudflare doesn't want it in the value provided to the API.

> octodns.provider.cloudflare.CloudflareError: DNS Validation Error

Based on the stack trace this error isn't coming from octoDNS and it's likely that either the Cloudflare API doesn't allow empty values (or maybe the client library doesn't.) 

Looking at the link you provdied to the CF forum it sounds like it's saying Cloudflare doesn't support empty SRV values as well.

If that's the case there's nothing much that octoDNS can do.

**Comment by mtearle** [comment]
I've been slowly narrowing it down (working my way the octoDNS unit tests)

One of the zones that I've got API access to on Cloudflare does have a NULL record; as it was not set up by myself, this may have been a zone file import so Cloudflare can definitely serve it.   I'm hoping that post is old and the API has improved.

```
mtearle@complication$ dig ucc.asn.au ns

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> ucc.asn.au ns
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22509
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 10

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ucc.asn.au.			IN	NS

;; ANSWER SECTION:
ucc.asn.au.		86400	IN	NS	leland.ns.cloudflare.com.
ucc.asn.au.		86400	IN	NS	fay.ns.cloudflare.com.

;; ADDITIONAL SECTION:
fay.ns.cloudflare.com.	37	IN	A	108.162.192.115
fay.ns.cloudflare.com.	37	IN	A	173.245.58.115
fay.ns.cloudflare.com.	37	IN	A	172.64.32.115
fay.ns.cloudflare.com.	594	IN	AAAA	2803:f800:50::6ca2:c073
fay.ns.cloudflare.com.	594	IN	AAAA	2606:4700:50::adf5:3a73
fay.ns.cloudflare.com.	594	IN	AAAA	2a06:98c1:50::ac40:2073
leland.ns.cloudflare.com. 325	IN	A	108.162.195.8
leland.ns.cloudflare.com. 325	IN	A	162.159.44.8
leland.ns.cloudflare.com. 325	IN	A	172.64.35.8

;; Query time: 51 msec
;; SERVER: 192.168.43.1#53(192.168.43.1)
;; WHEN: Tue Dec 08 19:40:27 AWST 2020
;; MSG SIZE  rcvd: 275

mtearle@complication$ dig @fay.ns.cloudflare.com _imap._tcp.ucc.asn.au srv

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> @fay.ns.cloudflare.com _imap._tcp.ucc.asn.au srv
; (6 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25160
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;_imap._tcp.ucc.asn.au.		IN	SRV

;; ANSWER SECTION:
_imap._tcp.ucc.asn.au.	3600	IN	SRV	0 0 0 .

;; Query time: 45 msec
;; SERVER: 172.64.32.115#53(172.64.32.115)
;; WHEN: Tue Dec 08 19:51:00 AWST 2020
;; MSG SIZE  rcvd: 69

```

Syncing from Cloudflare to YAML for that zone gave me:

```
_imap._tcp:
  ttl: 1
  type: SRV
  value:
    port: 0
    priority: 0
    target: ..
    weight: 0
```

I've manually pull that record out with the API, and it's returning a single period

It appears the stray period is coming from here:

https://github.com/github/octodns/blob/b1b992c628f3e69ea8bbfe444bae95cd33ca154b/octodns/provider/cloudflare.py#L246

It appears the dnsimple and digitalocean providers have a similar line of code.   DNSimple has a sandbox so I'll do some additional testing against that.

I'm hoping to get some code happening tonight and see if I can confirm either way.

**Comment by mtearle** [comment]
```
diff --git a/octodns/provider/cloudflare.py b/octodns/provider/cloudflare.py
index db937e5..ac200d8 100644
--- a/octodns/provider/cloudflare.py
+++ b/octodns/provider/cloudflare.py
@@ -243,7 +243,7 @@ class CloudflareProvider(BaseProvider):
                 'priority': r['data']['priority'],
                 'weight': r['data']['weight'],
                 'port': r['data']['port'],
-                'target': '{}.'.format(r['data']['target']),
+                'target': ('{}.'.format(r['data']['target']) if r['data']['target'] != "." else "."),
             })
         return {
             'type': _type,
@@ -413,7 +413,7 @@ class CloudflareProvider(BaseProvider):
                     'priority': value.priority,
                     'weight': value.weight,
                     'port': value.port,
-                    'target': value.target[:-1],
+                    'target': (value.target[:-1] if value.target != "." else "."),
                 }
             }
````

I've tested the above from YAML to Cloudflare, and Cloudflare to YAML.   I'll work on getting the pull request together.

**Comment by mtearle** [comment]
Currently working on the branch over here, https://github.com/ucc/octodns/tree/srv_null_records , working my way through the other providers to check their support.

Did some testing against the DNSimple API.  Not working correctly, have reached out via their web form.

**Comment by mtearle** [comment]
Tested YAML to DigitalOcean, and DigitalOcean to YAML successfully

**Comment by mtearle** [comment]
Response received from DNSimple, test case sent, and internal ticket created @ DNSimple

**Comment by mtearle** [comment]
Tested YAML to PowerDNS API, and PowerDNS API to YAML successfully

**Comment by mtearle** [comment]
Tested against DNSMadeEasy sandbox; appears to be explicitly not supported

```
octodns.provider.dnsmadeeasy.DnsMadeEasyClientBadRequest: 
  - Record value may not be a standalone dot.
  - Port must be between 1 and 65535.  Invalid value:  0
```

**Comment by mtearle** [comment]
Of the remaining providers that support SRV records in octodns; I've not able to test:

* Constellix
* Easy DNS
* Edge DNS
* Gandi

Primary reason is there is no API sandbox available / test account / behaviour is not documented

This leaves "mythic beasts"    I reached out to a friend whose familiar with their API and customer; his testing generated errors on their API.   Waiting to hear more back from him  / "mythic beasts"

**Comment by mtearle** [comment]
@ross What would be the correct approach here for these remaining providers?  Flag a "Warning" when one of these records is encountered and then try anyhow, or do-nothing?

**Comment by yzguy** [comment]
I can take a look at Constellix and Gandi.

**Comment by yzguy** [comment]
YAML to Gandi, and Gandi to YAML seems to work. I used below to push to Gandi, and when dumping from Gandi I got the same thing. I believe this is the tests you were doing?

```yaml
_pop3._tcp:
  type: SRV
  value:
    port: 0
    priority: 0
    target: .
    weight: 0
```

**Comment by mtearle** [comment]
Thanks @yzguy - that would very much be appreciated.

The place to start is the example record from RFC6186.

_pop3._tcp     SRV  0 0 0   .

Corresponding YAML is:

_pop3._tcp:
  type: SRV
  value:
    port: 0
    priority: 0
    target: .
    weight: 0

For Digital Ocean, I did a quick test through the Web UI to see what happened and then poked their API by hand.
I think you should be able to do your tests with a vanilla copy of octodns (based on what tweaks/code changes I had to do in my development environment)

**Comment by mtearle** [comment]
Thanks Adam ( @yzguy )

Yes, I was doing round trip tests.   Thanks for testing this for me.

**Comment by ross** [comment]
> @ross What would be the correct approach here for these remaining providers? Flag a "Warning" when one of these records is encountered and then try anyhow, or do-nothing?

If the config is spec-compliant and some providers support it then it likely makes sense for octoDNS to allow it (assuming there's valid use cases for it.) The providers that can support it should and those that can't will probably have to warn when they encounter it. 

If only a couple providers support it and there's no clear/real use case then we might as well have octoDNS record validate reject the setup.

**Comment by mtearle** [comment]
@actazen Are you able to test Easy DNS?

@jdgri Are you able to test Edge DNS?

**Comment by actazen** [comment]
Hi guys, sorry for not responding sooner.  EasyDNS does support this and the API correctly handles a record such as:

_pop3._tcp:
  type: SRV
  value:
    port: 0
    priority: 0
    target: .
    weight: 0

**Comment by mtearle** [comment]
Thanks @actazen for testing this

**Comment by mtearle** [comment]
Thanks to @pwaring for his assistance with mythic beasts tests.  API is now working.

**Comment by mtearle** [comment]
Thanks to Jim (@jdgri ) for his assistance testing Edge DNS.  Working there in both directions.
