### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'octodns' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by ConscriptMR** [octodns/octodns#643]
Traceback (most recent call last):
File "/usr/local/bin/octodns-sync", line 6, in
from pkg_resources import load_entry_point
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 3251, in
@_call_aside
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 3235, in _call_aside
f(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 3264, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 583, in _build_master
ws.require(requires)
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 900, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/local/lib/python2.7/dist-packages/pkg_resources/init.py", line 786, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'octodns' distribution was not found and is required by the application

octodns install using: pip install -r requirements.txt
requirements contains: -e git+https://git@github.com/github/octodns.git@07b8c19acc337efc90391f5024a346ce0956a5be#egg=octodns
command ran was: octodns-sync --config-file=/etc/bind/octodns-config.yaml

**Comment by ross** [comment]
Can't seem to reproduce that with python3 and the latest pip

```
(env) salmon:foo ross$ cat requirements.txt
-e git+https://git@github.com/github/octodns.git@07b8c19acc337efc90391f5024a346ce0956a5be#egg=octodns
(env) salmon:foo ross$ python --version
Python 3.9.0
(env) salmon:foo ross$ pip --version
pip 20.3.1 from /private/tmp/foo/env/lib/python3.9/site-packages/pip (python 3.9)
(env) salmon:foo ross$ pip install -r requirements.txt
Obtaining octodns from git+https://****@github.com/github/octodns.git@07b8c19acc337efc90391f5024a346ce0956a5be#egg=octodns (from -r requirements.txt (line 1))
  Cloning https://****@github.com/github/octodns.git (to revision 07b8c19acc337efc90391f5024a346ce0956a5be) to ./env/src/octodns
Collecting dnspython>=1.15.0
  Using cached dnspython-2.0.0-py3-none-any.whl (208 kB)
...
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Installing collected packages: pyparsing, toml, py, pluggy, packaging, iniconfig, attrs, pytest, coverage, urllib3, six, repoze.lru, pytest-mock, pytest-cov, pycountry, pprintpp, idna, chardet, certifi, requests, PyYaml, python-dateutil, pycountry-convert, natsort, dnspython, octodns
  Running setup.py develop for octodns
Successfully installed PyYaml-5.3.1 attrs-20.3.0 certifi-2020.12.5 chardet-3.0.4 coverage-5.3 dnspython-2.0.0 idna-2.10 iniconfig-1.1.1 natsort-7.1.0 octodns packaging-20.7 pluggy-0.13.1 pprintpp-0.4.0 py-1.9.0 pycountry-20.7.3 pycountry-convert-0.7.2 pyparsing-2.4.7 pytest-6.1.2 pytest-cov-2.10.1 pytest-mock-3.3.1 python-dateutil-2.8.1 repoze.lru-0.7 requests-2.25.0 six-1.15.0 toml-0.10.2 urllib3-1.26.2
(env) salmon:foo ross$ octodns-sync
usage: octodns-sync [-h] --config-file CONFIG_FILE [--doit] [--force] [--source SOURCE] [--target TARGET] [--version] [--log-stream-stdout] [--log-syslog] [--syslog-device SYSLOG_DEVICE] [--syslog-facility SYSLOG_FACILITY] [--debug]
                    [zone ...]
octodns-sync: error: the following arguments are required: --config-file
```

What versions are you using?

You might also try modifying the `-e` line to use `github.com/octodns/octodns.git` now that octoDNS has moved to it's own org to see if that's related.

**Comment by ConscriptMR** [comment]
I'm using python 2 with pip version 8.1.1

**Comment by ross** [comment]
> I'm using python 2 with pip version 8.1.1

OK. I can reproduce this with python 2 and pip 8.1.1. 

That's a really old version of pip, it's at 20.2.2 now and there are all sorts of issues like this with older pips so I'm not surprised. I tried the most recent version and that solved the above problem. There may be others that are unrelated that I'm now looking into around non-printable chars that python2 is having a problem with. 

Going to call this close though as the issue is with a really old pip and not octoDNS.

**Comment by ConscriptMR** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2928, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'octodns' distribution was not found and is required by the application
Build step 'Execute shell' marked build as failure

it's still not working for me with latest pip and python3.8 on ubuntu16.04

**Comment by ConscriptMR** [comment]
nvm, it works for me but it doesn't work from the jenkins job for some reason..
