### ISSUE TITLE
Issue with the Route53 provider handling of CNAME records without trailing dot.

### ISSUE THREAD

**Issue by nikolay-te** [octodns/octodns#647]
So, we have some records in Route53 which are missing the trailing dot when fetching them via the API, however these DNS queries work as expected because R53 assumes them to be FQDN:
From https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-values-basic.html
```
CNAME — Canonical name
The fully qualified domain name (for example, www.example.com) that you want Route 53 to return in response to DNS queries for this record. A trailing dot is optional; Route 53 assumes that the domain name is fully qualified. This means that Route 53 treats www.example.com (without a trailing dot) and www.example.com. (with a trailing dot) as identical.
```

But `octodns` is failing when pulling zones with such records:
```
octodns-dump --config-file ../dns-automation/config/staging.yaml --output-dir ./ XXX.com. route53                                                                                
2020-12-11T19:07:55  [4652064192] INFO  Manager __init__: config_file=../dns-automation/config/staging.yaml
2020-12-11T19:07:55  [4652064192] INFO  Manager __init__:   max_workers=2
2020-12-11T19:07:55  [4652064192] INFO  Manager __init__:   include_meta=False
2020-12-11T19:07:56  [4652064192] INFO  Manager dump: zone=XXX.com., sources=()
Traceback (most recent call last):
  File "/Users/ndenev/te/octodns/venv/bin/octodns-dump", line 33, in <module>
    sys.exit(load_entry_point('octodns', 'console_scripts', 'octodns-dump')())
  File "/Users/ndenev/te/octodns/octodns/cmds/dump.py", line 34, in main
    manager.dump(args.zone, args.output_dir, args.lenient, args.split,
  File "/Users/ndenev/te/octodns/octodns/manager.py", line 469, in dump
    source.populate(zone, lenient=lenient)
  File "/Users/ndenev/te/octodns/octodns/provider/route53.py", line 993, in populate
    record = Record.new(zone, name, data, source=self,
  File "/Users/ndenev/te/octodns/octodns/record/__init__.py", line 120, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record YYY._domainkey.XXX.com.
  - CNAME value "abcdef.dkim.YYY.io" missing trailing .
```

**Comment by nikolay-te** [comment]
Potential fix in https://github.com/octodns/octodns/pull/648

**Comment by ross** [comment]
> octodns-dump --config-file ../dns-automation/config/staging.yaml --output-dir ./ XXX.com. route53

See https://github.com/octodns/octodns/blob/master/docs/records.md#lenience for discussion of options around lenience. 

There's a param `--lenient` which you can add to ^ that will turn the validation errors into warnings during the dump which should allow you to dump the data into yaml. You can then update the record values to be spec compliant or if you really don't want to do that configure octoDNS to be lenient going forward. The reason to update them to be compliant is so that all DNS providers will accept them as some do require the trailing `.` and others will add it for you causing false diffs when you plan changes.

**Comment by ross** [comment]
Closing. Feel free to reopen if I've misunderstood.
