### ISSUE TITLE
Feature request: Support for deSEC API

### ISSUE THREAD

**Issue by peterthomassen** [octodns/octodns#651]
It would be great if octoDNS supported [deSEC](https://desec.io/) as a provider. It has an API, supports a very large number of record types (virtually no restrictions on what PowerDNS supports), and has automatic DNSSEC management.

The API docs are here: https://desec.readthedocs.io/

(Disclaimer: I am the founder of deSEC. We started the project in the spirit of Let's Encrypt, to provide domain owners with a free and easy way to equip their domains with DNSSEC.)

**Comment by ross** [comment]
Hi @peterthomassen, deSEC looks pretty cool and it should be fairly easy to create an octoDNS provider for it based on a quick skim of the API. I'm partway through some reorganizing of octoDNS, (cc https://github.com/octodns/octodns/issues/622) and plan to start building out the template/infrastructure for having seperate modules for each provider. I might try looking at a deSEC provider as part of that, but it'll be probably be a month or so before I'd get there. If someone else beats me to it and wants to look at doing a PR for the provider on the existing mono-repo we can figure out whether to merge that or just "port" it into a standalone module repo.

**Comment by ross** [comment]
There is now a template repo and process to ease this sort of work, https://github.com/octodns/octodns-template. https://github.com/octodns/octodns-powerdns is a good example for simple providers with good apis.

**Comment by peterthomassen** [comment]
@ross Are you still planning to check on deSEC as a provider, or do you need help with that?

**Comment by peterthomassen** [comment]
https://github.com/TilCreator/octodns-desec/ has an implementation.

**Comment by ross** [comment]
Feel free to file a PR adding a link to the README if that makes sense to you.
