### ISSUE TITLE
Plan should order changes consistently, e.g. Deletes before Adds etc. 

### ISSUE THREAD

**Issue by ross** [octodns/octodns#656]
Some providers have to manually ensure that deletes come first to avoid problems like their providers throwing errors about duplicate A/CNAME when making a type change.

We should look into a default behavior of consistently ordering `Plan` `changes` to make it easier on providers/more likely that they do the right thing out of the gate. If not by default we should add helpers to the `Plan` object to allow them to request the ordered version: e.g. `plan.ordered_changes`. 

/cc https://github.com/octodns/octodns/pull/587#pullrequestreview-560726591

**Comment by mtearle** [comment]
@ross This was the approach I took on the Cloudflare provider when I hit this issue when putting together my other pull request.  https://github.com/octodns/octodns/pull/635/commits/0266b3e452f6bfe7669cc44ecc3c18b9f64d7e25

**Comment by deric** [comment]
@mtearle That's great (works fine, at least in my case), but it doesn't change the plan. It would be better if the plan would be the same as the ordering of the actual changes.
