### ISSUE TITLE
zonefile source fails under windows since files can't end in dot

### ISSUE THREAD

**Issue by ttk** [octodns/octodns#657]
Due to a limitation in windows, filenames can't end in a dot.  The default behaviour of the `ZoneFileSource` loader is to include the dot at the end of the zone filename as per the comment:

`# Filenames should match zone name (eg. example.com.)`

My solution was to subclass the ZoneFileSource class and override the `_load_zone_file()` function to discover the zonefiles as per our naming convention.

Perhaps the default `ZoneFileSource` should support zone file lookups without the dot as well?

**Comment by ross** [comment]
Interesting. Guess best bet may be to support an optional `.zone` or something like that and then try loading both. Looks like the relevant bit of code is https://github.com/octodns/octodns/blob/16241d29a6ed0f72f52381334d3c1ef66e446a45/octodns/source/axfr.py#L227-L232

**Comment by ttk** [comment]
Yeah, supporting `.zone` would be helpful as that is a common naming convention and it would solve the problem on windows without any code changes.  However, supporting a custom naming convention for the zone files would still require subclassing `ZoneFileSource`, as far as I can tell.

**Comment by ross** [comment]
> require subclassing `ZoneFileSource`, as far as I can tell.

I was suggesting that the `.zone` support be added to the existing (linked) provider. Would be happy to :eye: a PR to that effect.

**Comment by yzguy** [comment]
I can take a look at this. It's a good catch, surprised it didn't come up before.

**Comment by yzguy** [comment]
@ttk Just added this functionality to the ZoneFileSource, it's been merged into master.
