### ISSUE TITLE
git checkout fails under Windows

### ISSUE THREAD

**Issue by ttk** [octodns/octodns#662]
Similar to what was reported in #657 , because Windows doesn't support files that end in a dot/period, the octodns project fails to checkout a working branch.

```
git clone git@github.com:octodns/octodns.git
Cloning into './octodns'...
done.
error: invalid path 'tests/config/split/dynamic.tests./a.yaml'
fatal: unable to checkout working tree
```

Here are the list of all files and directories that end in a dot.

```
./tests/zones/invalid.records.
./tests/zones/invalid.zone.
./tests/zones/unit.tests.
./tests/config/split/subzone.unit.tests.
./tests/config/split/unordered.
./tests/config/split/empty.
./tests/config/split/unit.tests.
./tests/config/split/dynamic.tests.
```

My workaround is to clone the project in WSL2.

**Comment by ross** [comment]
That's annoying. The new functionality can mostly work around that, but then it'll be stuck not being able to test the default/main case if we rename them all. Not sure what the best option is...

**Comment by ttk** [comment]
My plan is to rename the files with the `.zone` extension so that the checkout works in Windows.   Then I'll modify the unit tests to temporarily copy the `.zone` file to a `.` file if the detected os is not Windows.  Does that sound reasonable?

**Comment by ross** [comment]
> Then I'll modify the unit tests to temporarily copy the `.zone` file to a `.` file if the detected os is not Windows. Does that sound reasonable?

If you want they can just copy them and leave them on platforms that allow it and we can `.gitignore` the copies so that git won't try and add them back. That's probably easier than trying to clean up after things if something goes wrong during the tests.

**Comment by ross** [comment]
https://github.com/octodns/octodns/pull/665 should  get this addressed (with the fix an underlying bug in https://github.com/octodns/octodns/pull/664.) 

@ttk if you can to pull down that branch and give it a try on a windows box please do. You can probably grab a tarball of that branch to avoid having to git clone (since that won't yet work) I don't have a windows box so I can't test it.

**Comment by ross** [comment]
> ./tests/config/split/subzone.unit.tests.
> ./tests/config/split/unordered.
> ./tests/config/split/empty.
> ./tests/config/split/unit.tests.
> ./tests/config/split/dynamic.tests.

That's going to be annoying. Those are directories rather than files :-/

**Comment by ross** [comment]
Reworked https://github.com/octodns/octodns/pull/665 a bit to what I believe should function on windows and still have full code coverage.

**Comment by ttk** [comment]
Fantastic!  Thanks!
