### ISSUE TITLE
Mention related project: octodns-sync GitHub Action

### ISSUE THREAD

**Issue by patcon** [octodns/octodns#673]
@solvaholic created a GitHub Action that seems super rad :) Though he seems to be staff, guessing it's not official. But any chance that would be appropriate to reference somewhere in docs?

https://github.com/solvaholic/octodns-sync
https://github.com/marketplace/actions/octodns-sync

Thanks!

Use-case context here, in case anyone curious how tools like this support others: https://github.com/g0v/domain/issues/50

EDIT: Oops. Added link.

**Comment by ross** [comment]
Not opposed to a "Related Projects/Links" section in the readme if that's what you have in mind. Fee free to PR a start at that.

**Comment by patcon** [comment]
Gonna make a first-pass list of stuff that might have helped me. Feedback welcome:

- GitHub Action: [OctoDNS-Sync](https://github.com/marketplace/actions/octodns-sync)
- Sample Implementations
  - [`hackclub/dns`](https://github.com/hackclub/dns)
  - [`kubernetes/k8s.io:/dns`](https://github.com/kubernetes/k8s.io/tree/master/dns)
  - [`g0v-network/domains`](https://github.com/g0v-network/domains)
  - [`jekyll/dns`](https://github.com/jekyll/dns)
  - [`parkr/dns`](https://github.com/parkr/dns)
- Custom Providers
  - [`octodns/octodns-ddns`](https://github.com/octodns/octodns-ddns): A simple Dynamic DNS source.
  - [`doddo/octodns-lexicon`](https://github.com/doddo/octodns-lexicon): Use [Lexicon](https://github.com/AnalogJ/lexicon) providers as DNS sources.
  - [`asyncon/octoblox`](https://github.com/asyncon/octoblox): [Infoblox](https://www.infoblox.com/) provider.
  - [`sukiyaki/octodns-netbox`](https://github.com/sukiyaki/octodns-netbox): [NetBox](https://github.com/netbox-community/netbox) provider.
  - [`kompetenzbolzen/octodns-custom-provider`](https://github.com/kompetenzbolzen/octodns-custom-provider): phpIPAM provider.
- Resources
  - Article: [Visualising DNS records with Neo4j](https://medium.com/@costask/querying-and-visualising-octodns-records-with-neo4j-f4f72ab2d474) + code
  - Video: [FOSDEM 2019 - DNS as code with octodns](https://archive.fosdem.org/2019/schedule/event/dns_octodns/)
  - GitHub Blog: [Enabling DNS split authority with OctoDNS](https://github.blog/2017-04-27-enabling-split-authority-dns-with-octodns/)

Was pretty liberal with this list, but lemme know if there's an easy cut-off. Also, can just do PR and can do real flow, just didn't want to do bigger and messier reformatting there

**Comment by ross** [comment]
Nice, there's more out there than I realized :-).

**Comment by patcon** [comment]
k, opened PR, so I'll close this out. Thanks!
