### ISSUE TITLE
Consider including unreleased features to CHANGELOG

### ISSUE THREAD

**Issue by patcon** [octodns/octodns#678]
Would this be something we could start doing here? https://keepachangelog.com/en/1.0.0/#effort

For example, when I was trying to determine if a feature was available, I search the changelog first. Not seeing it there, I could assume it's unreleased, but because things often get missed from changelogs, many would search for the code and use blame to find out when it went in.

An unreleased section of changelog would make it unambiguously clear when someone will need to rely on an unreleased version :)

Thanks for considering!

**Comment by ross** [comment]
Half of the time I start keeping the changelog up to date with a ????-??-?? placeholder section and start keeping track of what's merged, but not yet released. No objection to this in concept/intention, but jut not something I always think to do...

**Comment by patcon** [comment]
Heh k thx ross!

I could investigate options that might make changelings in general easier for maintainers, make a few proposals here for your consideration, or I could just close this out. Lemme know :)

**Comment by ross** [comment]
> I could investigate options that might make changelings in general easier for maintainers (and make a few proposals here for your consideration), or I could just close this out. Your call, lemme know :)

Up to you. It's not super high on my need/priority list so I haven't worried about it. It seems like a really tough problem to solve well, but happy to look at links to things if you have them already. If not it's probably fine to close. Thanks.

**Comment by patcon** [comment]
k thx! If I haven't moved this is 2 weeks, def anyone feel free to close
