### ISSUE TITLE
Apex NS records can not sync

### ISSUE THREAD

**Issue by cemkayar** [octodns/octodns#680]
I noticed that when I wanted to sync a zone between power dns servers, NS records could not be synchronized. Looking at the document, NS record seems to be supported for Power dns. Am I missing something?

**Comment by yzguy** [comment]
Are you talking about the root NS records at the apex of your zone? If so, these are unsupported. Relevant issue is #38

Each provider has a different implementation, some require you to have their servers, some don't let you control it at all, etc. So at the moment it's not supported.

**Comment by ross** [comment]
Closing as a dup of https://github.com/octodns/octodns/issues/38. Feel free to reopen if that's not the case.
