### ISSUE TITLE
Hetzner DNS provider

### ISSUE THREAD

**Issue by ricardbejarano** [octodns/octodns#684]
Hey, I will PR a provider for use with [Hetzner DNS Public API](https://dns.hetzner.com/api-docs) during the following weeks.

Just a heads up.

Will close this issue once it's been merged.

**Comment by evgkrsk** [comment]
Any news?

**Comment by ricardbejarano** [comment]
Still working through it, my personal life didn't leave much time for it.

I created this issue mainly so that efforts are consolidated, if anyone is able to help I'd really appreciate it.

Otherwise, I expect to have something PR-able in 2-3 natural weeks.

**Comment by ross** [comment]
Would recommend pushing a PR up if you have anything locally in lieu of this issue to call that out. That way others can potentially help if they're interested and/or if you get a start, but don't come up with the time to finish it off someone else could pick it up. If you don't have anything push-worthy yet that's fine, but just want to call out that PRs aren't necessarily finished products and you can always choose to open it as a "draft" to call that out.

**Comment by ricardbejarano** [comment]
Raised #691 draft PR with the API client class.
Keep up with progress there.

I kind of have the OctoDNS Provider API figured out, so I expect not to face any major challenges with the `HetznerProvider` class.

I am missing some insight on testing. Maybe @ross can give a hand with that?

**Comment by ricardbejarano** [comment]
PR merged.

Closing.
