### ISSUE TITLE
Does not allow multiple TXT records with same name (i.e. @)

### ISSUE THREAD

**Issue by lksoft** [octodns/octodns#690]
I have multiple TXT records that I want to maintain on my zone (for spa, google verification etc), and I currently have them as three separate TXT records thus:

```
@ IN TXT v=spf1 include:mail.zendesk.com include:amazonses.com include:_spf.hostedemail.com ~all
@ IN TXT google-site-verification=su5pvO_NECbUXOCrXaGVSBFesyZ_LmdpE5JZteJFJWw
@ IN TXT amazonses:5NTfBAK1VfSDgap44rvj974baZgE/dWPC6Y3MaSOWaE=
```
But I cannot seem to do this with octodns, if I put them all as '@', then only the last is taken. I get the idea of excluding duplicates for A, AAAA, & CNAME records but **TXT** records seems like an oversight.

Am I wrong?

**Comment by ross** [comment]
With the YAML config it'd be something like:

```yaml
'':
  type: TXT
  values:
    - first
    - second
    - third
```

Based on what you have there it looks like maybe you're using the zone file source or something? If so I'm not deeply familiar with it enough to say what needs to be there. In general it's there to use to initially import things and the recommended way of configuring things going forward would be the yaml route. There may be exceptions to that though...

**Comment by lksoft** [comment]
Oh duh, that is simple enough!

That does create a single record instead of separate ones. I will do some testing to see if that is an issue. Seems to work for the SPF record, but I'll have to see if the google verification works like that.

**Comment by lksoft** [comment]
I am going to close this, since this can just be avoided by properly formatting the yaml.
