### ISSUE TITLE
compare operation doesn't seem to care about lenient flag

### ISSUE THREAD

**Issue by shollingsworth** [octodns/octodns#708]
Is this by design? I use it to compare multiple dumps of route53 domains that have records that normally do not pass validation.

I had to fork a version where I added it. Wondering if this is something that you folks are interested in putting upstream.

**Comment by ross** [comment]
No specific reason it doesn't. Probably either predated `lenient` being a thing and wasn't added when it came about or otherwise was just an oversight/wasn't needed so wasn't added. PR welcome.
