### ISSUE TITLE
Move to python's f-strings

### ISSUE THREAD

**Issue by viranch** [octodns/octodns#711]
With this project fully on python3 now, are there any plans to replace all usages of `str.format` to f-strings? It's much easier to use among numerous other advantages listed in https://www.python.org/dev/peps/pep-0498/.

Let me know your thoughts and I will be happy to contribute.

**Comment by viranch** [comment]
I noticed that CI runs only 3.x checks, so I assumed that octo officially dropped support for python 2. Did I read #677 correctly that 2.x support will completely end on 2021-08-16?

**Comment by ross** [comment]
> that 2.x support will completely end on 2021-08-16?

Yeah. I'd actually forgot that I picked a date :grin: 

Until then it's on a YMMV/no promises support to give a couple bit stragglers time to update their setup...

**Comment by ross** [comment]
Fixed by https://github.com/octodns/octodns/pull/768
