### ISSUE TITLE
"OctoDNS" vs "octoDNS"

### ISSUE THREAD

**Issue by viranch** [octodns/octodns#733]
... wondering which one is intended to be correct. I see a mixed usage across READMEs. It's probably a good idea to finalize on one vs the other and update all references accordingly.

**Comment by ross** [comment]
I think the short answer is `octoDNS`, but I don't personally have an issue with OctoDNS. Wouldn't object to a PR that makes the change in documentation etc, but it's not something that personally keeps me awake at night :grin:
