### ISSUE TITLE
Release date for v0.9.13 ?

### ISSUE THREAD

**Issue by meghashyamps** [octodns/octodns#741]
@ross I see that a lot of relevant changes have gone in since v0.9.12. We have an internal process to vet all open-source project against a specific release version, and v0.9.13 is the release we want. When do you suppose you will publish v0.9.13 ?

**Comment by ross** [comment]
No specific timeline tbh. Will add a todo list item to take a look and see if there's anything that needs to :ship: first or if it's ready to go.

**Comment by meghashyamps** [comment]
Thank you for releasing v0.9.13 👍 

Closing this issue.
