### ISSUE TITLE
Are there any examples of code usage (non-cli)?

### ISSUE THREAD

**Issue by ambersariya** [octodns/octodns#766]
Any examples of using the classes from the library to perform some basic tasks such as creating new empty zone, listing zone records and creating/updating/deleting records in zone would be useful if someone has any, thanks.

**Comment by ross** [comment]
Hi @ambersariya. There's no examples of using octoDNS as a library beyond what can be gleaned from looking at [the cmds](https://github.com/octodns/octodns/tree/master/octodns/cmds) that make up the CLI all of which are fairly straightforward. The bulk of the orchestration lives in [manager.py](https://github.com/octodns/octodns/blob/master/octodns/manager.py).

octoDNS isn't really intended as a unified API to various providers so there's not a simple path to listing zones or doing CRUD on records directly. That's just not the problem its trying to solve. There are other libraries that do, e.g. the stuff mentioned in https://github.com/octodns/octodns/issues/534. I've not used them or really even looked into them beyond finding that they aren't well suited to octoDNS's needs.

Good luck.
