### ISSUE TITLE
New feature to support Rage4?

### ISSUE THREAD

**Issue by FreshP0325** [octodns/octodns#773]
It seems that there isn't a fork that supports Rage4 now, what can we do to support it?

**Comment by ross** [comment]
Not familiar with the provider, but in general the place to start would be to create a PR adding a new `Provider` child class for it. [`DnsimpleProvider`](https://github.com/octodns/octodns/blob/master/octodns/provider/dnsimple.py#L86) is one of the least complex and may serve as a good starting point. There's a handful of other fairly striaghtforward providers that may be closer to Rage4, but without knowing it I don't have a clue.

**Comment by ross** [comment]
There is now a template repo and process to ease this sort of work, https://github.com/octodns/octodns-template. https://github.com/octodns/octodns-powerdns is a good example for simple providers with good apis.

**Comment by FreshP0325** [comment]
@ross That helps a lot, thanks!
