### ISSUE TITLE
Use of Route53 list_hosted_zones causes mass rate limiting in our scale tests

### ISSUE THREAD

**Issue by slandry90** [octodns/octodns#776]
During scale testing of octodns we've hit an issue with the route53 provider.

To briefly describe our setup, we have ~12000 zones and are using a notifier to sync individual zones when changes are made to that zone. This prevents us from needing to iterate through thousands of zones and records that we know have not changed since the last execution.

https://github.com/octodns/octodns/blob/4c9f0137a1f1a378e190670a5279363111c87d2b/octodns/provider/route53.py#L658

The r53_zones function is currently used to retrieve the hosted_zone_id of a particular zone, in order to do that it runs a list_hosted_zone call. The list_hosted_zone call has a hard pagination limit of 100. In our case where we have about 12000 zones in our route53 account, this means that each time a new sync job runs it has to execute at least 120 list_hosted_zones calls in order to retrieve all the zones just to get the singular hosted_zone_id which could be retrieved via a list_hosted_zones_by_name call.

I know different people use octodns differently and swapping the functionality from list_hosted_zone to list_hosted_zones_by_name could have some adverse effects for those that are running 100s of zones within the same sync job (would have the same problem but in a different direction) so would like some thoughts on a route forward here.

I'd like to initially propose adding a flag in route53 to toggle the behavior to list_hosted_zones_by_name, leaving the current behavior as the default but allowing users like us to be able to avoid the mass number of api calls. I'd rather not fork if we don't need to but we can do that as well if this isn't a use case the group here is game for supporting.

Would also be happy to help with testing or submitting a PR if that helps as well.

Thanks

**Comment by ross** [comment]
> 'd like to initially propose adding a flag in route53 to toggle the behavior to list_hosted_zones_by_name, leaving the current behavior as the default but allowing users like us to be able to avoid the mass number of api calls. I'd rather not fork if we don't need to but we can do that as well if this isn't a use case the group here is game for supporting.

👍 to that approach. I'll think about it and see if I can come up with anything auto-magic/smarter, but nothing immediately comes to mind. 

> Would also be happy to help with testing or submitting a PR if that helps as well.

Definitely. Will be happy to 👁️ one.

**Comment by slandry90** [comment]
@ross proposed the PR here, https://github.com/octodns/octodns/pull/783. Let me know if I need to make changes or improvements!

**Comment by ross** [comment]
Fixed in https://github.com/octodns/octodns/pull/783

**Comment by slandry90** [comment]
Thanks @ross! What's the usual timeframe for new releases to be cut? Trying to decide if we want to wait or build from source in our code.

**Comment by yzguy** [comment]
@slandry90 You can install from a Git hash in the meantime.

```
$ pip install -e git+https://git@github.com/octodns/octodns.git@<SHA>#egg=octodns
```
