### ISSUE TITLE
Is there a way to override too many deletes threshold? 

### ISSUE THREAD

**Issue by Unaidedsteak** [octodns/octodns#785]
Hello!

I've looked through the README and couldn't find anything that mentions a setting or option to override the too many deletes threshold. Does this option exist?

I'm running into this:
`octodns.provider.plan.UnsafePlan: Too many deletes, 39.85 is over 30.00 %(104/261)`

Thanks!

**Comment by ross** [comment]
The provider params that control the thresholds are documented [here](https://github.com/octodns/octodns/blob/e087a3b26f0272a994d3efba2a62ead0f4617a16/docs/records.md#restrict-record-manipulations)

If you just want to get past it once to say, this is actually OK, then you can add the `--force` parameter to the command line.
