### ISSUE TITLE
More of a question. 

### ISSUE THREAD

**Issue by mk5559** [octodns/octodns#788]
I have record with weighted shuffle filter..answers with load values.

I am trying to dump config and I get this validation Error. How to deal with records during dump which have filters like weighted shuffle, priority etc..

```
Traceback (most recent call last):
  File "/root/python_venv/dns-dr/bin/octodns-dump", line 8, in <module>
    sys.exit(main())
  File "/root/python_venv/dns-dr/lib/python3.6/site-packages/octodns/cmds/dump.py", line 35, in main
    *args.source)
  File "/root/python_venv/dns-dr/lib/python3.6/site-packages/octodns/manager.py", line 525, in dump
    source.populate(zone, lenient=lenient)
  File "/root/python_venv/dns-dr/lib/python3.6/site-packages/octodns/provider/ns1.py", line 799, in populate
    record = Record.new(zone, name, data, source=self, lenient=lenient)
  File "/root/python_venv/dns-dr/lib/python3.6/site-packages/octodns/record/__init__.py", line 121, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record abc.example-manual.com.
  - missing value(s)
```

When I run it with lenient. Just skips its..

```
 zone=Zone<example-manual.com.>, create record=<ARecord A 3600, abc.example-manual.com., ['']>
```

Once I remove filter chains on NS1 portal..short answers are populated from config dump..
  
 Normal API call:  
 
 ```
 {
         "tier" : 2,
         "domain" : "abc.example-manual.com",
         "ttl" : 3600,
         "id" : "5da0efe4f2abd00001af59a6",
         "type" : "A",
         "short_answers" : [
            "1.1.1.1",
            "2.2.2.2",
            "3.3.3.3"
         ]
      },
 ```

**Comment by ross** [comment]
That's, unfortunately, the nature of the more specialized/provider specific record types with NS1 and other providers. octoDNS is intended to have a single setup pushed to multiple providers and as part of that it doesn't support all of the various advanced record features that are unique to each provider.

It generally should blow up with an error when it encounters records that it cannot support, but some of the details of that are still WIP. The error you saw is good in that it blows up, but it's catching a secondary problem and not the original one...

`lenient` is the way to say I acknowledge this isn't going to be simple/smooth and I'll pay close attention and make sure that I'm OK with the results and tweak things as needed.

So summary, I think you've hit a case where I'd expect complications and that you as the user have to decide what you want to do with that record. If you want to use octoDNS it'll have to be reworked to use `dynamic` semantics or alternatively tell octoDNS to ignore it and manually manage it etc.
