### ISSUE TITLE
UnsafePlan threshold limit reached

### ISSUE THREAD

**Issue by Guegui** [octodns/octodns#808]
Hey! Newb here.

We've been using octodns and we have CI/CD setupped for deployment to cloudflare. Lately we get that error while pushing a change:

`Traceback (most recent call last):
  File "/usr/local/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/octodns/cmds/sync.py", line 40, in main
    force=args.force)
  File "/usr/local/lib/python3.7/site-packages/octodns/manager.py", line 454, in sync
    plan.raise_if_unsafe()
  File "/usr/local/lib/python3.7/site-packages/octodns/provider/plan.py", line 77, in raise_if_unsafe
    existing_record_count)
octodns.provider.plan.UnsafePlan: Too many updates, 72.73 is over 30.00 %(8/11)
ERROR: Job failed: command terminated with exit code 1`

If I understand, there was too many changes pushed lately. It makes sense because we had someone delete one of our Zones on our DNS and octodns repushed it back with all the entries in it. Question is, now that I identified the cause, how can I go around that or put the threshold higher so my job passes?

Thanks!

**Comment by ross** [comment]
:wave:

The provider params that control the thresholds are documented [here](https://github.com/octodns/octodns/blob/e087a3b26f0272a994d3efba2a62ead0f4617a16/docs/records.md#restrict-record-manipulations)

If you just want to get past it once to say, this is actually OK, then you can add the `--force` parameter to the command line. 

/cc https://github.com/octodns/octodns/issues/785#issuecomment-926739806 which this similar to and the answer was copied from.
