### ISSUE TITLE
pip install with different account in virtualenv failed

### ISSUE THREAD

**Issue by guicai-private** [octodns/octodns#812]
Hey! Newb here.

I found installing octodns in virtualenv with different users from source code could fail for permission issue.

```
        File "/tmp/pip-install-bvmz246h/octodns_f98df76a99b642c59c3a3c94c3ec7fdd/setup.py", line 80, in <module>
          long_description=long_description(),
        File "/tmp/pip-install-bvmz246h/octodns_f98df76a99b642c59c3a3c94c3ec7fdd/setup.py", line 56, in long_description
          with open('/tmp/mod', 'w') as fh:
      PermissionError: [Errno 13] Permission denied: '/tmp/mod'
```

If user A intall octodns, a `/tmp/mod` file will then be created, and there for user B will failed to install octodns.  

Could we avoid writing /tmp/mod in setup.py? 

Related script:
https://github.com/octodns/octodns/blob/master/setup.py#L56

**Comment by ross** [comment]
Yeah. That should likely use `TemporaryFile`, https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryFile
