### ISSUE TITLE
Feature request: dynamic for ALIAS/ANAME records?

### ISSUE THREAD

**Issue by istr** [octodns/octodns#823]
@ross currently I am experimenting with the `dynamic` feature using the constellix and ns1 providers.
This works great, so far, using `CNAME` records. However, I would like to take this one step further:

- both constellix and ns1 support `ALIAS` (constellix: `ANAME`) records for dynamic setups as "non-root" entries
- the upstream only has a single DNS provider
- both are able to cache the resolved `A`/`AAAA` values; so they keep going if the upstream (spof) fails

Given the fact, that

- `dynamic` is still in an early development state
- `dynamic` is "non-compliant" anyway

I would like to ask:

1. are you willing to support `ALIAS` for `dynamic` ?
2. do you think it would make sense to set the `lenient` flag to `true` implicitly in this case? (because `dynamic` with non-root `ALIAS` is not much more "non-compliant" than other `dynamic` setups)

**Comment by ross** [comment]
> * both constellix and ns1 support `ALIAS` (constellix: `ANAME`) records for dynamic setups as "non-root" entries

Could you elaborate on the need/use case for `ALIAS` over `CNAME` here? 

> * both are able to cache the resolved `A`/`AAAA` values; so they keep going if the upstream (spof) fails

Is it just to get the caching behavior or there something more to it?

> * `dynamic` is still in an early development state

At this point I'd call `dynamic` fairly stable. Did you see something in the documentation/issues that leads you to conclude otherwise?

> * `dynamic` is "non-compliant" anyway

Not sure what you mean by this. Could you elaborate?



> * are you willing to support `ALIAS` for `dynamic` ?

I'd definitely be willing to have support for apex `ALIAS` records if there are meaningful use cases for that.

> 2\. do you think it would make sense to set the `lenient` flag to `true` implicitly in this case? (because `dynamic` with non-root `ALIAS` is not much more "non-compliant" than other `dynamic` setups)

If, and only if, providers could easily/cleanly support dynamic non-apex `ALIAS` records they would certainly need to include `lenient: true`. If it was complicated to implement or caused other problems/confusion I'd probably lean towards not. Ideally it'd be like non-dynamic `ALIAS` and mostly come for free just by adding `lenient`, though even that has caused confusion/hiccups/bugs so ...

**Comment by istr** [comment]
> Could you elaborate on the need/use case for ALIAS over CNAME here?

The use case is latency optimization for first time visitors in a multi-DNS / multi-CDN setup. Some CDNs have a great edge server infrastructure, but fail when it comes to fast resolving / traffic direction. If you put fast DNS providers (e.g. constellix/ns1) in front of that, you can gain improvements that can yield something about half of the complete load time for the initial page. If CDN provider A takes 400ms for the traffic routing decision and CDN provider B takes 25ms (these are numbers from measurements over a few weeks), you might gain a lot if you can skip the CNAME resolving for A most of the time. Apart from that, most CDN providers do not offer a multi-DNS setup for their resolving and traffic direction, so you need to move the DNS part of the game out of the CDN providers' scope, if "multi-DNS" is a requirement.
Using plain `A`/`AAAA` records in this situation is not a good option, because some CDN providers might change the PoP name to IP mapping any time without prior notice.

> At this point I'd call dynamic fairly stable. Did you see something in the documentation/issues that leads you to conclude otherwise?

https://github.com/octodns/octodns/blob/master/docs/dynamic_records.md

> There is preliminary support for CNAME records, but caution should be exercised as they have not been thoroughly tested.

Apart from that, the constellix provider does not seem to recognize existent `dynamic` configurations, so every run against constellix with `dynamic` reports a change (but that should be addressed in a separate issue).

> > dynamic is "non-compliant" anyway

> Not sure what you mean by this. Could you elaborate?

From what I understand with regards to the `lenient` flag, it is meant to address setups that are not _RFC_ compliant.
https://github.com/octodns/octodns#readme
> `lenient` mostly focuses on the details of Records and standards compliance. When set to true octoDNS will allow allow non-compliant configurations & values where possible.

But the whole `dynamic` construct (as well as the now superseded `geo` construct) is not (yet) standards compliant anyway (let alone RFC compliance):
https://github.com/octodns/octodns/blob/master/docs/dynamic_records.md
> Configuring GeoDNS is complex and the _details of the functionality vary widely_ from provider to provider.

That is to say -- if I encounter a record that has `dynamic` configured I would expect that there is an implicit `lenient` flag set on record level and there is no need to explicitly enable `lenient` for other "non-compliant" features like ANAME/ALIAS on subdomains/non-apex. But I perfectly get the point of
> If it was complicated to implement or caused other problems/confusion I'd probably lean towards not.

so better double check and have the user confirm that (s)he knows what (s)he is doing.

**Comment by ross** [comment]
> The use case is latency optimization ... any time without prior notice.

Does the `ALIAS` add something over a `CNAME` though? At most I'd imagine it would improve caching if the provider's `ALIAS` lookups were cached locally, but I don't see how that could work well since the provider doesn't know what the upstream (CDN) traffic policy would be. It seems like either the provider would cache the values (based on TTL) and then serve up incorrect responses based on the CDN's traffic steering or it would have to forward every request to the CDN provider's DNS setup anyway. 

It also wouldn't really get multi-dns for the CDN as the providers would each individually still have to do lookups and fail. If they happen to have a cached response and are willing to serve stale that might help a bit, but still nowhere near the fault tolerance of the CDN provider having mutli-dns. I believe a dynamic `CNAME` with health checking would likely work better in this case, not that it would work around the CDN provider's DNS issues, but that it could allow a fallback to another CDN provider who is still healthy.

> https://github.com/octodns/octodns/blob/master/docs/dynamic_records.md

Ah. That's mostly referring to `CNAME`s as I hadn't used them, but I believe there are quite a few people who are these days and some of the early shortcomings have been addressed. Maybe @viranch can weight in on whether that first paragraph can be reworked as I believe they're using `CNAME`s

> Apart from that, the constellix provider does not seem to recognize existent `dynamic` configurations, so every run against constellix with `dynamic` reports a change (but that should be addressed in a separate issue).

Ah. Definitely should be filed. I don't have access to that provider so we've been relying on people who do to work on it. We can tag them on that issue. Likely just bugs/hiccups in that provider.

> > `lenient` mostly focuses on the details of Records and standards compliance. When set to true octoDNS will allow allow non-compliant configurations & values where possible.
> 
> But the whole `dynamic` construct (as well as the now superseded `geo` construct) is not (yet) standards compliant anyway (let alone RFC compliance): https://github.com/octodns/octodns/blob/master/docs/dynamic_records.md

Ah. As far as octoDNS is concerned this is a standards adjacent thing. `CNAME`s aren't allowed at the apex of zones standards-wise, though some providers do allow them. octoDNS's definition of `ALIAS` provides `CNAME` like functionality for apex records in providers that support the concept. Under the hood that's sometimes that's done with a special record type and other times the provider allows `CNAME`s there in a non-RFC manner. 

Relatedly octoDNS considers allowing `ALIAS`es outside of the apex to be a non-standard thing even though the whole type isn't an RFC. It's an opposite/follow on from `CNAME`s not being allowed at the apex, thus `lenient` lets you do something it considers non-compliant. 


> But the whole `dynamic` construct (as well as the now superseded `geo` construct) is not (yet) standards compliant anyway (let alone RFC compliance):
> https://github.com/octodns/octodns/blob/master/docs/dynamic_records.md

Yeah. I don't imagine it'll ever be a standards compliant thing unless someone shows up and wants to push it through the RFC process and I'd have a hard time imaging it making it through, but 🤷 😁 



> That is to say -- if I encounter a record that has `dynamic` configured I would expect that there is an implicit `lenient` flag set on record level and there is no need to explicitly enable `lenient` for other "non-compliant" features like ANAME/ALIAS on subdomains/non-apex. But I perfectly get the point of

Ah. Yeah. Maybe the section on `lenient` is worded a little too strongly. It's not strictly a standards thing, it's more of a standards/rules type thing. octoDNS's rules are guided by RFCs, but it does extend and define other rules as needed in addition to those. 

`lenient` lets you say I know what I'm doing here is not normal, but let me do it anyway and turns off enforcing the rules.

**Comment by istr** [comment]
>  I don't have access to that provider so we've been relying on people ...

It is comparatively cheap to tinker around with constellix (pay-as-you-go). The experiments I made so far cost far below  USD 20 per month.

> It also wouldn't really get multi-dns ... another CDN provider who is still healthy.

Yes, I see your point. The setup I am referring to needs the lookup on the side of the CDN provider(s) _only_ for the "last hop".
The traffic direction is performed by means of the multi-DNS setup with geo-targeting, so multi-DNS performs the traffic direction and CDN providers' DNS only provides PoP address resolution. These are _relatively stable_ (so caching works quite well).
Maybe I put in some sample config to clarify (only _one_ provider for easy reading). Note that KeyCDN is _not_ the provider having DNS performance issues (they are _fast_ but rely on awsdns _only_).

Variant a) hard A/AAAA records. Need to monitor for (rare) PoP address changes separately.

    cdn:
      dynamic:
        pools:
          apac:
            values:
              - status: up
                value: 199.254.199.55  # p-jptk00.kxcdn.com.
          eu:
            values:
              - status: up
                value: 185.172.148.128  # p-defr00.kxcdn.com.
              - status: up
                value: 185.172.148.132  # p-defr00.kxcdn.com.
          eu_ch:
            values:
              - status: up
                value: 94.126.16.223  # p-chzh00.kxcdn.com
          eu_de:
            values:
              - status: up
                value: 185.172.148.128  # p-defr00.kxcdn.com.
              - status: up
                value: 185.172.148.132  # p-defr00.kxcdn.com.
          eu_fr:
            values:
              - status: up
                value: 89.44.9.58  #  p-frpa00.kxcdn.com.
          eu_nl:
            values:
              - status: up
                value: 185.172.149.128  # p-nlam00.kxcdn.com.
              - status: up
                value: 185.172.149.132  # p-nlam00.kxcdn.com.
          eu_uk:
            values:
              - status: up
                value: 68.70.192.128  # p-uklo00.kxcdn.com.
          na:
            values:
              - status: up
                value: 51.222.8.159  # p-camo00.kxcdn.com.
          ocean:
            values:
              - status: up
                value: 103.231.91.78  # p-nzau00.kxcdn.com.
        rules:
          - geos:
            - AS
            pool: apac
          - geos:
            - OC
            pool: ocean
          - geos:
            - NA
            - SA
            pool: na
          - geos:
            - EU-CH
            pool: eu_ch
          - geos:
            - EU-DE
            pool: eu_de
          - geos:
            - EU-FR
            pool: eu_fr
          - geos:
            - EU-NL
            pool: eu_nl
          - geos:
            - EU-GB
            pool: eu_uk
          - pool: eu
      ttl: 60
      type: A
      values:
        - 185.172.148.128  # p-defr00.kxcdn.com.
        - 185.172.148.132  # p-defr00.kxcdn.com.

b) same with CNAME (now you "buy" the latency from upstream, if they have)

    cdn:
      dynamic:
        pools:
          apac:
            values:
              - status: up
                value: p-jptk00.kxcdn.com.
          eu:
            values:
              - status: up
                value: p-defr00.kxcdn.com.
          eu_ch:
            values:
              - status: up
                value: p-chzh00.kxcdn.com
          eu_de:
            values:
              - status: up
                value: p-defr00.kxcdn.com.
          eu_fr:
            values:
              - status: up
                value: p-frpa00.kxcdn.com.
          eu_nl:
            values:
              - status: up
                value: p-nlam00.kxcdn.com.
          eu_uk:
            values:
              - status: up
                value: p-uklo00.kxcdn.com.
          na:
            values:
              - status: up
                value: p-camo00.kxcdn.com.
          ocean:
            values:
              - status: up
                value: p-nzau00.kxcdn.com.
        rules:
          - geos:
            - AS
            pool: apac
          - geos:
            - OC
            pool: ocean
          - geos:
            - NA
            - SA
            pool: na
          - geos:
            - EU-CH
            pool: eu_ch
          - geos:
            - EU-DE
            pool: eu_de
          - geos:
            - EU-FR
            pool: eu_fr
          - geos:
            - EU-NL
            pool: eu_nl
          - geos:
            - EU-GB
            pool: eu_uk
          - pool: eu
      ttl: 3600 # short TTL is now on the last hop behind the CNAME
      type: CNAME
      value: p-defr00.kxcdn.com.

c) same with `ALIAS` instead of `CNAME` (now you "cache" away the latencies that might occur within the "last hop" resolution and works at least with constellix and ns1).

Admittedly, this whole construction is somewhat questionable, so possibly not worth allowing `ALIAS` here if not enough providers can handle it.
Feel free to close the issue if you don't see other valid use cases with `ALIAS` on non-apex combined with `dynamic`.

**Comment by ross** [comment]
> The traffic direction is performed by means of the multi-DNS setup with geo-targeting, so multi-DNS performs the traffic direction and CDN providers' DNS only provides PoP address resolution.

If i understand the setup, this overall probably isn't a good practice as it's removing the ability of the CDN provider to manage traffic by selecting specific POPs and making decisions about what goes to them. This prevents them from being able to make performance decisions to send things to the best locations. They lose the ability to remove traffic from POPs during maintenance or to gracefully redirect it away when there's problems. Moving traffic around is also common practice to defend against attack, either to move legitimate things that are getting hit as collateral damage somewhere safe or to attract & sink the malicious stuff to a specific location. As you point out it would also run into problems as the CDN provider expands and adds or removes POPs over time. E.g. new locations won't be utilized and old ones they're shutting down would still be included.  

CDNs usually have a fqdn they expect things to CNAME to and that fqdn often returns anycast IPs that direct traffic based on BGP shortest path. I haven't dug into https://www.keycdn.com/ deeply, but it seems to work similarly. 

I believe the minor gains in serving up cached POP lookups when the CDN's DNS failed would be outweighed by the increase in problems mentioned above. 

Also I don't imagine providers have any dynamic logic on the resolution of their POP fqdns, e.g. `p-jptk00.kxcdn.com.` is very likely a simple A/AAAA record as the logic of directing things likely happens. These lookups are likely slow b/c they have a low TTL (i'm seeing ~60s) and aren't common lookups (using the pop fqdns wouldn't be rare) and thus are almost never cached across the internet. 

Case `a` would remove the providers DNS lookup/latency, but result in a very fragile setup. When pop changes as you point out, but IP address changes and traffic shifting is very common/daily thing so I suspect it'd see frequent issues. 

`b` and `c` are possibly equivalent performance-wise, though it depends greatly on the details of the providers `ALIAS` lookup implementation's caching and how busy (cached) the POP fqdns are. It would just change who's caching them. In case `c` the dns provider would be based on their `ALIAS` implementation (which may or may not cache) and in case `b` the normal dns resolver/cache infrastructure would be doing the caching. Either way it would likely be based on the TTL of the records which for these POPs are surprisingly low. There'd be performance differences, but there's no guarantees which would be faster. 

> Admittedly, this whole construction is somewhat questionable, so possibly not worth allowing `ALIAS` here if not enough providers can handle it.

Heh. Yeah. I enjoy thinking about/working through setups like this thus my long winded/rambling answer above. All of this is not to say that I'm against the ideal of `dynamic` `ALIAS`es, just my thoughts on the specific use cases here and I haven't yet come up with a case where I'd make use of them. That's roughly what leads me to the thinking of it if mostly just works I'd be fine with it being possible with `lenient` saying "I know i'm doing odd stuff here". Tbh it's probably something that will live on a potential TODO list until someone comes across the use case and need that leads them to implement it.

**Comment by istr** [comment]
> Tbh it's probably something that will live on a potential TODO list until someone comes across the use case and need that leads them to implement it.

Let's keep the TODO list lean and clean. I am closing this. Feel free to re-open if you see any reason to do so.
