### ISSUE TITLE
OVH  issue with GET SRV records

### ISSUE THREAD

**Issue by hawaii6** [octodns/octodns#832]
I noticed, that when octodns pulling zone from OVH it adds second dot to every srv records. Next to that I have problem with pushing configuration to another provider.

Example: some config from zone file

```
_autodiscover._tcp:
  ttl: 0
  type: SRV
  value:
    port: 443
    priority: 0
    target: mailconfig.ovh.net.
    weight: 0
```

output from octodns-sync:

```
********************************************************************************
* hidden.pl.
********************************************************************************
* config (YamlProvider)
*   Create Zone<hidden.pl.>
*   Create <ARecord A 0, hidden.pl., ['5.6.7.8']> (ovh)
*   Create <MxRecord MX 0, hidden.pl., [''1 mx4.mail.ovh.net.'', ''10 mx3.mail.ovh.net.'']> (ovh)
*   Create <TxtRecord TXT 0, hidden.pl., ['1|www.hidden.pl']> (ovh)
*   Create <SrvRecord SRV 0, _autodiscover._tcp.hidden.pl., [''0 0 443 mailconfig.ovh.net..'']> (ovh)
*   Create <SrvRecord SRV 0, _imaps._tcp.hidden.pl., [''0 0 993 ssl0.ovh.net..'']> (ovh)
*   Create <SrvRecord SRV 0, _submission._tcp.hidden.pl., [''0 0 465 ssl0.ovh.net..'']> (ovh)
*   Create <CnameRecord CNAME 0, autoconfig.hidden.pl., mailconfig.ovh.net.> (ovh)
*   Create <CnameRecord CNAME 0, autodiscover.hidden.pl., mailconfig.ovh.net.> (ovh)
*   Create <CnameRecord CNAME 0, ftp.hidden.pl., hidden.pl.> (ovh)
*   Create <ARecord A 0, test.hidden.pl., ['1.2.3.4']> (ovh)
*   Create <ARecord A 0, www.hidden.pl., ['5.6.7.8']> (ovh)
*   Create <TxtRecord TXT 0, www.hidden.pl., ['3|welcome']> (ovh)
*   Summary: Creates=12, Updates=0, Deletes=0, Existing Records=0
********************************************************************************
```

OVH API returns value alright: 

```
method GET from value `/domain/zone/hidden.pl/record/5214708123` 
{
  "ttl": 0,
  "subDomain": "_submission._tcp",
  "zone": "hidden.pl",
  "fieldType": "SRV",
  "target": "0 0 465 ssl0.ovh.net.",
  "id": 5214708123
}
```

**Comment by ross** [comment]
Looks like there's a `.` being added in https://github.com/octodns/octodns/blob/d3c9b31c013fcdbe7741de7d9105aa6306cd4a12/octodns/provider/ovh.py#L199, but I don't see that happening for other record types that normally end in `.` so my guess is that's the culprit. I don't have access to OVH so I can't make the change and test it.

**Comment by hawaii6** [comment]
bingo...without dot at line 199 works fine. Tests it on my few domains. Thanks for fast reply

**Comment by ross** [comment]
> bingo...without dot at line 199 works fine. Tests it on my few domains. Thanks for fast reply

Cool. You want to PR the change?

**Comment by istr** [comment]
I am willing to provide a PR for this (trivial) change against octodns-ovh, once the split is done.
See https://github.com/octodns/octodns/pull/852.
Maybe I can cater for the 3.10 issue there, too.

**Comment by pierregeekme** [comment]
Hello,

thank you for PR.  In CI, step CI Build is failed.
Only version 0.0.1 is available and it contains '{target}.'
Do you have the possibility to restart the CI?

Thank you in advance.
