### ISSUE TITLE
Lots of provider modules tests failing post v0.9.16

### ISSUE THREAD

**Issue by ross** [octodns/octodns#885]
Started seeing failures when manually working so I created a new manually runnable action that runs the test suites of all the modules in https://github.com/octodns/octodns/pull/883.

Result is a lot of copy-n-pasted failures due to the fact that `Zone.changes` no longer excludes root NS records with the `_is_eligible` filter function. 

This is fine in terms of it's not an actual breakage of any real-world use of octoDNS. It's also something that the work in https://github.com/octodns/octodns/pull/883 is designed to surface earlier... 

```
            zone = Zone('unit.tests.', [])
            provider.populate(zone)
            self.assertEqual(19, len(zone.records))
            changes = expected.changes(zone, provider)
>           self.assertEqual(0, len(changes))
E           AssertionError: 0 != 1
```

I think the fix here will just be to go through and update all the tests to handle this case. It's not ideal, but it's probably the best option.

/cc https://github.com/octodns/octodns/runs/5482284584?check_suite_focus=true
/cc https://github.com/octodns/octodns/pull/883

**Comment by ross** [comment]
* [x] [octodns/octodns-azure](https://github.com/octodns/octodns-azure)
* [ ] [octodns/octodns-cloudflare](https://github.com/octodns/octodns-cloudflare)
* [x] [octodns/octodns-constellix](https://github.com/octodns/octodns-constellix)
* [x] [octodns/octodns-ddns](https://github.com/octodns/octodns-ddns)
* [ ] [octodns/octodns-digitalocean](https://github.com/octodns/octodns-digitalocean)
* [ ] [octodns/octodns-dnsimple](https://github.com/octodns/octodns-dnsimple)
* [ ] [octodns/octodns-dnsmadeeasy](https://github.com/octodns/octodns-dnsmadeeasy)
* [ ] [octodns/octodns-dyn](https://github.com/octodns/octodns-dyn)
* [ ] [octodns/octodns-easydns](https://github.com/octodns/octodns-easydns)
* [ ] [octodns/octodns-edgedns](https://github.com/octodns/octodns-edgedns)
* [x] [octodns/octodns-etchosts](https://github.com/octodns/octodns-etchosts)
* [ ] [octodns/octodns-gandi](https://github.com/octodns/octodns-gandi)
* [ ] [octodns/octodns-gcore](https://github.com/octodns/octodns-gcore)
* [x] [octodns/octodns-googlecloud](https://github.com/octodns/octodns-googlecloud)
* [ ] [octodns/octodns-hetzner](https://github.com/octodns/octodns-hetzner)
* [x] [octodns/octodns-mythicbeasts](https://github.com/octodns/octodns-mythicbeasts)
* [x] [octodns/octodns-ns1](https://github.com/octodns/octodns-ns1)
* [ ] [octodns/octodns-ovh](https://github.com/octodns/octodns-ovh)
* [ ] [octodns/octodns-powerdns](https://github.com/octodns/octodns-powerdns)
* [x] [octodns/octodns-rackspace](https://github.com/octodns/octodns-rackspace)
* [ ] [octodns/octodns-route53](https://github.com/octodns/octodns-route53)
* [x] [octodns/octodns-selectel](https://github.com/octodns/octodns-selectel)
* [ ] [octodns/octodns-transip](https://github.com/octodns/octodns-transip)
* [x] [octodns/octodns-ultra](https://github.com/octodns/octodns-ultra)

**Comment by ross** [comment]
Made a pass through all the modules updating all the requirements and making sure they're passing with 0.9.16. PRs that do so are all linked up above. Will re-run the test suite once they've all been merged which should get things green.

**Comment by ross** [comment]
Most of these have merged, the ones that haven't are waiting on other PRs to ship first and should be soon-ish.

Turned out that only a handful of them were problems with the `Zone.changes` bit and most were due to having "bad" data in their config files that didn't match up with the tests. I.e. in the past unit.tests.yaml and the fixtures/code didn't have to match up b/c changes ignored them, but now they don't and the data needed to match. Anyway, this should be sorted in the next week or so...

**Comment by ross** [comment]
Ah. We have a couple failing due to the tests assuming change order. Again I think this is fine and just a side effect of assumptions tests were making and not an issue for actual uses of octoDNS...

**Comment by ross** [comment]
As of https://github.com/octodns/octodns/actions/runs/1971765060 everything is passing.

**Comment by istr** [comment]
> As of https://github.com/octodns/octodns/actions/runs/1971765060 everything is passing.

Just out of curiosity: is there any means to assure that this keeps passing when providers change?

That is to say: is there some sort of trigger that re-checks in case a provider updates their code?

**Comment by ross** [comment]
> Just out of curiosity: is there any means to assure that this keeps passing when providers change?

It was heavy enough that I didn't want to run it on every branch commit. For now it's manually run when desired. Ideally there's be some way to have it run before merge. I don't see a clean way to do that atm.

**Comment by ross** [comment]
Might be sort of possible with required statuses. I can't see a way to kick it off at the right time, but I may be able to mark one or all of the ci job's are required to merge. That would at least require someone go in and manually kick off the job before merge.

**Comment by ross** [comment]
https://github.com/octodns/terraformed/pull/7 will fill out all the required contexts on repos which I believe should (additionally) force the modules tests to be manually run before merge. If/when we come up with or find a good way to trigger them at an appropriate point that would be even better.
