### ISSUE TITLE
Publish a JSON Schema

### ISSUE THREAD

**Issue by sjparkinson** [octodns/octodns#909]
I'm reviewing our VS Code extensions settings for an OctoDNS based repository.

It'd be amazing to get a JSON Schema published for the OctoDNS configuration.

The schema could be added to [SchemaStore/schemastore](https://github.com/SchemaStore/schemastore/tree/master/src/schemas/json) (published to https://www.schemastore.org/api/json/catalog.json), which is used by the [YAML extension](https://github.com/redhat-developer/vscode-yaml#extension-settings).

If there's support for this I'd be happy to look at raising a pull request.

**Comment by sjparkinson** [comment]
Here's a first pass at a schema to add context:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/Financial-Times/dns/main/schema.json",
  "title": "OctoDNS zone file",
  "type": "object",
  "patternProperties": {
    ".*": {
      "properties": {
        "ttl": {
          "type": "integer",
          "minimum": 0
        },
        "type": {
          "type": "string",
          "enum": [
            "A",
            "AAAA",
            "ALIAS",
            "CAA",
            "CNAME",
            "DNAME",
            "LOC",
            "MX",
            "NAPTR",
            "NS",
            "PTR",
            "SPF",
            "SRV",
            "SSHFP",
            "TLSA",
            "TXT",
            "URLFWD"
          ]
        },
        "value": {
          "type": "string"
        },
        "values": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "type"
      ],
      "anyOf": [
        {
          "required": [
            "value"
          ]
        },
        {
          "required": [
            "values"
          ]
        }
      ]
    }
  }
}
```

This doesn't deal with [multiple records](https://github.com/octodns/octodns/blob/master/docs/records.md#multiple-records).

**Comment by ross** [comment]
Don't mind it conceptually, but the idea of schemas living divorced in a repo separate from the code that implements them seems like a bad. As soon as it's committed it'd start drifting out of sync.

**Comment by sjparkinson** [comment]
> Don't mind it conceptually, but the idea of schemas living divorced in a repo separate from the code that implements them seems like a bad. As soon as it's committed it'd start drifting out of sync.

That I totally understand, good feedback thanks. Having a quick look at what could enable this [pydanic](https://pydantic-docs.helpmanual.io/) seemed to be the suggested Python library from the JSON Schema project.

I'm not got to be able to spend the time on such a refactor so I'll close this for now.

**Comment by wiktor-k** [comment]
Does closing this ticket mean that external contributions implementing that are not welcome or just that you're not actively working on it?

I think having a way to statically validate yamls *and* offer nice IDE auto-completion is really, *really* nice. (I'm using that for Kubernetes and other yaml-based ecosystems). For example it took me some time to figure out how to correctly add `HTTPS` type record while all of that could be offered from the IDE. That said, I understand that adding this feature is quite complex.

Anyway, thanks for octodns, I really enjoy using it! 👋

**Comment by ross** [comment]
It's an interesting idea and I'm not opposed to it, but it's not actively being worked on.

Closely related it went pretty deep with jsonschema in https://github.com/octodns/octodns/pull/1272. That ran into hiccups/shortcomings that were ultimately blockers.

**Comment by ross** [comment]
Played around with claude and generated https://github.com/octodns/octodns/pull/1373 based on the previous work. It's used for generating the schema file, but not validation (which was lacking.) Still a lot of review and tweaking to do, but it's a start.

**Comment by wiktor-k** [comment]
Wow, really cool that there's already something 🤯 

I'll test it out on Monday!

> and future SchemaStore submission.

FWIW, some projects just keep the file in the repository itself: https://github.com/aquasecurity/trivy/issues/9970#issuecomment-3705370072 but schema store would be a 🍒 on top!

Anyway, thanks for your time! 👋

**Comment by ross** [comment]
> FWIW, some projects just keep the file in the repository itself: [aquasecurity/trivy#9970 (comment)](https://github.com/aquasecurity/trivy/issues/9970#issuecomment-3705370072) but schema store would be a 🍒 on top!

Yeah. Not opposed to that so long as it is managed/lives in the repo and is pushed there or something like that.

**Comment by ross** [comment]
https://github.com/octodns/octodns/pull/1375 publishes a schema doc. Future releases will include it. For now the links will be broken, but they'll start working as things are released going forward.

**Comment by ross** [comment]
Circling back.

## Docs:
* https://octodns.readthedocs.io/en/latest/configuration.html#json-schema-for-zone-yaml-files
* https://octodns.readthedocs.io/en/latest/_static/octodns.schema.json (dev)

## Modeline

    # yaml-language-server: $schema=https://octodns.readthedocs.io/en/latest/_static/octodns.schema.json

## nvim Example

<img width="1392" height="336" alt="image" src="https://github.com/user-attachments/assets/7f0bb665-b54e-4ba2-968e-abff75d9426e" />

**Comment by wiktor-k** [comment]
I just tried it on my zones and it works beautifully 🤩 thanks!

There's still room for improvement, e.g. the `HTTPS` record seems to specify `svcparams` as just an object:

```json
                "properties": {
                  "svcparams": {
                    "additionalProperties": true,
                    "type": "object" // <-- just an object
                  },
                  "svcpriority": {
                    "maximum": 65535,
                    "minimum": 0,
                    "type": "integer"
                  },
                  "targetname": {
                    "type": "string"
                  }
                },
                "required": [
                  "svcpriority",
                  "targetname"
                ],
 ```

While it could offer more fine grained types for e.g. ipv4hint etc:

```yaml
arm.services:
  - ttl: 300
    type: HTTPS
    values:
    - svcparams:
        alpn:
        - h3
        - h2
        ipv4hint:
        - 158.101.211.162 # <-- more validation possible for IPv4 addresses etc.
        ipv6hint:
        - 2603:c022:c009:16ee:0:79aa:5d2b:b1df
      svcpriority: 1
      targetname: .
```

(Not sure if that's the limitation of Python data model here...)

One way or another, this is already a big step forward! Editing zone files is such a pleasure now.

Thank you for the extremely fast turnaround :) and have a great rest of the weekend! 👋

**Comment by ross** [comment]
> There's still room for improvement, e.g. the `HTTPS` record seems to specify `svcparams` as just an object:

Yeah. All of the schema stuff currently is a direct translation of the validations implemented by octoDNS

> (Not sure if that's the limitation of Python data model here...)

Not a limitation, just a shortcoming :grin:  This was part of the reason I looked into using jsonschema for octoDNS's validation engine. It seemed like it'd make it cleanly to do much more detailed/complete validation. Was dissapointed that it's error messages weren't useful and seemed more designed for the use case of showing errors inline and not printing them out at a terminal.

I would like to make some passes through improving the validations, but until then I'd lean towards keeping the validations and the jsonschema inline with each other and not having one validate things that the other doesn't.

**Comment by wiktor-k** [comment]
> I would like to make some passes through improving the validations, but until then I'd lean towards keeping the validations and the jsonschema inline with each other and not having one validate things that the other doesn't.

Oh yeah, sounds like a sensible plan!

I guess I just didn't know how these validations worked for `HTTPS` records. (Notabene maybe that's me but the docs at https://octodns.readthedocs.io/en/latest/api/records/octodns.record.https.html#octodns.record.https.HttpsRecord._type look to be primarily aimed at octodns developers or folks writing providers not regular users... I think a simple example there for all records would be good idea (unless I missed them somewhere). These esoteric ones such as `HTTPS` especially. (I had to grep github for examples ;)).

Okay, I don't want to inflate this ticket with unrelated stuff. Thanks for working on the Schema. I really appreciate it! 🙇

**Comment by ross** [comment]
> Notabene maybe that's me but the docs at https://octodns.readthedocs.io/en/latest/api/records/octodns.record.https.html#octodns.record.https.HttpsRecord._type look to be primarily aimed at octodns developers or folks writing providers not regular users

It's an OSS project so what managed to get documented is what's there :grin:, there's quite a bit of "user" doc in the Getting Started, Configuration, and Examples sections. It's probably about 50/50 in reality, but not obvious if you just  scan the TOC.

**Comment by wiktor-k** [comment]
> It's an OSS project so what managed to get documented is what's there 😁

Haha, right! I think I was wondering out loud if I should contribute some stuff that I'd expect there. No promises but it seems you're open to me extending these :)
