### ISSUE TITLE
'collections' has not attribute 'Iterable'

### ISSUE THREAD

**Issue by brianeclow** [octodns/octodns#921]
Testing `0.9.19`, while executing a `doit`, I got the following error:

```Traceback (most recent call last):
  File "dns/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "dns/env/lib/python3.10/site-packages/octodns/cmds/sync.py", line 64, in main
    manager.sync(
  File "dns/env/lib/python3.10/site-packages/octodns/manager.py", line 611, in sync
    total_changes += target.apply(plan)
  File "dns/env/lib/python3.10/site-packages/octodns/provider/base.py", line 253, in apply
    self._apply(plan)
  File "dns/env/lib/python3.10/site-packages/octodns_ns1/__init__.py", line 1558, in _apply
    getattr(self, f'_apply_{class_name}')(ns1_zone, change)
  File "dns/env/lib/python3.10/site-packages/octodns_ns1/__init__.py", line 1506, in _apply_Create
    self._client.records_create(zone, domain, _type, **params)
  File "dns/env/lib/python3.10/site-packages/octodns_ns1/__init__.py", line 107, in call
    new_record = func(self, zone, domain, _type, **params)
  File "dns/env/lib/python3.10/site-packages/octodns_ns1/__init__.py", line 234, in records_create
    return self._try(self._records.create, zone, domain, _type, **params)
  File "dns/env/lib/python3.10/site-packages/octodns_ns1/__init__.py", line 261, in _try
    return method(*args, **kwargs)
  File "dns/env/lib/python3.10/site-packages/ns1/rest/records.py", line 115, in create
    body = self._buildBody(zone, domain, type, **kwargs)
  File "dns/env/lib/python3.10/site-packages/ns1/rest/records.py", line 101, in _buildBody
    body["answers"] = self._getAnswersForBody(kwargs["answers"])
  File "dns/env/lib/python3.10/site-packages/ns1/rest/records.py", line 43, in _getAnswersForBody
    elif not isinstance(answers, collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'
```

I returned to the older version `0.9.17`, and the error persists. From a quick search, it looks like `collections.Iterable` has been deprecated, and now removed. It was replaced with `collections.abc.Iterable`.

This looks to be a python `3.10.6` issue? I rebuilt my virtualenv with python `3.9.13`, and it functioned as expected.

**Comment by ross** [comment]
> File "dns/env/lib/python3.10/site-packages/ns1/rest/records.py", line 43, in _getAnswersForBody
>     elif not isinstance(answers, collections.Iterable):

Looks like that's down in the ns1 client lib based on the stack trace.

> This looks to be a python `3.10.6`

Which explains why we don't see it in CI where we have 3.10, https://github.com/octodns/octodns/blob/c92734f7a6d6a69f479b236e3a927c77c8333aac/.github/workflows/main.yml#L11

Guessing ns1 hasn't yet verified their client lib against that version.

> I returned to the older version `0.9.17`, and the error persists. From a quick search, it looks like `collections.Iterable` has been deprecated, and now removed. It was replaced with `collections.abc.Iterable`.

We don't seem to use `collections.Iterable` in octoDNS core, but I vaguely remember running into warnings about it, probably in one of the provider modules (don't see it now) or in another python project of mine.

**Comment by ross** [comment]
Ah, knew I'd hit it somewhere, looks like the NS1 provider uses `collections.abc.Mapping`

https://github.com/octodns/octodns-ns1/blame/a2aaa7f6fa82670aae36d9cc776b1180b590a67b/octodns_ns1/__init__.py#L7 which was updated when 3.10 was added to its CI list.

**Comment by brianeclow** [comment]
I found octodns was importing defaultdict from collections in `octodns` when I did a search before filing this issue. It looks like the data was a bit stale, and it is only showing up in a helper script, now.

My bad, I thought I checked both providers on the test zone. 😅

**Comment by brianeclow** [comment]
Confirmation
I am using octodns-ns1 version `0.0.2` with python `3.10.6` gets that error, and the route53 apply/doit didn't show the error.
Pulled the main branch of octodns-ns1, and the error persists.

Shall I close this issue and reopen in the octodns-ns1 repo?

**Comment by ross** [comment]
> Shall I close this issue and reopen in the octodns-ns1 repo?

The problem is actually in https://github.com/ns1/ns1-python/, rather than octodns/octodns-ns1. 

It looks like @istr actually fixed the underlying issue ~2 weeks ago in https://github.com/ns1/ns1-python/pull/107, specifically https://github.com/ns1/ns1-python/pull/107/files#diff-46d1e6289881ceb01279f697ff44b91f4f0b22abf467f8bfa709397cc51f4a19

Doesn't looks like there's been any releases since that merge so it'd only be available if you pin a SHA rather than release. https://github.com/ns1/ns1-python/tags

**Comment by brianeclow** [comment]
This appears to be the issue related: https://github.com/ns1/ns1-python/issues/108
Pinning to the SHA solved the problem.
I will inquire with `ns1-python` about a new version bump. Thank you.
