### ISSUE TITLE
Sub-Zone Delegation

### ISSUE THREAD

**Issue by brianeclow** [octodns/octodns#941]
I remember reading about handling the delegation of a sub-zone, but I can't seem to find the issue/PR again.

The scenario being explored:

- We need a sub-zone delegated to a differing provider
- We have an internal requirement that all entries are tracked via version control and our automation
- Via a control mechanism, the change request can be fully automated

I believe octoDNS's management aspects can be leveraged to assist:

- Add the new provider to the "configuration" yaml
- Add the NS delegation to the existing zone
- Creating the sub-zone delegation as a "managed zone" within the configuration yaml
- Creating the sub-zone's zone yaml

Is this a correct assumption based on my memory and inferred understanding of the inner workings of the tool?

**Comment by ross** [comment]
All of the above makes sense to me and should allow you to delegate a subzone to provider that isn't the same as the parent and have octoDNS manage them both. 

You may need to add the provider & subzone config prior to creating the NS delegation with a lot of providers, just to figure out what the NS records need to be.

**Comment by brianeclow** [comment]
I figured there would the potential for a hard order of operations.

Thank you for confirming my thought experiment.
