### ISSUE TITLE
Make it possible to set log level

### ISSUE THREAD

**Issue by runephilosof-abtion** [octodns/octodns#943]
It would be nice to be able to set the log level.
I would like to have warnings and the summary.

```
(env) [octodns]$ octodns-sync --config-file=./config/production.yaml --log-stream-stdout | grep -vE "^([^ ]+ +){2}INFO"
2022-09-27T09:22:17  [127262042330688] WARNING CloudflareProvider[cloudflare] root NS record not supported for example.com.; ignoring it
********************************************************************************
No changes were planned
********************************************************************************
```

**Comment by brianeclow** [comment]
Understanding this is scope creep, I would love to be able to leverage more of the logger. Set an "error" file, in addition to providing the log level. Right now, I have a wrapper that splits it apart, but this isn't ideal.

**Comment by ross** [comment]
Pretty trivial to write custom plan output classes to do anything you want with it. There's a few existing ones in there already, e.g. Markdown https://github.com/octodns/octodns/blob/main/octodns/provider/plan.py#L206

Adding support for file based logging config might be interesting to look into https://docs.python.org/3/library/logging.config.html#logging.config.fileConfig. IIRC that allows you to configure loggers, handlers, levels, etc. There may even be some filtering support in there.

**Comment by ross** [comment]
Added `--logging-config` support over in https://github.com/octodns/octodns/pull/945#issuecomment-1262839550, pretty happy with how that came out. It should give nearly complete control over things.
