### ISSUE TITLE
missing "requirements.txt" on fresh Ubuntu 20-04 install

### ISSUE THREAD

**Issue by ninjaix** [octodns/octodns#952]
Setting up a fresh install and not seeing the requirements.txt or scripts directory being installed.  At least that is what I am thinking is missing if I do  test dump.
octodns-dump: error: the following arguments are required: source
(env) root@octodns:~/octodns# octodns-dump --config-file ./config.yaml --output-dir=zones/real-domain.name cloudflare
usage: octodns-dump [-h] --config-file CONFIG_FILE --output-dir OUTPUT_DIR [--output-provider OUTPUT_PROVIDER] [--lenient] [--split]
                    [--version] [--log-stream-stdout] [--log-syslog] [--syslog-device SYSLOG_DEVICE] [--syslog-facility SYSLOG_FACILITY]
                    [--debug] [--quiet] [--logging-config LOGGING_CONFIG]
                    zone source [source ...]
octodns-dump: error: the following arguments are required: source

**Comment by ross** [comment]
> octodns-dump: error: the following arguments are required: source

The `source [source ...]` argument(s) are referring to the place where the records will be pulled from for the dump. E.g. if you have data in Cloudflare and a provider configured named `cloudflare` then you'll likely want to use `cloudflare` as that argument. octodns-dump will then pull the supported records from there and dump them into the specified location.
