### ISSUE TITLE
Feature Request: Linode Provider

### ISSUE THREAD

**Issue by yzguy** [octodns/octodns#970]
Create a provider for Linode's DNS

Mostly a TODO for me :P

**Comment by timwsuqld** [comment]
Still interested in this

**Comment by ibizaman** [comment]
Still interested.

**Comment by timwsuqld** [comment]
Still interested

**Comment by timwsuqld** [comment]
Still interested in this

**Comment by ross** [comment]
Going to go ahead and close this. That's not to say that a Linode provider will never exist, just to knowledge that it's not something that's actively being worked on or planned. Afaik yzguy no longer works there and I have no specific plans to work on it absent someone interested in funding it's development. If a 3rd party wants to pick it up, starting with https://github.com/octodns/octodns-template, we would be happy to answer questions and help things along if necessary.
