### ISSUE TITLE
Automatically maintain a reverse dns zone based on zones a records

### ISSUE THREAD

**Issue by hijak** [octodns/octodns#972]
Hi

i am struggling to find a way to automatically populate reverse dns zones based on other zones a records. is this a feature i can request?

**Comment by ross** [comment]
TL;DR is that it's possible to create fairly simple providers that are sufficient for specific use-cases, but I spent quite a bit of time with multiple approaches to implementing something universal without success. They all grew super complicated and edge-case-y really quickly.

**Comment by hijak** [comment]
ah got ya. i would ask chatgpt but i think the api has moved on since it learnt about it

**Comment by ross** [comment]
If you want to share details about your setup and what you're looking to do I can see if there's clean ways to pull it off.

**Comment by hijak** [comment]
well we use yaml sources to sync to two pdns instances. this is all done in a pipeline. ideally octodns would create ptr from A records it finds in the yaml zones and just maintain it that way. or another way would be some script to generate the rdns zone files from the a records it finds and then we can apply them like everything else

**Comment by ross** [comment]
OK. The main hiccup in that sort of setup is that the reverse zones have to run after all of the forward/normal zones have completed in order to know what all records were created. There's an extra complication due to things running in parallel. Let me look over my old WIP branches to see if anything looks promising for that case.

**Comment by ross** [comment]
See https://github.com/octodns/octodns/pull/974 for a potential solution to this

**Comment by hijak** [comment]
very exciting thank you for your hard work! ill keep an eye on the merge
