### ISSUE TITLE
`<provider-specific-requirements>`

### ISSUE THREAD

**Issue by stappersg** [octodns/octodns#976]
The `README.md` has
```text
pip install octodns <provider-specific-requirements>
```
and the link [providers table](https://github.com/octodns/octodns#providers).

As a _newbie_ to `octodns` I can't tell what is ment with `<provider-specific-requirements>`.

Are they Python modules? Like modules for  `XML` or `JSON`???

Are they _"octodns providers"_ like `octodns_bind` is one?

And `<provider-specific-requirements>` is plural. How to express that multple requirement**s** are wanted?    (space separated, space separated between qoutes  or comma seperated???)

Assumption, I do:
```
pip install octodns foo
```
and later I need into addition of `foo` also `bar`.  How to add an additional `provider-specific-requirement`?

**Comment by brianeclow** [comment]
`<provider-specific-requirements>` has specific context to your leveraged DNS provider. For example, if you are using Cloudflare, then the specific provider requirement is `octodns-cloudflare`, which will result in the pip install:

```bash
pip install octodns octodns-cloudflare
```

All internal dependencies to both octoDNS packages will be installed.
