### ISSUE TITLE
AWS Route 53 changes being applied only one per run

### ISSUE THREAD

**Issue by rafaelfuchsbr** [octodns/octodns#985]
I'm working on a zone where I had like 64 updates to be applied, but octoDNS is only applying one update per run.
So I run `octodns-sync --config-file=./config/octodns.yaml --doit` and it applies only one update.
Then I run it again and now I have 63 updates. And then again and again... the number of updates keep going down one by one.

I've ran the command with the `--debug` flag, but there's no errors or relevant information that is helping me find the root cause.

I see this in the logs,
```
INFO  Route53Provider[route53] _apply:   sending change request for batch of 62 mods, 62 ResourceRecords
INFO  Manager sync:   62 total changes
```

and next run I get:
```
INFO  Route53Provider[route53] _apply:   sending change request for batch of 61 mods, 61 ResourceRecords
INFO  Manager sync:   61 total changes
```

Any clue what's going on?

**Comment by rafaelfuchsbr** [comment]
Nevermind, just found this one: https://github.com/octodns/octodns-route53/issues/45

**Comment by ross** [comment]
If you happen to have paid support please point them towards that issue. The public forum (as expected) got no traction and I don't have contacts there at this point so don't hold out much hope.

**Comment by rafaelfuchs-mb** [comment]
I've contacted them through my company and they have opened an internal ticket to investigate this.
I will share updates here once I have something.

**Comment by ross** [comment]
> I've contacted them through my company and they have opened an internal ticket to investigate this. I will share updates here once I have something.

Awesome, Thanks!
