### ISSUE TITLE
Support relative record values, supress FQDN validation

### ISSUE THREAD

**Issue by rafaelfuchsbr** [octodns/octodns#987]
octoDNS is currently checking if domain name values are FQDN, but, according to [RFC1035](https://datatracker.ietf.org/doc/html/rfc1035), it should support relative domain names.

> &lt;domain-name&gt;s make up a large share of the data in the master file.
The labels in the domain name are expressed as character strings and
separated by dots.  Quoting conventions allow arbitrary characters to be
stored in domain names.  Domain names that end in a dot are called
absolute, and are taken as complete.  Domain names which do not end in a
dot are called relative; the actual domain name is the concatenation of
the relative part with an origin specified in a $ORIGIN, $INCLUDE, or as
an argument to the master file loading routine.  A relative name is an
error when no origin is available.

I understand that the `lenient` option allow me to move forward with the process, but it's still showing the warning message in a way that can lead people to believe that this is an error/invalid value, which is not the case.

**Comment by ross** [comment]
I think this came through while I was traveling and I managed to miss it then.

I think I'd personally land at using the FQDN being a best practice even if it's not required and from that POV the validation would be encouraging that.

At the same time I'm not a fan of throwing an error when someone doesn't w/o using lenient. The FQDN check was probably originally intended more to just validate that things are sane more than specifically a FQDN. 

Will have to think about this one a bit.

**Comment by ross** [comment]
> octoDNS is currently checking if domain name values are FQDN, but, according to [RFC1035](https://datatracker.ietf.org/doc/html/rfc1035), it should support relative domain names.

Can you quote/copy-n-paste the section of this you feel like is related to relative values?

I started doing some deeper testing on https://github.com/octodns/octodns/pull/1023 and so far 100% of providers are putting `.` on the end of the relative values when they serve them out. E.g. Azure:

<img width="325" alt="Screen Shot 2023-07-18 at 4 21 21 PM" src="https://github.com/octodns/octodns/assets/12789/0f0e4e50-6b1f-4058-8f05-c0d455adc0ad">

...

<img width="839" alt="Screen Shot 2023-07-18 at 4 20 59 PM" src="https://github.com/octodns/octodns/assets/12789/c94d05d6-b609-40a2-97b1-e8d2a41fa916">


When queried:

```console
(env) coho:octodns ross$ dig +short relative.xormedia.com
www.
```

And when I hit it with curl/wget/etc:


```console
(env) coho:octodns ross$ curl  http://relative.xormedia.com
curl: (6) Could not resolve host: relative.xormedia.com
```

As best as I can tell it's using the localhost's search order to resolve the relative `www.` value, which surprises me given the `.` on the end. 

What's the use-cases for this?

**Comment by istr** [comment]
For what it is worth, the `relative` statement refers to the format of master files _only_ (it is part of section `5. MASTER FILES`/`5.1. Format`). Apart from that

> Domain names which do not end in a dot are called relative; the actual domain name is the concatenation of
the relative part with an origin specified in a $ORIGIN, $INCLUDE, or as an argument to the master file loading routine.
A relative name is an error when no origin is available.

From the initial post, it is unclear to me if this request refers to the zone file support in `octodns-bind` or generally to  support assembly from relative name parts.

If zone file support is targeted, this should be addressed in `octodns-bind`. If generic support is requested, I would argue that `octodns` is opinionated and could still consider FQDNs in targets best practice.

@rafaelfuchsbr could you clarify what was the original use-case / intention of your request?
