### ISSUE TITLE
Missing TinyDNS data source record types

### ISSUE THREAD

**Issue by dbuenoparedes** [octodns/octodns#999]
I have been doing some TinyDNS to OctoDNS conversions recently and noticed that there are some record types that OctoDNS source script is missing:
- `&`: 
  - example: `&fqdn:ip:x:ttl:timestamp:lo`
  - Name server for domain fqdn. tinydns-data creates
    - an NS record showing `x.ns.fqdn` as a name server for `fqdn` and
    - an A record showing ip as the IP address of `x.ns.fqdn.`
- `Z`: 
  - example: `Zfqdn:mname:rname:ser:ref:ret:exp:min:ttl:timestamp:lo`
    - SOA record for `fqdn` showing `mname` as the primary name server, `rname` (with the first `.` converted to `@`) as the contact address, `ser` as the serial number, `ref` as the refresh time, `ret` as the retry time, `exp` as the expire time, and `min` as the minimum time. `ser`, `ref`, `ret`, `exp`, and `min` may be omitted; they default to, respectively, the modification time of the `data` file, 16384 seconds, 2048 seconds, 1048576 seconds, and 2560 seconds. 
- `'`:
  - example: `'fqdn:s:ttl:timestamp:lo`
    - TXT ("text") record for `fqdn.` tinydns-data creates a TXT record for `fqdn` containing the string `s`. You may use octal `\nnn` codes to include arbitrary bytes inside `s`; for example, `\072` is a _colon_. 

All this info has been taken from https://cr.yp.to/djbdns/tinydns-data.html, 1st entry from the **Common data lines** and 2nd and 3rd entries from the **Uncommon data lines** respectively.

I could get around this by using the OctoDNS zone transfer (axfr) source by running TinyDNS's axfrdns program (https://cr.yp.to/djbdns/axfrdns.html) with the TinyDNS data files containing these type of records.

I would add them and fix it myself but I'm a total noob with python, sorry.

Thank you very much.

Edit: the specific part of the TinyDNS source python script code I forgot to add is this one: https://github.com/octodns/octodns/blob/main/octodns/source/tinydns.py#L124-L135

**Comment by ross** [comment]
> I have been doing some TinyDNS to OctoDNS conversions recently and noticed that there are some record types that OctoDNS source script is missing:

`TinyDNSSource` definitely is partial, I believe what was initially added as just what was present in the configs we were converting at the time. 

> `&`:
> * example: `&fqdn:ip:x:ttl:timestamp:lo`
> * Name server for domain fqdn. tinydns-data creates

If I understand it correctly, octoDNS should be able to support this.

> `Z`:
> * example: `Zfqdn:mname:rname:ser:ref:ret:exp:min:ttl:timestamp:lo`
>   
>   * SOA record for `fqdn` showing `mname`

Unfortunately octoDNS doesn't support managing SOA records as support for it across providers varies widely and for the most part isn't viable.

> `'`:
> * example: `'fqdn:s:ttl:timestamp:lo`
>   
>   * TXT ("text") record for `fqdn.`

Should be possible. 

> I would add them and fix it myself but I'm a total noob with python, sorry.

It can go onto the TODO list, but no clue on timeline.

**Comment by ross** [comment]
Fixed by https://github.com/octodns/octodns/pull/1020
